/**
 * Census Autopilot V2.2 — Official-first + Rooms breakthrough + real production waves.
 * DRY-RUN ONLY. No Airtable. No Webhound. Cvent never production evidence.
 */

export const AUTOPILOT_V22_VERSION = "census-autopilot-v2.2-official-first-rooms";

export const OUT_REL = "data/research-engine-v2/census-autopilot-v2-2-official-first-rooms";

export const V21_OUT_REL = "data/research-engine-v2/census-autopilot-v2-1-production-readiness";
export const V2_OUT_REL = "data/research-engine-v2/census-autopilot-v2-full-universe";

/** Adapter capability classes for brand-family map */
export const ADAPTER_CLASS = Object.freeze({
  STRONG_NATIVE: "KNOWN BRAND FAMILY — STRONG NATIVE ADAPTER",
  PARTIAL: "KNOWN BRAND FAMILY — PARTIAL ADAPTER",
  NO_ADAPTER: "KNOWN BRAND FAMILY — NO ADAPTER",
  SOFT_BRAND: "SOFT BRAND / COLLECTION",
  INDEPENDENT: "INDEPENDENT",
  UNKNOWN: "UNKNOWN AFFILIATION",
});

export const FAMILY_ADAPTER_META = Object.freeze({
  IHG: {
    class: ADAPTER_CLASS.STRONG_NATIVE,
    directory: true,
    property_detail: true,
    structured: true,
    property_id: "ihg_hotel_code",
    rooms_native: "PARTIAL_EMPTY_FIELD",
    address: true,
    coordinates: true,
    phone: true,
    amenities: true,
    status: true,
  },
  Hilton: {
    class: ADAPTER_CLASS.STRONG_NATIVE,
    directory: true,
    property_detail: true,
    structured: true,
    property_id: "hilton_ctyhocn",
    rooms_native: "GRAPHQL_PROSE_OCCASIONAL",
    address: true,
    coordinates: true,
    phone: true,
    amenities: true,
    status: true,
  },
  Choice: {
    class: ADAPTER_CLASS.STRONG_NATIVE,
    directory: true,
    property_detail: true,
    structured: true,
    property_id: "choice_property_id",
    rooms_native: "SPARSE_HTML",
    address: true,
    coordinates: false,
    phone: true,
    amenities: true,
    status: true,
  },
  Marriott: {
    class: ADAPTER_CLASS.PARTIAL,
    directory: true,
    property_detail: true,
    structured: "embedded_state",
    property_id: "marriott_marsha",
    rooms_native: "FACT_SHEET_OR_OPENING",
    address: true,
    coordinates: true,
    phone: true,
    amenities: true,
    status: true,
  },
  Accor: {
    class: ADAPTER_CLASS.NO_ADAPTER,
    directory: true,
    property_detail: true,
    structured: "json_ld_possible",
    property_id: "accor_property_id",
    rooms_native: "OWNER_OR_OPENING",
    address: true,
    coordinates: false,
    phone: true,
    amenities: true,
    status: true,
  },
  Wyndham: {
    class: ADAPTER_CLASS.NO_ADAPTER,
    directory: true,
    property_detail: true,
    structured: false,
    property_id: "wyndham_property_id",
    rooms_native: "OWNER_OR_OPENING",
    address: true,
    coordinates: false,
    phone: true,
    amenities: true,
    status: true,
  },
  Hyatt: {
    class: ADAPTER_CLASS.NO_ADAPTER,
    directory: true,
    property_detail: true,
    structured: "embedded_state",
    property_id: "hyatt_property_id",
    rooms_native: "FACT_SHEET_OR_OPENING",
    address: true,
    coordinates: true,
    phone: true,
    amenities: true,
    status: true,
  },
  Minor: {
    class: ADAPTER_CLASS.NO_ADAPTER,
    directory: true,
    property_detail: true,
    structured: false,
    property_id: "minor_property_id",
    rooms_native: "FIRST_PARTY",
    address: true,
    coordinates: false,
    phone: true,
    amenities: false,
    status: true,
  },
  Melia: {
    class: ADAPTER_CLASS.NO_ADAPTER,
    directory: true,
    property_detail: true,
    structured: false,
    property_id: "melia_property_id",
    rooms_native: "OWNER_OR_OPENING",
    address: true,
    coordinates: false,
    phone: true,
    amenities: true,
    status: true,
  },
  Barcelo: {
    class: ADAPTER_CLASS.NO_ADAPTER,
    directory: true,
    property_detail: true,
    structured: false,
    property_id: "barcelo_property_id",
    rooms_native: "OWNER_OR_OPENING",
    address: true,
    coordinates: false,
    phone: true,
    amenities: true,
    status: true,
  },
  RIU: {
    class: ADAPTER_CLASS.NO_ADAPTER,
    directory: true,
    property_detail: true,
    structured: false,
    property_id: "riu_property_id",
    rooms_native: "OWNER_OR_OPENING",
    address: true,
    coordinates: false,
    phone: true,
    amenities: true,
    status: true,
  },
  Iberostar: {
    class: ADAPTER_CLASS.NO_ADAPTER,
    directory: true,
    property_detail: true,
    structured: false,
    property_id: "iberostar_property_id",
    rooms_native: "OWNER_OR_OPENING",
    address: true,
    coordinates: false,
    phone: true,
    amenities: true,
    status: true,
  },
  Radisson: {
    class: ADAPTER_CLASS.NO_ADAPTER,
    directory: true,
    property_detail: true,
    structured: false,
    property_id: "radisson_property_id",
    rooms_native: "FIRST_PARTY",
    address: true,
    coordinates: false,
    phone: true,
    amenities: true,
    status: true,
  },
  Independent: {
    class: ADAPTER_CLASS.INDEPENDENT,
    directory: false,
    property_detail: false,
    structured: false,
    property_id: null,
    rooms_native: "FIRST_PARTY_OR_DEEP",
    address: false,
    coordinates: false,
    phone: false,
    amenities: false,
    status: false,
  },
});

export const VERIFIED_LIFECYCLE = Object.freeze({
  VERIFIED_GOLDEN_COMPLETE: "VERIFIED — GOLDEN COMPLETE",
  VERIFIED_MATERIAL_GAPS: "VERIFIED — MATERIAL GAPS",
  VERIFIED_ROOMS_PENDING: "VERIFIED — ROOMS PENDING",
  VERIFIED_FIRST_PARTY_PENDING: "VERIFIED — FIRST-PARTY VALIDATION PENDING",
  PARTIAL_IDENTITY_RESEARCH: "PARTIAL — IDENTITY/RESEARCH",
  UNRESOLVED: "UNRESOLVED",
});

export const WRITE_CLASS = Object.freeze({
  AUTO_WRITE_SAFE: "AUTO_WRITE_SAFE",
  CORROBORATED_WRITE: "CORROBORATED_WRITE",
  STEWARD_REVIEW: "STEWARD_REVIEW",
  FIRST_PARTY_VALIDATION: "FIRST_PARTY_VALIDATION",
  BLOCKED_RIGHTS: "BLOCKED_RIGHTS",
  PROHIBITED: "PROHIBITED",
});

/** SerpApi expected-value threshold (0–100). Below = skip paid call. */
export const SERPAPI_EV_THRESHOLD = Number(process.env.CAV22_SERPAPI_EV_THRESHOLD || 45);

export const PRIORITY_WAVE = Object.freeze({
  P0: "P0 identity integrity",
  P1: "P1 existing Verified <95%",
  P2: "P2 high-confidence branded new",
  P3: "P3 efficiently confirmable Cvent challenges",
  P4: "P4 independents",
  P5: "P5 hard cases",
});
