/**
 * Adaptive ownership research — shared contracts (V2 candidate-first controller).
 * Does not replace Brazil V1.1; routes into it when appropriate.
 */

export const PLAYBOOK_ID = Object.freeze({
  GENERAL_OWNERSHIP_DISCOVERY: "GENERAL_OWNERSHIP_DISCOVERY",
  TRANSACTION_CURRENT_OWNER: "TRANSACTION_CURRENT_OWNER",
  CORPORATE_ENTITY_RELATIONSHIP: "CORPORATE_ENTITY_RELATIONSHIP",
  FINANCING_PUBLIC_RECORD: "FINANCING_PUBLIC_RECORD",
});

export const ALL_PLAYBOOK_IDS = Object.freeze(Object.values(PLAYBOOK_ID));

/** Candidate types — high-recall research hypotheses, never auto-facts. */
export const OWNER_CANDIDATE_TYPE = Object.freeze({
  DIRECT_PROPERTY_OWNER: "DIRECT_PROPERTY_OWNER",
  OWNER_SPV: "OWNER_SPV",
  ECONOMIC_SPONSOR: "ECONOMIC_SPONSOR",
  DEVELOPER: "DEVELOPER",
  JV_PARTICIPANT: "JV_PARTICIPANT",
  REIT_OR_FUND: "REIT_OR_FUND",
  OPERATING_ENTITY: "OPERATING_ENTITY",
  HOTEL_OPERATOR: "HOTEL_OPERATOR",
  MANAGEMENT_COMPANY: "MANAGEMENT_COMPANY",
  HISTORICAL_OWNER: "HISTORICAL_OWNER",
  POSSIBLE_OWNER: "POSSIBLE_OWNER",
  UNKNOWN_RELATIONSHIP: "UNKNOWN_RELATIONSHIP",
});

export const CANDIDATE_VERIFICATION_STATUS = Object.freeze({
  PENDING: "PENDING",
  SUPPORTED: "SUPPORTED",
  REJECTED: "REJECTED",
  INSUFFICIENT: "INSUFFICIENT",
});

/**
 * Structured verification / routing rejection reasons.
 * Consumed by the playbook router — not decorative labels.
 */
export const STRUCTURED_REJECTION_REASON = Object.freeze({
  NO_OWNER_CANDIDATE: "NO_OWNER_CANDIDATE",
  OWNER_OPERATOR_CONFUSION: "OWNER_OPERATOR_CONFUSION",
  OPERATING_ENTITY_NOT_OWNER: "OPERATING_ENTITY_NOT_OWNER",
  HISTORICAL_OWNER: "HISTORICAL_OWNER",
  OWNERSHIP_DATE_UNCLEAR: "OWNERSHIP_DATE_UNCLEAR",
  OWNER_EVIDENCE_INSUFFICIENT: "OWNER_EVIDENCE_INSUFFICIENT",
  ENTITY_MATCH_UNCERTAIN: "ENTITY_MATCH_UNCERTAIN",
  ENTITY_LOCATION_CONFLICT: "ENTITY_LOCATION_CONFLICT",
  ENTITY_CONFLICT: "ENTITY_CONFLICT",
  JV_STRUCTURE_SUSPECTED: "JV_STRUCTURE_SUSPECTED",
  SOURCE_TOO_WEAK: "SOURCE_TOO_WEAK",
  SOURCE_NOT_ATTRIBUTABLE: "SOURCE_NOT_ATTRIBUTABLE",
  CURRENT_OWNER_UNCONFIRMED: "CURRENT_OWNER_UNCONFIRMED",
  FUND_RELATIONSHIP_UNCONFIRMED: "FUND_RELATIONSHIP_UNCONFIRMED",
  PROPERTY_RELATIONSHIP_UNCONFIRMED: "PROPERTY_RELATIONSHIP_UNCONFIRMED",
  RESEARCH_PATH_EXHAUSTED: "RESEARCH_PATH_EXHAUSTED",
  NO_USEFUL_NEW_EVIDENCE: "NO_USEFUL_NEW_EVIDENCE",
});

export const PLAYBOOK_OUTCOME = Object.freeze({
  CANDIDATES_GENERATED: "CANDIDATES_GENERATED",
  EVIDENCE_ADDED: "EVIDENCE_ADDED",
  NO_USEFUL_NEW_EVIDENCE: "NO_USEFUL_NEW_EVIDENCE",
  OWNER_SUPPORTED: "OWNER_SUPPORTED",
  BUDGET_BLOCKED: "BUDGET_BLOCKED",
  ERROR: "ERROR",
});

export const ADAPTIVE_CONTROLLER_VERSION = "adaptive-ownership-controller-v2";
