/**
 * GDI International Finalization Engine V1 — constants.
 * Ready / Watch thresholds unchanged. Finalization resolves disposition, not inflation.
 */

export const IFE_VERSION = "gdi_international_finalization_v1";

export const PILLAR_STRENGTH = Object.freeze({
  PROVEN: "PROVEN",
  STRONG: "STRONG",
  PLAUSIBLE: "PLAUSIBLE",
  MISSING: "MISSING",
  CONTRADICTED: "CONTRADICTED",
});

export const TARGET_HOTEL_FIT = Object.freeze({
  STRONG_FIT: "STRONG_FIT",
  PLAUSIBLE_FIT: "PLAUSIBLE_FIT",
  WEAK_FIT: "WEAK_FIT",
  NO_FIT: "NO_FIT",
  UNKNOWN: "UNKNOWN",
});

export const SELECTION_STATUS = Object.freeze({
  NOT_STARTED: "NOT_STARTED",
  EXPECTED: "EXPECTED",
  OPEN: "OPEN",
  UNDER_REVIEW: "UNDER_REVIEW",
  PARTIALLY_PLACED: "PARTIALLY_PLACED",
  PLACED: "PLACED",
  CLOSED: "CLOSED",
  UNKNOWN: "UNKNOWN",
});

export const SELECTION_MODEL = Object.freeze({
  CENTRAL_ROOM_BLOCK: "CENTRAL_ROOM_BLOCK",
  PREFERRED_HOTEL_LIST: "PREFERRED_HOTEL_LIST",
  OFFICIAL_HOTEL: "OFFICIAL_HOTEL",
  MULTI_HOTEL_PROGRAM: "MULTI_HOTEL_PROGRAM",
  SELF_BOOKING_RECOMMENDED_LIST: "SELF_BOOKING_RECOMMENDED_LIST",
  PCO_MANAGED: "PCO_MANAGED",
  DMC_MANAGED: "DMC_MANAGED",
  HOST_INSTITUTION_MANAGED: "HOST_INSTITUTION_MANAGED",
  PROCUREMENT_RFP: "PROCUREMENT_RFP",
  DIRECT_NEGOTIATION: "DIRECT_NEGOTIATION",
  UNKNOWN: "UNKNOWN",
});

export const FINAL_DISPOSITION = Object.freeze({
  READY: "READY",
  VALID_FUTURE_WATCH: "VALID_FUTURE_WATCH",
  COMPLETE_STRONG: "COMPLETE_STRONG",
  COMPLETE_PLAUSIBLE: "COMPLETE_PLAUSIBLE",
  PARTIAL_PACKET: "PARTIAL_PACKET",
  NO_TARGET_HOTEL_FIT: "NO_TARGET_HOTEL_FIT",
  SELECTION_ALREADY_CLOSED: "SELECTION_ALREADY_CLOSED",
  WRONG_DESTINATION: "WRONG_DESTINATION",
  NO_HOTEL_PROGRAM: "NO_HOTEL_PROGRAM",
  NO_TRAVELING_ENTITY: "NO_TRAVELING_ENTITY",
  NO_COMMERCIAL_PATH: "NO_COMMERCIAL_PATH",
  NO_CURRENT_HOTEL_PATH: "NO_CURRENT_HOTEL_PATH",
  WAITING_FOR_TRIGGER: "WAITING_FOR_TRIGGER",
  WAITING_FOR_PUBLICATION: "WAITING_FOR_PUBLICATION",
  WAITING_FOR_CONTROLLER_RESPONSE: "WAITING_FOR_CONTROLLER_RESPONSE",
  INSUFFICIENT_TRAVEL_PROOF: "INSUFFICIENT_TRAVEL_PROOF",
  UNKNOWN: "UNKNOWN",
});

export const EVIDENCE_ASK_CATEGORY = Object.freeze({
  HOTEL_SELECTION_STATUS: "HOTEL_SELECTION_STATUS",
  RATE_SUBMISSION: "RATE_SUBMISSION",
  LODGING_CONTROLLER: "LODGING_CONTROLLER",
  ROOM_BLOCK: "ROOM_BLOCK",
  PREFERRED_HOTEL_LIST: "PREFERRED_HOTEL_LIST",
  OVERFLOW: "OVERFLOW",
  RFP_TIMELINE: "RFP_TIMELINE",
  HOTEL_ELIGIBILITY: "HOTEL_ELIGIBILITY",
});

export const FINALIZATION_ELIGIBILITY = Object.freeze({
  COMPLETE_PLAUSIBLE: "COMPLETE_PLAUSIBLE",
  VALID_FUTURE_WATCH: "VALID_FUTURE_WATCH",
  PARTIAL_NEAR_COMPLETE: "PARTIAL_NEAR_COMPLETE",
  INELIGIBLE_SIGNAL_ONLY: "INELIGIBLE_SIGNAL_ONLY",
});
