/**
 * ADP Measurement Assurance V1 — version + pipeline states.
 * Permanent certification pipeline (not a one-off audit).
 */

export const ADP_MEASUREMENT_ASSURANCE_VERSION = "adp_measurement_assurance_v1";
export const ASSURANCE_RESOLVER_VERSION = "adp_assurance_subject_resolver_v1";
export const ASSURANCE_ENTITY_VERSION = "adp_assurance_entity_v1";
export const ASSURANCE_ATTRIBUTE_DICT_VERSION = "adp_attribute_dictionary_v1";
export const ASSURANCE_TERRITORY_DICT_VERSION = "adp_demand_territory_dictionary_v1";

/** Property/period lifecycle — customer PUBLISHED only after certification gates pass. */
export const PIPELINE_STATES = Object.freeze({
  OBSERVATION_CREATED: "OBSERVATION_CREATED",
  OBSERVATION_COMPLETE: "OBSERVATION_COMPLETE",
  PARSED: "PARSED",
  ASSURANCE_PENDING: "ASSURANCE_PENDING",
  ASSURANCE_RUNNING: "ASSURANCE_RUNNING",
  ASSURANCE_REVIEW_REQUIRED: "ASSURANCE_REVIEW_REQUIRED",
  CERTIFIED: "CERTIFIED",
  CERTIFIED_WITH_DISCLOSURES: "CERTIFIED_WITH_DISCLOSURES",
  NOT_CERTIFIED: "NOT_CERTIFIED",
  PUBLISHED: "PUBLISHED",
});

export const ASSURANCE_LAYERS = Object.freeze({
  OBSERVATION_INTEGRITY: "OBSERVATION_INTEGRITY",
  MEASUREMENT_INTEGRITY: "MEASUREMENT_INTEGRITY",
  COMPARABILITY_INTEGRITY: "COMPARABILITY_INTEGRITY",
  ANALYTICAL_COHERENCE: "ANALYTICAL_COHERENCE",
  PUBLICATION_INTEGRITY: "PUBLICATION_INTEGRITY",
});

/** Certification requires all five layers. */
export const REQUIRED_CERTIFICATION_LAYERS = Object.freeze([
  ASSURANCE_LAYERS.OBSERVATION_INTEGRITY,
  ASSURANCE_LAYERS.MEASUREMENT_INTEGRITY,
  ASSURANCE_LAYERS.COMPARABILITY_INTEGRITY,
  ASSURANCE_LAYERS.ANALYTICAL_COHERENCE,
  ASSURANCE_LAYERS.PUBLICATION_INTEGRITY,
]);

export const CERTIFICATION_OUTCOMES = Object.freeze({
  CERTIFIED: "CERTIFIED",
  CERTIFIED_WITH_DISCLOSURES: "CERTIFIED_WITH_DISCLOSURES",
  NOT_CERTIFIED: "NOT_CERTIFIED",
  ASSURANCE_REVIEW_REQUIRED: "ASSURANCE_REVIEW_REQUIRED",
});

export const DISAGREEMENT_CLASSES = Object.freeze({
  SUBJECT_FALSE_POSITIVE: "SUBJECT_FALSE_POSITIVE",
  SUBJECT_FALSE_NEGATIVE: "SUBJECT_FALSE_NEGATIVE",
  WRONG_ENTITY: "WRONG_ENTITY",
  WRONG_RANK: "WRONG_RANK",
  COMPETITOR_PARSE_ERROR: "COMPETITOR_PARSE_ERROR",
  ATTRIBUTE_PARSE_ERROR: "ATTRIBUTE_PARSE_ERROR",
  TERRITORY_MAPPING_ERROR: "TERRITORY_MAPPING_ERROR",
  PARSER_VERSION_DRIFT: "PARSER_VERSION_DRIFT",
  AMBIGUOUS: "AMBIGUOUS",
  OTHER: "OTHER",
});

export const LIVE_ASSURANCE_COHORT = Object.freeze([
  "adp_waterstone_boca_raton",
  "adp_renaissance_times_square",
  "adp_cambridge_beaches_bermuda",
  "adp_now_now_noho",
  "adp_hotel_phillips_kansas_city",
]);

export const ROUNDING_TOLERANCE_PP = 0.15;
