/** @typedef {import("../islands/island-build-types.js").IslandBuildSpec} IslandBuildSpec */

/** @type {IslandBuildSpec} */
export const BONAIRE_BUILD = {
  slug: "bonaire",
  country: "Bonaire",
  region: "Caribbean",
  sequence: 36,
  market: "Bonaire Countrywide",
  submarkets: ["Kralendijk", "Rincon", "Washington Slagbaai", "Other"],
  notes: "Kralendijk cruise and dive hub; Rincon heritage village; Washington Slagbaai national park; Lac Bay windsurf and salt flats eco-tourism.",
  tourismUrl: "https://www.tourismbonaire.com/",
  microPass: {
    names: [],
    rules: [{ base: ["https://www.tourismbonaire.com/", "https://www.tourismbonaire.com"], template: "https://www.tourismbonaire.com/explore/{key}" }],
  },
  audit: {
    keywords: ["bonaire", "kralendijk", "rincon", "flamingo airport", "lac bay", "washington slagbaai", "bonaire national marine park", "klein bonaire"],
    expectedPatterns: [
      { label: "Flamingo International Airport / BON", patterns: [/flamingo.*airport/i, /\bBON\b/i] },
      { label: "Kralendijk cruise port", patterns: [/kralendijk.*cruise/i, /harbour village/i] },
      { label: "Lac Bay windsurf", patterns: [/lac bay/i, /sorobon/i] },
      { label: "Washington Slagbaai National Park", patterns: [/washington slagbaai/i] },
      { label: "Rincon heritage village", patterns: [/rincon/i] },
    ],
  },
  candidates: [
    { name: "Flamingo International Airport Corridor", pointType: "Future Growth Node", city: "Kralendijk", submarket: "Kralendijk", latitude: 12.131, longitude: -68.2685, sourceReference: "https://bonaireinternationalairport.com/", manuallyVerified: true },
    { name: "Kralendijk Cruise Port — Harbour Village", pointType: "Mixed-Use Development", city: "Kralendijk", submarket: "Kralendijk", latitude: 12.1512, longitude: -68.2789, sourceReference: "https://www.tourismbonaire.com/", manuallyVerified: true },
    { name: "Kralendijk Waterfront and Wilhelmina Park", pointType: "Beach / Waterfront", city: "Kralendijk", submarket: "Kralendijk", latitude: 12.1534, longitude: -68.2767, sourceReference: "https://www.tourismbonaire.com/" },
    { name: "Kaya Grandi Shopping and Dining Strip", pointType: "Entertainment District", city: "Kralendijk", submarket: "Kralendijk", latitude: 12.1512, longitude: -68.2712, sourceReference: "https://www.tourismbonaire.com/" },
    { name: "Fort Oranje Historic Waterfront", pointType: "Tourist Attraction", city: "Kralendijk", submarket: "Kralendijk", latitude: 12.1523, longitude: -68.2734, sourceReference: "https://www.tourismbonaire.com/" },
    { name: "Bonaire National Marine Park Headquarters", pointType: "Tourist Attraction", city: "Kralendijk", submarket: "Kralendijk", latitude: 12.1489, longitude: -68.2812, sourceReference: "https://www.bonairenaturefoundation.org/" },
    { name: "Donkey Sanctuary Bonaire", pointType: "Tourist Attraction", city: "Kralendijk", submarket: "Kralendijk", latitude: 12.1712, longitude: -68.2512, sourceReference: "https://www.tourismbonaire.com/" },
    { name: "Hospital San Francisco", pointType: "Medical Campus", city: "Kralendijk", submarket: "Kralendijk", latitude: 12.1589, longitude: -68.2689, sourceReference: "https://www.bonairegov.com/" },
    { name: "Bonaire Convention and Events Center", pointType: "Convention Center", city: "Kralendijk", submarket: "Kralendijk", latitude: 12.1567, longitude: -68.2634, sourceReference: "https://www.tourismbonaire.com/" },
    { name: "Plaza Resort Bonaire", pointType: "Mixed-Use Development", city: "Kralendijk", submarket: "Kralendijk", latitude: 12.1612, longitude: -68.2912, sourceReference: "https://www.tourismbonaire.com/" },
    { name: "Delfins Beach Resort", pointType: "Beach / Waterfront", city: "Kralendijk", submarket: "Kralendijk", latitude: 12.1689, longitude: -68.3012, sourceReference: "https://www.tourismbonaire.com/" },
    { name: "Buddy Dive Resort and Pier", pointType: "Mixed-Use Development", city: "Kralendijk", submarket: "Kralendijk", latitude: 12.1634, longitude: -68.2889, sourceReference: "https://www.buddyresort.com/" },
    { name: "Klein Bonaire Uninhabited Island", pointType: "Tourist Attraction", city: "Kralendijk", submarket: "Kralendijk", latitude: 12.1589, longitude: -68.3012, sourceReference: "https://www.tourismbonaire.com/", manuallyVerified: true },
    { name: "Lac Bay Windsurf and Sorobon Beach", pointType: "Beach / Waterfront", city: "Sorobon", submarket: "Other", latitude: 12.1089, longitude: -68.2312, sourceReference: "https://www.tourismbonaire.com/", manuallyVerified: true },
    { name: "Cargill Salt Flats — Pink Salt Pans", pointType: "Tourist Attraction", city: "Kralendijk", submarket: "Other", latitude: 12.0789, longitude: -68.2512, sourceReference: "https://www.tourismbonaire.com/" },
    { name: "Willemstoren Lighthouse South Tip", pointType: "Tourist Attraction", city: "Kralendijk", submarket: "Other", latitude: 12.0289, longitude: -68.2512, sourceReference: "https://www.tourismbonaire.com/" },
    { name: "Rincon Heritage Village", pointType: "Tourist Attraction", city: "Rincon", submarket: "Rincon", latitude: 12.2312, longitude: -68.3312, sourceReference: "https://www.tourismbonaire.com/", manuallyVerified: true },
    { name: "Rincon Cadushy Distillery", pointType: "Tourist Attraction", city: "Rincon", submarket: "Rincon", latitude: 12.2334, longitude: -68.3289, sourceReference: "https://www.tourismbonaire.com/" },
    { name: "Rincon Valley Agricultural Heartland", pointType: "Tourist Attraction", city: "Rincon", submarket: "Rincon", latitude: 12.2412, longitude: -68.3189, sourceReference: "https://www.tourismbonaire.com/" },
    { name: "Gotomeer Flamingo Sanctuary", pointType: "Tourist Attraction", city: "Rincon", submarket: "Rincon", latitude: 12.2189, longitude: -68.3012, sourceReference: "https://www.tourismbonaire.com/" },
    { name: "Washington Slagbaai National Park Entrance", pointType: "Tourist Attraction", city: "Rincon", submarket: "Washington Slagbaai", latitude: 12.2512, longitude: -68.3512, sourceReference: "https://www.stinapa.org/", manuallyVerified: true },
    { name: "Slagbaai Bay Beach", pointType: "Beach / Waterfront", city: "Washington Slagbaai", submarket: "Washington Slagbaai", latitude: 12.2689, longitude: -68.3712, sourceReference: "https://www.stinapa.org/" },
    { name: "Boka Kokolishi Black Sand Beach", pointType: "Beach / Waterfront", city: "Washington Slagbaai", submarket: "Washington Slagbaai", latitude: 12.2812, longitude: -68.3612, sourceReference: "https://www.stinapa.org/" },
    { name: "Seru Largu Scenic Overlook", pointType: "Tourist Attraction", city: "Kralendijk", submarket: "Washington Slagbaai", latitude: 12.2012, longitude: -68.2912, sourceReference: "https://www.stinapa.org/" },
    { name: "1000 Steps Dive Site", pointType: "Tourist Attraction", city: "Kralendijk", submarket: "Other", latitude: 12.2189, longitude: -68.3112, sourceReference: "https://www.tourismbonaire.com/" },
    { name: "Karpata Dive and Snorkel Coast", pointType: "Beach / Waterfront", city: "Kralendijk", submarket: "Other", latitude: 12.2412, longitude: -68.3412, sourceReference: "https://www.tourismbonaire.com/" },
    { name: "Andrea I and II Dive Reef", pointType: "Tourist Attraction", city: "Kralendijk", submarket: "Other", latitude: 12.1712, longitude: -68.3012, sourceReference: "https://www.tourismbonaire.com/" },
    { name: "Eden Beach Resort Area", pointType: "Beach / Waterfront", city: "Kralendijk", submarket: "Kralendijk", latitude: 12.1789, longitude: -68.3089, sourceReference: "https://www.tourismbonaire.com/" },
    { name: "Sunset Beach Resort Coast", pointType: "Beach / Waterfront", city: "Kralendijk", submarket: "Kralendijk", latitude: 12.1812, longitude: -68.3112, sourceReference: "https://www.tourismbonaire.com/" },
    { name: "Captain Don's Habitat Dive Resort", pointType: "Mixed-Use Development", city: "Kralendijk", submarket: "Kralendijk", latitude: 12.1667, longitude: -68.2934, sourceReference: "https://www.tourismbonaire.com/" },
    { name: "Bonaire Free Zone Industrial Park", pointType: "Industrial / Logistics Zone", city: "Kralendijk", submarket: "Kralendijk", latitude: 12.1389, longitude: -68.2589, sourceReference: "https://www.bonairegov.com/" },
    { name: "Bonaire Economic Development Zone", pointType: "Future Growth Node", city: "Kralendijk", submarket: "Kralendijk", latitude: 12.1412, longitude: -68.2612, sourceReference: "https://www.bonairegov.com/" },
    { name: "Antriol Residential and Dive Lodge Corridor", pointType: "Mixed-Use Development", city: "Antriol", submarket: "Kralendijk", latitude: 12.1589, longitude: -68.2512, sourceReference: "https://www.tourismbonaire.com/" },
    { name: "Hato Agricultural and Cactus Country", pointType: "Tourist Attraction", city: "Hato", submarket: "Other", latitude: 12.1912, longitude: -68.2712, sourceReference: "https://www.tourismbonaire.com/" },
    { name: "Bonaire Aloe Factory", pointType: "Tourist Attraction", city: "Rincon", submarket: "Rincon", latitude: 12.2289, longitude: -68.3234, sourceReference: "https://www.tourismbonaire.com/" },
    { name: "Pos Mangel Retail and Dining Hub", pointType: "Entertainment District", city: "Kralendijk", submarket: "Kralendijk", latitude: 12.1534, longitude: -68.2689, sourceReference: "https://www.tourismbonaire.com/" },
    { name: "Bonaire Deep South Dive Coast", pointType: "Future Growth Node", city: "Kralendijk", submarket: "Other", latitude: 12.0489, longitude: -68.2612, sourceReference: "https://www.tourismbonaire.com/" },
    { name: "Tera Kora Hills Mountain Biking Zone", pointType: "Tourist Attraction", city: "Rincon", submarket: "Rincon", latitude: 12.2389, longitude: -68.3112, sourceReference: "https://www.tourismbonaire.com/" },
    { name: "Bonaire Mangrove Kayak Launch — Lac Cai", pointType: "Tourist Attraction", city: "Lac Cai", submarket: "Other", latitude: 12.1189, longitude: -68.2189, sourceReference: "https://www.tourismbonaire.com/" },
    { name: "Bonaire Cruise Tourism Growth Node", pointType: "Future Growth Node", city: "Kralendijk", submarket: "Kralendijk", latitude: 12.1501, longitude: -68.2778, sourceReference: "https://www.tourismbonaire.com/" },
  ],
  tiRecords: [
    { name: "Flamingo International Airport Access", pointType: "Highway Access", pointSubtype: "Airport Access", city: "Kralendijk", submarket: "Kralendijk", latitude: 12.131, longitude: -68.2685, sourceReference: "https://bonaireinternationalairport.com/", notes: "Primary international gateway for Bonaire dive and leisure demand." },
    { name: "Kralendijk Cruise Port Access", pointType: "Port / Maritime", pointSubtype: "Cruise Terminal", city: "Kralendijk", submarket: "Kralendijk", latitude: 12.1512, longitude: -68.2789, sourceReference: "https://www.tourismbonaire.com/", notes: "Main cruise pier supporting day-call and pre/post-stay lodging.", useCaseTags: ["Cruise / Port", "Resort / Leisure"] },
    { name: "Klein Bonaire Ferry Access", pointType: "Ferry Terminal", pointSubtype: "Water Taxi", city: "Kralendijk", submarket: "Kralendijk", latitude: 12.1589, longitude: -68.3012, sourceReference: "https://www.tourismbonaire.com/", notes: "Water taxi access to Klein Bonaire snorkel and beach demand." },
    { name: "Lac Bay Coastal Highway Access", pointType: "Highway Access", pointSubtype: "Scenic Corridor", city: "Sorobon", submarket: "Other", latitude: 12.1089, longitude: -68.2312, sourceReference: "https://www.tourismbonaire.com/", notes: "East coast road access to Lac Bay windsurf and mangrove tourism." },
    { name: "Rincon Village Highway Access", pointType: "Highway Access", pointSubtype: "Heritage Corridor", city: "Rincon", submarket: "Rincon", latitude: 12.2312, longitude: -68.3312, sourceReference: "https://www.tourismbonaire.com/", notes: "North road access to Rincon heritage and agricultural tourism." },
    { name: "Washington Slagbaai Park Road Access", pointType: "Highway Access", pointSubtype: "National Park Access", city: "Rincon", submarket: "Washington Slagbaai", latitude: 12.2512, longitude: -68.3512, sourceReference: "https://www.stinapa.org/", notes: "Park entrance road for northwest nature and dive tourism." },
    { name: "Kralendijk South Dive Coast Road Access", pointType: "Highway Access", pointSubtype: "Coastal Highway", city: "Kralendijk", submarket: "Other", latitude: 12.1712, longitude: -68.3012, sourceReference: "https://www.tourismbonaire.com/", notes: "South coast dive site road connector along Bonaire National Marine Park." },
    { name: "Bonaire Free Zone Port Access", pointType: "Port / Maritime", pointSubtype: "Commercial Port", city: "Kralendijk", submarket: "Kralendijk", latitude: 12.1389, longitude: -68.2589, sourceReference: "https://www.bonairegov.com/", notes: "Industrial port and free-zone logistics access.", useCaseTags: ["Industrial / Logistics"] },
  ],
  googleCorrections: {},
};
