/** @typedef {import("../islands/island-build-types.js").IslandBuildSpec} IslandBuildSpec */

/** @type {IslandBuildSpec} */
export const DOMINICAN_REPUBLIC_MATURE_BUILD = {
  slug: "dominican-republic-mature",
  country: "Dominican Republic",
  region: "Caribbean",
  buildType: "delta",
  sequence: 37,
  market: "Dominican Republic Mature Pass",
  submarkets: [
    "Punta Cana / Bávaro / Cap Cana",
    "Santo Domingo Metro",
    "Puerto Plata / Sosúa / Cabarete",
    "La Romana / Bayahibe",
    "Samaná / Las Terrenas",
    "Santiago / Cibao",
    "Miches / Costa Esmeralda",
    "Barahona / Pedernales",
    "Boca Chica / Juan Dolio",
    "Jarabacoa / Constanza",
    "Other",
  ],
  notes: "Mature gap-fill pass only — new demand anchors and TI records not present in first-pass or second-pass DR datasets.",
  tourismUrl: "https://www.godominicanrepublic.com/",
  microPass: {
    names: [],
    rules: [{ base: ["https://www.godominicanrepublic.com/", "https://www.godominicanrepublic.com"], template: "https://www.godominicanrepublic.com/places-to-visit/{key}" }],
  },
  audit: {
    keywords: ["dominican republic", "punta cana", "santo domingo", "santiago", "samana", "puerto plata", "la romana", "miches", "barahona", "jarabacoa"],
    expectedPatterns: [
      { label: "Hard Rock Punta Cana", patterns: [/hard rock.*punta cana/i] },
      { label: "Arena del Caribe", patterns: [/arena del caribe/i] },
      { label: "Parque Mirador del Este", patterns: [/mirador del este/i] },
      { label: "Centro León Santiago", patterns: [/centro le[oó]n/i] },
      { label: "Bahía de Samaná waterfront", patterns: [/bah[ií]a de saman[aá]/i] },
    ],
  },
  candidates: [
    { name: "Hard Rock Hotel & Casino Punta Cana", pointType: "Entertainment District", city: "Bávaro", submarket: "Punta Cana / Bávaro / Cap Cana", latitude: 18.6789, longitude: -68.4123, sourceReference: "https://www.hardrockhotelpuntacana.com/" },
    { name: "Arena del Caribe Convention Center", pointType: "Convention Center", city: "Punta Cana", submarket: "Punta Cana / Bávaro / Cap Cana", latitude: 18.5512, longitude: -68.3812, sourceReference: "https://www.arenadelcaribe.com/" },
    { name: "Macao Beach Surf and Eco Corridor", pointType: "Beach / Waterfront", city: "Macao", submarket: "Punta Cana / Bávaro / Cap Cana", latitude: 18.7612, longitude: -68.5312, sourceReference: "https://www.godominicanrepublic.com/" },
    { name: "Uvero Alto Beach Resort Growth Zone", pointType: "Future Growth Node", city: "Uvero Alto", submarket: "Punta Cana / Bávaro / Cap Cana", latitude: 18.8312, longitude: -68.6012, sourceReference: "https://www.godominicanrepublic.com/" },
    { name: "Verón Town Commercial Hub", pointType: "Business District", city: "Verón", submarket: "Punta Cana / Bávaro / Cap Cana", latitude: 18.5712, longitude: -68.3812, sourceReference: "https://www.godominicanrepublic.com/" },
    { name: "Galería 360 Shopping and Entertainment", pointType: "Entertainment District", city: "Santo Domingo", submarket: "Santo Domingo Metro", latitude: 18.4812, longitude: -69.9412, sourceReference: "https://www.galeria360.com/" },
    { name: "Parque Mirador del Este", pointType: "Tourist Attraction", city: "Santo Domingo", submarket: "Santo Domingo Metro", latitude: 18.4712, longitude: -69.8512, sourceReference: "https://www.godominicanrepublic.com/" },
    { name: "Faro a Colón — Columbus Lighthouse", pointType: "Tourist Attraction", city: "Santo Domingo", submarket: "Santo Domingo Metro", latitude: 18.4789, longitude: -69.8689, sourceReference: "https://www.godominicanrepublic.com/" },
    { name: "Zona Colonial — Conde Gate and Ramparts", pointType: "Tourist Attraction", city: "Santo Domingo", submarket: "Santo Domingo Metro", latitude: 18.4767, longitude: -69.8834, sourceReference: "https://www.godominicanrepublic.com/" },
    { name: "Gazcue Historic Residential District", pointType: "Tourist Attraction", city: "Santo Domingo", submarket: "Santo Domingo Metro", latitude: 18.4689, longitude: -69.9012, sourceReference: "https://www.godominicanrepublic.com/" },
    { name: "Bella Vista Corporate Corridor", pointType: "Business District", city: "Santo Domingo", submarket: "Santo Domingo Metro", latitude: 18.4612, longitude: -69.9312, sourceReference: "https://www.godominicanrepublic.com/" },
    { name: "Instituto Tecnológico de Santo Domingo (INTEC)", pointType: "University / College", city: "Santo Domingo", submarket: "Santo Domingo Metro", latitude: 18.4889, longitude: -69.9612, sourceReference: "https://www.intec.edu.do/" },
    { name: "Hospital General de la Plaza de la Cultura", pointType: "Medical Campus", city: "Santo Domingo", submarket: "Santo Domingo Metro", latitude: 18.4712, longitude: -69.9089, sourceReference: "https://www.godominicanrepublic.com/" },
    { name: "Palacio de los Deportes Virgilio Travieso Soto", pointType: "Sports Venue", city: "Santo Domingo", submarket: "Santo Domingo Metro", latitude: 18.4812, longitude: -69.9012, sourceReference: "https://www.godominicanrepublic.com/" },
    { name: "Playa Sosúa Beach and Snorkel Coast", pointType: "Beach / Waterfront", city: "Sosúa", submarket: "Puerto Plata / Sosúa / Cabarete", latitude: 19.7512, longitude: -70.5189, sourceReference: "https://www.godominicanrepublic.com/" },
    { name: "Malecón de Puerto Plata", pointType: "Beach / Waterfront", city: "Puerto Plata", submarket: "Puerto Plata / Sosúa / Cabarete", latitude: 19.8012, longitude: -70.6912, sourceReference: "https://www.godominicanrepublic.com/" },
    { name: "Teleférico Puerto Plata — Isabel de Torres", pointType: "Tourist Attraction", city: "Puerto Plata", submarket: "Puerto Plata / Sosúa / Cabarete", latitude: 19.7612, longitude: -70.7012, sourceReference: "https://www.telefericopuertoplata.com/" },
    { name: "27 Charcos de Damajagua Adventure Park", pointType: "Tourist Attraction", city: "Puerto Plata", submarket: "Puerto Plata / Sosúa / Cabarete", latitude: 19.6312, longitude: -70.8312, sourceReference: "https://www.godominicanrepublic.com/" },
    { name: "La Isabela Historic Settlement", pointType: "Tourist Attraction", city: "Puerto Plata", submarket: "Puerto Plata / Sosúa / Cabarete", latitude: 19.8912, longitude: -71.0812, sourceReference: "https://www.godominicanrepublic.com/" },
    { name: "Dominicus Beach — La Romana South", pointType: "Beach / Waterfront", city: "Dominicus", submarket: "La Romana / Bayahibe", latitude: 18.3612, longitude: -68.8012, sourceReference: "https://www.godominicanrepublic.com/" },
    { name: "Isla Catalina Day-Trip Marina", pointType: "Beach / Waterfront", city: "La Romana", submarket: "La Romana / Bayahibe", latitude: 18.3512, longitude: -68.8312, sourceReference: "https://www.godominicanrepublic.com/" },
    { name: "Teeth of the Dog Golf Course", pointType: "Sports Venue", city: "La Romana", submarket: "La Romana / Bayahibe", latitude: 18.4212, longitude: -68.9112, sourceReference: "https://www.casadecampo.com.do/" },
    { name: "Bahía de Samaná Waterfront Promenade", pointType: "Beach / Waterfront", city: "Samaná", submarket: "Samaná / Las Terrenas", latitude: 19.2067, longitude: -69.3356, sourceReference: "https://www.godominicanrepublic.com/" },
    { name: "Cayo Levantado Island Resort", pointType: "Mixed-Use Development", city: "Samaná", submarket: "Samaná / Las Terrenas", latitude: 19.1789, longitude: -69.3012, sourceReference: "https://www.godominicanrepublic.com/" },
    { name: "El Limón Waterfall Eco-Attraction", pointType: "Tourist Attraction", city: "Samaná", submarket: "Samaná / Las Terrenas", latitude: 19.3012, longitude: -69.4512, sourceReference: "https://www.godominicanrepublic.com/" },
    { name: "Pueblo de los Pescadores — Las Terrenas", pointType: "Entertainment District", city: "Las Terrenas", submarket: "Samaná / Las Terrenas", latitude: 19.3212, longitude: -69.5312, sourceReference: "https://www.godominicanrepublic.com/" },
    { name: "Centro León Cultural Center", pointType: "Convention Center", city: "Santiago", submarket: "Santiago / Cibao", latitude: 19.4512, longitude: -70.6912, sourceReference: "https://www.centroleon.org.do/" },
    { name: "Aeropuerto Internacional del Cibao Corridor", pointType: "Future Growth Node", city: "Santiago", submarket: "Santiago / Cibao", latitude: 19.4061, longitude: -70.6047, sourceReference: "https://www.aeropuertocibao.com.do/", manuallyVerified: true },
    { name: "Plaza Internacional Santiago Commercial Hub", pointType: "Business District", city: "Santiago", submarket: "Santiago / Cibao", latitude: 19.4489, longitude: -70.7089, sourceReference: "https://www.godominicanrepublic.com/" },
    { name: "Jarabacoa River Rafting and Adventure Hub", pointType: "Tourist Attraction", city: "Jarabacoa", submarket: "Jarabacoa / Constanza", latitude: 19.1212, longitude: -70.6412, sourceReference: "https://www.godominicanrepublic.com/" },
    { name: "Salto de Jimenoa Waterfall", pointType: "Tourist Attraction", city: "Jarabacoa", submarket: "Jarabacoa / Constanza", latitude: 19.1012, longitude: -70.6212, sourceReference: "https://www.godominicanrepublic.com/" },
    { name: "Pico Duarte Trailhead — La Ciénaga", pointType: "Tourist Attraction", city: "Jarabacoa", submarket: "Jarabacoa / Constanza", latitude: 18.9512, longitude: -70.8812, sourceReference: "https://www.godominicanrepublic.com/" },
    { name: "Four Points by Sheraton Puntacana Village", pointType: "Mixed-Use Development", city: "Punta Cana", submarket: "Punta Cana / Bávaro / Cap Cana", latitude: 18.5612, longitude: -68.3712, sourceReference: "https://www.marriott.com/" },
    { name: "Laguna Redonda and Laguna Limón Eco-Zone", pointType: "Tourist Attraction", city: "Miches", submarket: "Miches / Costa Esmeralda", latitude: 18.9612, longitude: -69.0712, sourceReference: "https://www.godominicanrepublic.com/" },
    { name: "Barahona City Waterfront and Marina", pointType: "Beach / Waterfront", city: "Barahona", submarket: "Barahona / Pedernales", latitude: 18.2089, longitude: -71.1012, sourceReference: "https://www.godominicanrepublic.com/" },
    { name: "Los Patos Beach — Barahona", pointType: "Beach / Waterfront", city: "Barahona", submarket: "Barahona / Pedernales", latitude: 18.1512, longitude: -71.1212, sourceReference: "https://www.godominicanrepublic.com/" },
    { name: "Pedernales Border Tourism Gateway", pointType: "Future Growth Node", city: "Pedernales", submarket: "Barahona / Pedernales", latitude: 18.0389, longitude: -71.7412, sourceReference: "https://www.godominicanrepublic.com/" },
    { name: "Andrés Boca Chica Beach Club Strip", pointType: "Entertainment District", city: "Boca Chica", submarket: "Boca Chica / Juan Dolio", latitude: 18.4512, longitude: -69.6112, sourceReference: "https://www.godominicanrepublic.com/" },
    { name: "Autopista Las Américas — SDQ Airport Corridor", pointType: "Future Growth Node", city: "Santo Domingo", submarket: "Boca Chica / Juan Dolio", latitude: 18.4312, longitude: -69.6712, sourceReference: "https://www.godominicanrepublic.com/", manuallyVerified: true },
    { name: "Higüey Basílica de la Altagracia", pointType: "Tourist Attraction", city: "Higüey", submarket: "Other", latitude: 18.615, longitude: -68.7089, sourceReference: "https://www.godominicanrepublic.com/" },
    { name: "San Pedro de Macorís Sugar Heritage City", pointType: "Tourist Attraction", city: "San Pedro de Macorís", submarket: "Other", latitude: 18.4512, longitude: -69.3012, sourceReference: "https://www.godominicanrepublic.com/" },
    { name: "La Romana International Airport Corridor", pointType: "Future Growth Node", city: "La Romana", submarket: "La Romana / Bayahibe", latitude: 18.4512, longitude: -68.9118, sourceReference: "https://www.godominicanrepublic.com/", manuallyVerified: true },
    { name: "Puerto Plata Gregorio Luperón Airport Corridor", pointType: "Future Growth Node", city: "Puerto Plata", submarket: "Puerto Plata / Sosúa / Cabarete", latitude: 19.7579, longitude: -70.5700, sourceReference: "https://www.godominicanrepublic.com/", manuallyVerified: true },
    { name: "Constanza Highland Vegetable Basket Tourism", pointType: "Tourist Attraction", city: "Constanza", submarket: "Jarabacoa / Constanza", latitude: 18.9089, longitude: -70.7412, sourceReference: "https://www.godominicanrepublic.com/" },
    { name: "Nagua North Coast Beach Gateway", pointType: "Beach / Waterfront", city: "Nagua", submarket: "Other", latitude: 19.3812, longitude: -69.8512, sourceReference: "https://www.godominicanrepublic.com/" },
  ],
  tiRecords: [
    { name: "Autopista del Este — Santo Domingo East Access", pointType: "Highway Access", pointSubtype: "National Highway", city: "Santo Domingo", submarket: "Santo Domingo Metro", latitude: 18.4712, longitude: -69.8612, sourceReference: "https://www.mop.gob.do/", notes: "East capital highway connector to airport and Boca Chica corridor." },
    { name: "Carretera Mella — Santiago North Access", pointType: "Highway Access", pointSubtype: "National Highway", city: "Santiago", submarket: "Santiago / Cibao", latitude: 19.4612, longitude: -70.6712, sourceReference: "https://www.mop.gob.do/", notes: "Primary Cibao north-south highway node for regional business travel." },
    { name: "Carretera Samaná — Las Terrenas Coastal Access", pointType: "Highway Access", pointSubtype: "Coastal Highway", city: "Las Terrenas", submarket: "Samaná / Las Terrenas", latitude: 19.3212, longitude: -69.5312, sourceReference: "https://www.godominicanrepublic.com/", notes: "Northeast peninsula coastal road for Samaná resort demand." },
    { name: "Las Américas International Airport Highway Access", pointType: "Highway Access", pointSubtype: "Airport Access", city: "Santo Domingo", submarket: "Santo Domingo Metro", latitude: 18.4297, longitude: -69.6689, sourceReference: "https://www.aerodom.com/", notes: "SDQ airport highway connector for capital and south-coast air-lift demand." },
    { name: "La Romana Highway 104 Resort Access", pointType: "Highway Access", pointSubtype: "Resort Corridor", city: "La Romana", submarket: "La Romana / Bayahibe", latitude: 18.4212, longitude: -68.9012, sourceReference: "https://www.mop.gob.do/", notes: "East-south resort highway access to Casa de Campo and Bayahibe corridor." },
    { name: "Puerto Plata — Sosúa Coastal Road Access", pointType: "Highway Access", pointSubtype: "Coastal Highway", city: "Sosúa", submarket: "Puerto Plata / Sosúa / Cabarete", latitude: 19.7512, longitude: -70.5189, sourceReference: "https://www.godominicanrepublic.com/", notes: "North coast scenic road linking Puerto Plata to Cabarete kite beach demand." },
    { name: "Miches Coastal Highway — Costa Esmeralda Access", pointType: "Highway Access", pointSubtype: "Emerging Resort Corridor", city: "Miches", submarket: "Miches / Costa Esmeralda", latitude: 18.9812, longitude: -69.0512, sourceReference: "https://www.godominicanrepublic.com/", notes: "New east-coast highway node for Miches/Costa Esmeralda resort growth." },
    { name: "Jarabacoa Mountain Highway Access", pointType: "Highway Access", pointSubtype: "Mountain Corridor", city: "Jarabacoa", submarket: "Jarabacoa / Constanza", latitude: 19.1212, longitude: -70.6412, sourceReference: "https://www.godominicanrepublic.com/", notes: "Central highland road access for adventure and eco-lodge hotel demand." },
    { name: "Barahona — Pedernales Southwest Highway Access", pointType: "Highway Access", pointSubtype: "Coastal Highway", city: "Barahona", submarket: "Barahona / Pedernales", latitude: 18.2089, longitude: -71.1012, sourceReference: "https://www.godominicanrepublic.com/", notes: "Southwest coastal highway for eco-tourism and Pedernales border demand." },
    { name: "Higüey — Punta Cana Inland Connector Access", pointType: "Highway Access", pointSubtype: "Resort Highway Corridor", city: "Higüey", submarket: "Punta Cana / Bávaro / Cap Cana", latitude: 18.615, longitude: -68.7089, sourceReference: "https://www.mop.gob.do/", notes: "Inland connector between Higüey and east-coast resort submarkets." },
  ],
  googleCorrections: {},
};
