/** @typedef {import("./market-build-types.js").MarketBuildSpec} MarketBuildSpec */

/** @type {MarketBuildSpec} */
export const GUADALAJARA_BUILD = {
  slug: "guadalajara",
  country: "Mexico",
  region: "North America",
  sequence: 4,
  market: "Guadalajara",
  submarkets: ["Centro", "Zapopan", "Tlaquepaque", "Expo / Andares", "Airport Corridor", "Other"],
  notes:
    "Jalisco urban hub: Centro histórico and Hospicio Cabañas UNESCO; Zapopan corporate/Andares; Tlaquepaque crafts tourism; Expo Guadalajara MICE; GDL airport corridor.",
  tourismUrl: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara",
  microPass: {
    names: [],
    rules: [
      {
        base: ["https://www.visitmexico.com/", "https://www.visitmexico.com"],
        template: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara/{key}",
      },
    ],
  },
  audit: {
    keywords: [
      "guadalajara",
      "gdl",
      "zapopan",
      "tlaquepaque",
      "expo guadalajara",
      "andares",
      "hospicio cabanas",
      "teatro degollado",
      "akron",
      "chapalita",
      "puerta de hierro",
    ],
    expectedPatterns: [
      { label: "Guadalajara International Airport / GDL", patterns: [/guadalajara international/i, /\bGDL\b/i, /miguel hidalgo/i] },
      { label: "Expo Guadalajara convention complex", patterns: [/expo guadalajara/i] },
      { label: "Hospicio Cabañas UNESCO", patterns: [/hospicio caba[nñ]as/i, /unesco/i] },
      { label: "Andares Zapopan corridor", patterns: [/andares/i, /zapopan/i] },
      { label: "Tlaquepaque crafts district", patterns: [/tlaquepaque/i] },
      { label: "Estadio Akron Chivas", patterns: [/akron/i, /chivas/i] },
    ],
  },
  candidates: [
    { name: "Guadalajara International Airport Corridor", pointType: "Future Growth Node", city: "Tlajomulco de Zúñiga", submarket: "Airport Corridor", latitude: 20.5218, longitude: -103.3112, sourceReference: "https://www.aeropuertogdl.com/", manuallyVerified: true },
    { name: "Hospicio Cabañas UNESCO World Heritage Site", pointType: "Tourist Attraction", city: "Guadalajara", submarket: "Centro", latitude: 20.677, longitude: -103.3478, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara", manuallyVerified: true },
    { name: "Teatro Degollado Historic Center", pointType: "Tourist Attraction", city: "Guadalajara", submarket: "Centro", latitude: 20.677, longitude: -103.3469, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara" },
    { name: "Guadalajara Cathedral and Plaza de Armas", pointType: "Tourist Attraction", city: "Guadalajara", submarket: "Centro", latitude: 20.6769, longitude: -103.3472, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara" },
    { name: "Instituto Cultural Cabañas", pointType: "Government / Civic Center", city: "Guadalajara", submarket: "Centro", latitude: 20.6765, longitude: -103.3481, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara" },
    { name: "Mercado San Juan de Dios", pointType: "Entertainment District", city: "Guadalajara", submarket: "Centro", latitude: 20.6734, longitude: -103.3412, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara" },
    { name: "Rotonda de los Jaliscienses Ilustres", pointType: "Tourist Attraction", city: "Guadalajara", submarket: "Centro", latitude: 20.6778, longitude: -103.3495, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara" },
    { name: "Templo Expiatorio del Santísimo Sacramento", pointType: "Tourist Attraction", city: "Guadalajara", submarket: "Centro", latitude: 20.6731, longitude: -103.3589, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara" },
    { name: "Palacio de Gobierno Jalisco", pointType: "Government / Civic Center", city: "Guadalajara", submarket: "Centro", latitude: 20.6767, longitude: -103.3465, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara" },
    { name: "Expo Guadalajara Convention Center", pointType: "Convention Center", city: "Guadalajara", submarket: "Expo / Andares", latitude: 20.6742, longitude: -103.3873, sourceReference: "https://www.expoguadalajara.com.mx/" },
    { name: "Andares Luxury Shopping District", pointType: "Entertainment District", city: "Zapopan", submarket: "Expo / Andares", latitude: 20.7097, longitude: -103.4112, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara" },
    { name: "Puerta de Hierro Corporate Corridor", pointType: "Business District", city: "Zapopan", submarket: "Expo / Andares", latitude: 20.7012, longitude: -103.4234, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara" },
    { name: "Zapopan Basilica and Plaza", pointType: "Tourist Attraction", city: "Zapopan", submarket: "Zapopan", latitude: 20.7212, longitude: -103.3912, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara" },
    { name: "Estadio Akron Chivas", pointType: "Sports Venue", city: "Zapopan", submarket: "Zapopan", latitude: 20.6819, longitude: -103.4622, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara" },
    { name: "Zapopan Art Museum MAZ", pointType: "Tourist Attraction", city: "Zapopan", submarket: "Zapopan", latitude: 20.7234, longitude: -103.3889, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara" },
    { name: "Zapopan Financial District", pointType: "Business District", city: "Zapopan", submarket: "Zapopan", latitude: 20.7156, longitude: -103.4012, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara" },
    { name: "Plaza Patria Zapopan", pointType: "Mixed-Use Development", city: "Zapopan", submarket: "Zapopan", latitude: 20.7189, longitude: -103.3945, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara" },
    { name: "Tlaquepaque Centro Artesanal", pointType: "Entertainment District", city: "San Pedro Tlaquepaque", submarket: "Tlaquepaque", latitude: 20.6403, longitude: -103.3114, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/tlaquepaque" },
    { name: "El Parián Tlaquepaque", pointType: "Entertainment District", city: "San Pedro Tlaquepaque", submarket: "Tlaquepaque", latitude: 20.6389, longitude: -103.3089, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/tlaquepaque" },
    { name: "Tlaquepaque Independent Gallery District", pointType: "Tourist Attraction", city: "San Pedro Tlaquepaque", submarket: "Tlaquepaque", latitude: 20.6412, longitude: -103.3123, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/tlaquepaque" },
    { name: "Tlaquepaque Casa Histórica Museum", pointType: "Tourist Attraction", city: "San Pedro Tlaquepaque", submarket: "Tlaquepaque", latitude: 20.6398, longitude: -103.3101, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/tlaquepaque" },
    { name: "Tlaquepaque Ceramics Workshop Corridor", pointType: "Tourist Attraction", city: "San Pedro Tlaquepaque", submarket: "Tlaquepaque", latitude: 20.6423, longitude: -103.3134, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/tlaquepaque" },
    { name: "GDL Airport Logistics and Industrial Park", pointType: "Industrial / Logistics Zone", city: "El Salto", submarket: "Airport Corridor", latitude: 20.5345, longitude: -103.2989, sourceReference: "https://www.aeropuertogdl.com/" },
    { name: "Aeropuerto Periférico Business Hotels Zone", pointType: "Business District", city: "Tlajomulco de Zúñiga", submarket: "Airport Corridor", latitude: 20.5189, longitude: -103.3045, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara" },
    { name: "Chapalita Residential and Dining Corridor", pointType: "Entertainment District", city: "Guadalajara", submarket: "Other", latitude: 20.6612, longitude: -103.3789, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara" },
    { name: "Tlaquepaque Río Santiago Park", pointType: "Entertainment District", city: "San Pedro Tlaquepaque", submarket: "Tlaquepaque", latitude: 20.6356, longitude: -103.3067, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/tlaquepaque" },
    { name: "ITESO University Campus", pointType: "University / College", city: "Tlaquepaque", submarket: "Tlaquepaque", latitude: 20.6289, longitude: -103.3234, sourceReference: "https://www.iteso.mx/" },
    { name: "Hospital Ángeles del Carmen", pointType: "Medical Campus", city: "Guadalajara", submarket: "Centro", latitude: 20.6689, longitude: -103.3512, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara" },
    { name: "Hospital Civil de Guadalajara", pointType: "Medical Campus", city: "Guadalajara", submarket: "Centro", latitude: 20.6812, longitude: -103.3623, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara" },
    { name: "Universidad de Guadalajara CUCEA", pointType: "University / College", city: "Zapopan", submarket: "Zapopan", latitude: 20.7345, longitude: -103.3789, sourceReference: "https://www.udg.mx/" },
    { name: "Museo de las Artes Universidad de Guadalajara", pointType: "Tourist Attraction", city: "Guadalajara", submarket: "Centro", latitude: 20.6745, longitude: -103.3612, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara" },
    { name: "Plaza del Sol Shopping Center", pointType: "Entertainment District", city: "Zapopan", submarket: "Zapopan", latitude: 20.6512, longitude: -103.4012, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara" },
    { name: "Galerías Guadalajara Mall", pointType: "Entertainment District", city: "Zapopan", submarket: "Zapopan", latitude: 20.6789, longitude: -103.4123, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara" },
    { name: "La Minerva Roundabout Landmark", pointType: "Tourist Attraction", city: "Guadalajara", submarket: "Centro", latitude: 20.6738, longitude: -103.3512, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara" },
    { name: "Chapultepec Avenue Entertainment Corridor", pointType: "Entertainment District", city: "Guadalajara", submarket: "Centro", latitude: 20.6712, longitude: -103.3678, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara" },
    { name: "Zoológico Guadalajara", pointType: "Tourist Attraction", city: "Guadalajara", submarket: "Other", latitude: 20.6456, longitude: -103.4234, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara" },
    { name: "Tonalá Crafts Market District", pointType: "Tourist Attraction", city: "Tonalá", submarket: "Other", latitude: 20.6234, longitude: -103.2345, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/tonala" },
    { name: "Tequila Pueblo Mágico Day-Trip Gateway", pointType: "Tourist Attraction", city: "Tequila", submarket: "Other", latitude: 20.8812, longitude: -103.8345, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/tequila" },
    { name: "Lago de Chapala Tourism Corridor", pointType: "Beach / Waterfront", city: "Chapala", submarket: "Other", latitude: 20.2912, longitude: -103.1912, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/chapala" },
    { name: "Zapopan Nuevo Periférico Office Corridor", pointType: "Business District", city: "Zapopan", submarket: "Zapopan", latitude: 20.7089, longitude: -103.4345, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara" },
    { name: "Expo Guadalajara Hotel Zone", pointType: "Mixed-Use Development", city: "Guadalajara", submarket: "Expo / Andares", latitude: 20.6723, longitude: -103.3845, sourceReference: "https://www.expoguadalajara.com.mx/" },
    { name: "World Trade Center Guadalajara", pointType: "Convention Center", city: "Zapopan", submarket: "Expo / Andares", latitude: 20.6989, longitude: -103.4189, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara" },
    { name: "Centro Médico Puerta de Hierro", pointType: "Medical Campus", city: "Zapopan", submarket: "Expo / Andares", latitude: 20.7045, longitude: -103.4267, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara" },
    { name: "Parque Metropolitano Zapopan", pointType: "Mixed-Use Development", city: "Zapopan", submarket: "Zapopan", latitude: 20.7267, longitude: -103.4012, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara" },
    { name: "Guadalajara Light Rail Macroplaza Station", pointType: "Future Growth Node", city: "Guadalajara", submarket: "Centro", latitude: 20.6762, longitude: -103.3456, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara" },
    { name: "Tlaquepaque Río Verde Cultural Park", pointType: "Tourist Attraction", city: "San Pedro Tlaquepaque", submarket: "Tlaquepaque", latitude: 20.6378, longitude: -103.3078, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/tlaquepaque" },
    { name: "GDL Airport Cargo Terminal Zone", pointType: "Industrial / Logistics Zone", city: "Tlajomulco de Zúñiga", submarket: "Airport Corridor", latitude: 20.5245, longitude: -103.3189, sourceReference: "https://www.aeropuertogdl.com/" },
    { name: "Providencia Dining and Retail Corridor", pointType: "Entertainment District", city: "Guadalajara", submarket: "Centro", latitude: 20.6912, longitude: -103.3789, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara" },
    { name: "Zapopan Arcos Vallarta Gateway", pointType: "Business District", city: "Zapopan", submarket: "Zapopan", latitude: 20.6845, longitude: -103.3912, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara" },
    { name: "Expo Guadalajara Future Expansion Node", pointType: "Future Growth Node", city: "Guadalajara", submarket: "Expo / Andares", latitude: 20.6756, longitude: -103.3898, sourceReference: "https://www.expoguadalajara.com.mx/" },
    { name: "Tlaquepaque Museo del Premio Nacional de la Cerámica", pointType: "Tourist Attraction", city: "San Pedro Tlaquepaque", submarket: "Tlaquepaque", latitude: 20.6401, longitude: -103.3118, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/tlaquepaque" },
    { name: "Centro Histórico Guadalajara Hotel Conversion Zone", pointType: "Future Growth Node", city: "Guadalajara", submarket: "Centro", latitude: 20.6756, longitude: -103.3489, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara" },
  ],
  tiRecords: [
    { name: "Guadalajara International Airport Access", pointType: "Highway Access", pointSubtype: "Airport Access", city: "Tlajomulco de Zúñiga", submarket: "Airport Corridor", latitude: 20.5218, longitude: -103.3112, sourceReference: "https://www.aeropuertogdl.com/", notes: "Primary international gateway for Guadalajara corporate and MICE demand." },
    { name: "Expo Guadalajara Convention Access", pointType: "Highway Access", pointSubtype: "Convention Access", city: "Guadalajara", submarket: "Expo / Andares", latitude: 20.6742, longitude: -103.3873, sourceReference: "https://www.expoguadalajara.com.mx/", notes: "Convention center highway access for group and event compression." },
    { name: "Centro Histórico Transit Access", pointType: "Highway Access", pointSubtype: "Historic Core", city: "Guadalajara", submarket: "Centro", latitude: 20.6769, longitude: -103.3472, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara", notes: "Historic center access for cultural tourism and urban hotel demand." },
    { name: "Andares Puerta de Hierro Corridor Access", pointType: "Highway Access", pointSubtype: "Business District", city: "Zapopan", submarket: "Expo / Andares", latitude: 20.7097, longitude: -103.4112, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara", notes: "Zapopan luxury retail and corporate corridor access." },
    { name: "Tlaquepaque Crafts District Access", pointType: "Highway Access", pointSubtype: "Tourism Corridor", city: "San Pedro Tlaquepaque", submarket: "Tlaquepaque", latitude: 20.6403, longitude: -103.3114, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/tlaquepaque", notes: "Crafts and dining tourism access south of Guadalajara centro." },
    { name: "Estadio Akron Event Access", pointType: "Highway Access", pointSubtype: "Sports Venue", city: "Zapopan", submarket: "Zapopan", latitude: 20.6819, longitude: -103.4622, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara", notes: "Sports and concert event compression access in western Zapopan." },
    { name: "Periférico Sur Ring Road Access", pointType: "Highway Access", pointSubtype: "Urban Artery", city: "Guadalajara", submarket: "Other", latitude: 20.6512, longitude: -103.3912, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/guadalajara", notes: "Periférico ring road linking airport, Expo, and Zapopan submarkets." },
    { name: "Tequila Ruta Tourism Highway Access", pointType: "Highway Access", pointSubtype: "Tourism Corridor", city: "Tequila", submarket: "Other", latitude: 20.8812, longitude: -103.8345, sourceReference: "https://www.visitmexico.com/en/main-destinations/jalisco/tequila", notes: "Day-trip agri-tourism corridor from Guadalajara hotel base." },
  ],
  googleCorrections: {},
};
