/** @typedef {import("../islands/island-build-types.js").IslandBuildSpec} IslandBuildSpec */

/** @type {IslandBuildSpec} */
export const HAITI_BUILD = {
  slug: "haiti",
  country: "Haiti",
  region: "Caribbean",
  sequence: 32,
  market: "Haiti Countrywide",
  submarkets: ["Port-au-Prince", "Cap-Haïtien", "Jacmel", "Other"],
  notes: "Port-au-Prince civic and business hub; Cap-Haïtien north heritage and cruise; Jacmel arts coast; Labadie and Citadelle leisure nodes.",
  tourismUrl: "https://www.haiti.org/",
  microPass: {
    names: [],
    rules: [{ base: ["https://www.haiti.org/", "https://www.haiti.org"], template: "https://www.haiti.org/destination/{key}" }],
  },
  audit: {
    keywords: ["haiti", "port-au-prince", "cap-haitien", "jacmel", "labadie", "citadelle", "petion-ville", "pap", "cap"],
    expectedPatterns: [
      { label: "Toussaint Louverture International Airport / PAP", patterns: [/toussaint louverture/i, /\bPAP\b/i] },
      { label: "Cap-Haïtien International Airport / CAP", patterns: [/cap.ha[iï]tien.*airport/i, /\bCAP\b/i] },
      { label: "Citadelle Laferrière", patterns: [/citadelle/i, /laferri[eè]re/i] },
      { label: "Jacmel historic district", patterns: [/jacmel/i] },
      { label: "Labadie cruise destination", patterns: [/labadie/i] },
    ],
  },
  candidates: [
    { name: "Toussaint Louverture International Airport Corridor", pointType: "Future Growth Node", city: "Port-au-Prince", submarket: "Port-au-Prince", latitude: 18.5801, longitude: -72.2925, sourceReference: "https://www.ofnac.gouv.ht/", manuallyVerified: true },
    { name: "Port of Port-au-Prince", pointType: "Mixed-Use Development", city: "Port-au-Prince", submarket: "Port-au-Prince", latitude: 18.5412, longitude: -72.3389, sourceReference: "https://www.haiti.org/", manuallyVerified: true },
    { name: "Champ de Mars Civic Plaza", pointType: "Government / Civic Center", city: "Port-au-Prince", submarket: "Port-au-Prince", latitude: 18.5434, longitude: -72.3378, sourceReference: "https://www.haiti.org/" },
    { name: "Iron Market Marché en Fer", pointType: "Entertainment District", city: "Port-au-Prince", submarket: "Port-au-Prince", latitude: 18.5445, longitude: -72.3356, sourceReference: "https://www.haiti.org/" },
    { name: "Pétion-Ville Business and Dining Corridor", pointType: "Business District", city: "Pétion-Ville", submarket: "Port-au-Prince", latitude: 18.5123, longitude: -72.2845, sourceReference: "https://www.haiti.org/" },
    { name: "Karibe Convention Center", pointType: "Convention Center", city: "Pétion-Ville", submarket: "Port-au-Prince", latitude: 18.5089, longitude: -72.2812, sourceReference: "https://www.karibehotel.com/" },
    { name: "Université Quisqueya Campus", pointType: "University / College", city: "Port-au-Prince", submarket: "Port-au-Prince", latitude: 18.5234, longitude: -72.2912, sourceReference: "https://www.uniq.edu.ht/" },
    { name: "Université d'État d'Haïti", pointType: "University / College", city: "Port-au-Prince", submarket: "Port-au-Prince", latitude: 18.5389, longitude: -72.3345, sourceReference: "https://www.ueh.edu.ht/" },
    { name: "Hôpital Universitaire de la Paix", pointType: "Medical Campus", city: "Port-au-Prince", submarket: "Port-au-Prince", latitude: 18.5312, longitude: -72.3012, sourceReference: "https://www.haiti.org/" },
    { name: "Stade Sylvio Cator", pointType: "Sports Venue", city: "Port-au-Prince", submarket: "Port-au-Prince", latitude: 18.5456, longitude: -72.3289, sourceReference: "https://www.haiti.org/" },
    { name: "Musée du Panthéon National Haïtien", pointType: "Tourist Attraction", city: "Port-au-Prince", submarket: "Port-au-Prince", latitude: 18.5467, longitude: -72.3367, sourceReference: "https://www.haiti.org/" },
    { name: "Tabarre Industrial and Logistics Zone", pointType: "Industrial / Logistics Zone", city: "Tabarre", submarket: "Port-au-Prince", latitude: 18.5712, longitude: -72.2678, sourceReference: "https://www.haiti.org/" },
    { name: "Kenscoff Mountain Retreat Corridor", pointType: "Tourist Attraction", city: "Kenscoff", submarket: "Port-au-Prince", latitude: 18.4512, longitude: -72.1989, sourceReference: "https://www.haiti.org/" },
    { name: "Cap-Haïtien International Airport Corridor", pointType: "Future Growth Node", city: "Cap-Haïtien", submarket: "Cap-Haïtien", latitude: 19.7581, longitude: -72.1944, sourceReference: "https://www.haiti.org/", manuallyVerified: true },
    { name: "Citadelle Laferrière UNESCO Site", pointType: "Tourist Attraction", city: "Milot", submarket: "Cap-Haïtien", latitude: 19.5734, longitude: -72.2445, sourceReference: "https://whc.unesco.org/en/list/180", manuallyVerified: true },
    { name: "Sans-Souci Palace Ruins", pointType: "Tourist Attraction", city: "Milot", submarket: "Cap-Haïtien", latitude: 19.6012, longitude: -72.2189, sourceReference: "https://whc.unesco.org/en/list/180" },
    { name: "Cap-Haïtien Historic Waterfront", pointType: "Beach / Waterfront", city: "Cap-Haïtien", submarket: "Cap-Haïtien", latitude: 19.7589, longitude: -72.2012, sourceReference: "https://www.haiti.org/" },
    { name: "Labadee Royal Caribbean Destination", pointType: "Beach / Waterfront", city: "Labadee", submarket: "Cap-Haïtien", latitude: 19.7867, longitude: -72.2456, sourceReference: "https://www.royalcaribbean.com/", manuallyVerified: true },
    { name: "Bassin Bleu Waterfall Attraction", pointType: "Tourist Attraction", city: "Jacmel", submarket: "Cap-Haïtien", latitude: 18.3234, longitude: -72.4123, sourceReference: "https://www.haiti.org/" },
    { name: "Cap-Haïtien Cathedral and Central Square", pointType: "Government / Civic Center", city: "Cap-Haïtien", submarket: "Cap-Haïtien", latitude: 19.7598, longitude: -72.2034, sourceReference: "https://www.haiti.org/" },
    { name: "Fort Picolet Historic Site", pointType: "Tourist Attraction", city: "Cap-Haïtien", submarket: "Cap-Haïtien", latitude: 19.7712, longitude: -72.1912, sourceReference: "https://www.haiti.org/" },
    { name: "Jacmel Historic Colonial District", pointType: "Tourist Attraction", city: "Jacmel", submarket: "Jacmel", latitude: 18.2345, longitude: -72.5356, sourceReference: "https://www.haiti.org/", manuallyVerified: true },
    { name: "Jacmel Carnival Arts Corridor", pointType: "Entertainment District", city: "Jacmel", submarket: "Jacmel", latitude: 18.2367, longitude: -72.5334, sourceReference: "https://www.haiti.org/" },
    { name: "Jacmel Beach Waterfront", pointType: "Beach / Waterfront", city: "Jacmel", submarket: "Jacmel", latitude: 18.2289, longitude: -72.5412, sourceReference: "https://www.haiti.org/" },
    { name: "Bassin Bleu Jacmel Eco-Attraction", pointType: "Tourist Attraction", city: "Jacmel", submarket: "Jacmel", latitude: 18.2512, longitude: -72.5234, sourceReference: "https://www.haiti.org/" },
    { name: "Cyvadier Beach Resort Zone", pointType: "Beach / Waterfront", city: "Jacmel", submarket: "Jacmel", latitude: 18.2189, longitude: -72.5489, sourceReference: "https://www.haiti.org/" },
    { name: "Port-de-Paix North Coast Gateway", pointType: "Future Growth Node", city: "Port-de-Paix", submarket: "Other", latitude: 19.9389, longitude: -72.8312, sourceReference: "https://www.haiti.org/" },
    { name: "Les Cayes South Coast Hub", pointType: "Business District", city: "Les Cayes", submarket: "Other", latitude: 18.1934, longitude: -73.7456, sourceReference: "https://www.haiti.org/" },
    { name: "Port-Salut Beach Tourism Corridor", pointType: "Beach / Waterfront", city: "Port-Salut", submarket: "Other", latitude: 18.0789, longitude: -73.9234, sourceReference: "https://www.haiti.org/" },
    { name: "Île-à-Vache Island Resort Destination", pointType: "Mixed-Use Development", city: "Île-à-Vache", submarket: "Other", latitude: 18.0712, longitude: -73.6912, sourceReference: "https://www.haiti.org/" },
    { name: "Gonaïves Independence Heritage City", pointType: "Tourist Attraction", city: "Gonaïves", submarket: "Other", latitude: 19.4512, longitude: -72.6889, sourceReference: "https://www.haiti.org/" },
    { name: "Jérémie South Peninsula Gateway", pointType: "Future Growth Node", city: "Jérémie", submarket: "Other", latitude: 18.6512, longitude: -74.1234, sourceReference: "https://www.haiti.org/" },
    { name: "Côte des Arcadins Resort Coast", pointType: "Beach / Waterfront", city: "Montrouis", submarket: "Other", latitude: 19.1012, longitude: -72.7012, sourceReference: "https://www.haiti.org/" },
    { name: "Wahoo Bay Beach Resort Area", pointType: "Beach / Waterfront", city: "Côtes-de-Fer", submarket: "Other", latitude: 18.1912, longitude: -72.5234, sourceReference: "https://www.haiti.org/" },
    { name: "Saut-d'Eau Pilgrimage and Tourism Site", pointType: "Tourist Attraction", city: "Saut-d'Eau", submarket: "Other", latitude: 18.8234, longitude: -72.2189, sourceReference: "https://www.haiti.org/" },
    { name: "Fort Jacques Mountain Heritage Site", pointType: "Tourist Attraction", city: "Kenscoff", submarket: "Other", latitude: 18.4389, longitude: -72.2123, sourceReference: "https://www.haiti.org/" },
    { name: "Ouanaminthe Border Commerce Zone", pointType: "Industrial / Logistics Zone", city: "Ouanaminthe", submarket: "Other", latitude: 19.5489, longitude: -71.7234, sourceReference: "https://www.haiti.org/" },
    { name: "Hinche Central Plateau Hub", pointType: "Business District", city: "Hinche", submarket: "Other", latitude: 19.1512, longitude: -72.0167, sourceReference: "https://www.haiti.org/" },
    { name: "Port-au-Prince Convention and NGO District", pointType: "Convention Center", city: "Port-au-Prince", submarket: "Port-au-Prince", latitude: 18.5189, longitude: -72.2889, sourceReference: "https://www.haiti.org/" },
    { name: "Tortuga Island Heritage Access", pointType: "Tourist Attraction", city: "Île de la Tortue", submarket: "Other", latitude: 20.0289, longitude: -72.7912, sourceReference: "https://www.haiti.org/" },
  ],
  tiRecords: [
    { name: "Toussaint Louverture International Airport Access", pointType: "Highway Access", pointSubtype: "Airport Access", city: "Port-au-Prince", submarket: "Port-au-Prince", latitude: 18.5801, longitude: -72.2925, sourceReference: "https://www.ofnac.gouv.ht/", notes: "Primary international gateway for Port-au-Prince metro demand." },
    { name: "Port of Port-au-Prince Access", pointType: "Port / Maritime", pointSubtype: "Commercial Port", city: "Port-au-Prince", submarket: "Port-au-Prince", latitude: 18.5412, longitude: -72.3389, sourceReference: "https://www.haiti.org/", notes: "Main cargo and ferry port for capital logistics and maritime demand.", useCaseTags: ["Industrial / Logistics", "Cruise / Port"] },
    { name: "Cap-Haïtien International Airport Access", pointType: "Highway Access", pointSubtype: "Airport Access", city: "Cap-Haïtien", submarket: "Cap-Haïtien", latitude: 19.7581, longitude: -72.1944, sourceReference: "https://www.haiti.org/", notes: "North Haiti air gateway for heritage and Labadie cruise demand." },
    { name: "Labadee Cruise Destination Access", pointType: "Port / Maritime", pointSubtype: "Cruise Terminal", city: "Labadee", submarket: "Cap-Haïtien", latitude: 19.7867, longitude: -72.2456, sourceReference: "https://www.royalcaribbean.com/", notes: "Private cruise destination supporting north-coast day-call demand.", useCaseTags: ["Cruise / Port", "Resort / Leisure"] },
    { name: "Citadelle Laferrière Scenic Highway Access", pointType: "Highway Access", pointSubtype: "Scenic Corridor", city: "Milot", submarket: "Cap-Haïtien", latitude: 19.5734, longitude: -72.2445, sourceReference: "https://whc.unesco.org/en/list/180", notes: "Mountain road access to Citadelle UNESCO heritage tourism." },
    { name: "Jacmel Coastal Highway Access", pointType: "Highway Access", pointSubtype: "Coastal Highway", city: "Jacmel", submarket: "Jacmel", latitude: 18.2345, longitude: -72.5356, sourceReference: "https://www.haiti.org/", notes: "South coast road connector for Jacmel arts and beach tourism." },
    { name: "Route Nationale 1 Cap-Haïtien Corridor Access", pointType: "Highway Access", pointSubtype: "National Highway", city: "Cap-Haïtien", submarket: "Cap-Haïtien", latitude: 19.7612, longitude: -72.2089, sourceReference: "https://www.haiti.org/", notes: "Primary north highway linking Cap-Haïtien to Port-au-Prince corridor." },
    { name: "Ouanaminthe Border Crossing Access", pointType: "Highway Access", pointSubtype: "Border Crossing", city: "Ouanaminthe", submarket: "Other", latitude: 19.5489, longitude: -71.7234, sourceReference: "https://www.haiti.org/", notes: "Dominican border commerce connector for cross-border transient demand.", useCaseTags: ["Industrial / Logistics"] },
  ],
  googleCorrections: {},
};
