/** @typedef {import("../islands/island-build-types.js").IslandBuildSpec} IslandBuildSpec */

/** @type {IslandBuildSpec} */
export const MARTINIQUE_BUILD = {
  slug: "martinique",
  country: "Martinique",
  region: "Caribbean",
  sequence: 34,
  market: "Martinique Countrywide",
  submarkets: ["Fort-de-France", "South Coast", "North Atlantic", "Other"],
  notes: "Fort-de-France civic and cruise hub; south resort coast (Les Trois-Îlets, Diamant); north Atlantic surf and rum heritage; Mount Pelée volcano corridor.",
  tourismUrl: "https://www.martinique.org/en",
  microPass: {
    names: [],
    rules: [{ base: ["https://www.martinique.org/", "https://www.martinique.org/en"], template: "https://www.martinique.org/en/discover/{key}" }],
  },
  audit: {
    keywords: ["martinique", "fort-de-france", "trois-ilets", "saint-pierre", "diamant", "les anses d'arlet", "aimé césaire", "schoelcher"],
    expectedPatterns: [
      { label: "Martinique Aimé Césaire International Airport / FDF", patterns: [/aim[eé] c[eé]saire/i, /\bFDF\b/i] },
      { label: "Fort-de-France cruise port", patterns: [/fort.de.france.*cruise/i, /pointe simon/i] },
      { label: "Saint-Pierre volcano heritage", patterns: [/saint.pierre/i, /montagne pel[eé]e/i] },
      { label: "Les Trois-Îlets resort coast", patterns: [/trois.îlets/i, /trois ilets/i] },
      { label: "La Savane park Fort-de-France", patterns: [/la savane/i] },
    ],
  },
  candidates: [
    { name: "Martinique Aimé Césaire International Airport Corridor", pointType: "Future Growth Node", city: "Le Lamentin", submarket: "Fort-de-France", latitude: 14.591, longitude: -61.0032, sourceReference: "https://www.martinique.aeroport.fr/", manuallyVerified: true },
    { name: "Fort-de-France Cruise Port — Pointe Simon", pointType: "Mixed-Use Development", city: "Fort-de-France", submarket: "Fort-de-France", latitude: 14.6012, longitude: -61.0712, sourceReference: "https://www.martinique.org/en", manuallyVerified: true },
    { name: "La Savane Park and Schoelcher Library", pointType: "Tourist Attraction", city: "Fort-de-France", submarket: "Fort-de-France", latitude: 14.6034, longitude: -61.0734, sourceReference: "https://www.martinique.org/en" },
    { name: "Fort Saint-Louis Historic Waterfront", pointType: "Tourist Attraction", city: "Fort-de-France", submarket: "Fort-de-France", latitude: 14.5989, longitude: -61.0689, sourceReference: "https://www.martinique.org/en" },
    { name: "Fort-de-France Central Business District", pointType: "Business District", city: "Fort-de-France", submarket: "Fort-de-France", latitude: 14.6045, longitude: -61.0756, sourceReference: "https://www.martinique.org/en" },
    { name: "Centre Hospitalier Universitaire de Martinique", pointType: "Medical Campus", city: "Fort-de-France", submarket: "Fort-de-France", latitude: 14.6123, longitude: -61.0812, sourceReference: "https://www.chu-martinique.fr/" },
    { name: "Université des Antilles — Martinique Campus", pointType: "University / College", city: "Schoelcher", submarket: "Fort-de-France", latitude: 14.6189, longitude: -61.0912, sourceReference: "https://www.univ-antilles.fr/" },
    { name: "Stade Pierre-Aliker", pointType: "Sports Venue", city: "Fort-de-France", submarket: "Fort-de-France", latitude: 14.6234, longitude: -61.0534, sourceReference: "https://www.martinique.org/en" },
    { name: "Palais Régional Government Precinct", pointType: "Government / Civic Center", city: "Fort-de-France", submarket: "Fort-de-France", latitude: 14.6067, longitude: -61.0789, sourceReference: "https://www.martinique.org/en" },
    { name: "Balata Botanical Garden", pointType: "Tourist Attraction", city: "Fort-de-France", submarket: "Fort-de-France", latitude: 14.6712, longitude: -61.0234, sourceReference: "https://www.martinique.org/en" },
    { name: "Les Trois-Îlets Resort Coast", pointType: "Beach / Waterfront", city: "Les Trois-Îlets", submarket: "South Coast", latitude: 14.5389, longitude: -61.0389, sourceReference: "https://www.martinique.org/en", manuallyVerified: true },
    { name: "La Pagerie — Empress Joséphine Museum", pointType: "Tourist Attraction", city: "Les Trois-Îlets", submarket: "South Coast", latitude: 14.5412, longitude: -61.0412, sourceReference: "https://www.martinique.org/en" },
    { name: "Pointe du Bout Marina and Beach", pointType: "Beach / Waterfront", city: "Les Trois-Îlets", submarket: "South Coast", latitude: 14.5312, longitude: -61.0512, sourceReference: "https://www.martinique.org/en" },
    { name: "Anse Mitan Beach Resort Strip", pointType: "Beach / Waterfront", city: "Les Trois-Îlets", submarket: "South Coast", latitude: 14.5289, longitude: -61.0534, sourceReference: "https://www.martinique.org/en" },
    { name: "Anse à l'Âne Beach", pointType: "Beach / Waterfront", city: "Les Trois-Îlets", submarket: "South Coast", latitude: 14.5234, longitude: -61.0489, sourceReference: "https://www.martinique.org/en" },
    { name: "Le Diamant Beach and Rocher du Diamant", pointType: "Tourist Attraction", city: "Le Diamant", submarket: "South Coast", latitude: 14.4789, longitude: -61.0289, sourceReference: "https://www.martinique.org/en" },
    { name: "Les Anses-d'Arlet Fishing Village", pointType: "Tourist Attraction", city: "Les Anses-d'Arlet", submarket: "South Coast", latitude: 14.4912, longitude: -61.0812, sourceReference: "https://www.martinique.org/en" },
    { name: "Saint-Anne Beach — Grande Anse des Salines", pointType: "Beach / Waterfront", city: "Saint-Anne", submarket: "South Coast", latitude: 14.4389, longitude: -60.8812, sourceReference: "https://www.martinique.org/en" },
    { name: "Club Med Les Boucaniers", pointType: "Mixed-Use Development", city: "Sainte-Anne", submarket: "South Coast", latitude: 14.4312, longitude: -60.8934, sourceReference: "https://www.clubmed.com/" },
    { name: "Cap 110 Memorial Sculpture Park", pointType: "Tourist Attraction", city: "Le Diamant", submarket: "South Coast", latitude: 14.4612, longitude: -61.0389, sourceReference: "https://www.martinique.org/en" },
    { name: "Saint-Pierre Volcano Heritage Town", pointType: "Tourist Attraction", city: "Saint-Pierre", submarket: "North Atlantic", latitude: 14.7412, longitude: -61.1756, sourceReference: "https://www.martinique.org/en", manuallyVerified: true },
    { name: "Montagne Pelée Volcano Trailhead", pointType: "Tourist Attraction", city: "Saint-Pierre", submarket: "North Atlantic", latitude: 14.8089, longitude: -61.1667, sourceReference: "https://www.martinique.org/en" },
    { name: "Depaz Distillery Heritage Site", pointType: "Tourist Attraction", city: "Saint-Pierre", submarket: "North Atlantic", latitude: 14.7389, longitude: -61.1512, sourceReference: "https://www.martinique.org/en" },
    { name: "Le Carbet Beach and Yoles Village", pointType: "Beach / Waterfront", city: "Le Carbet", submarket: "North Atlantic", latitude: 14.7112, longitude: -61.1812, sourceReference: "https://www.martinique.org/en" },
    { name: "Bellefontaine Surf Coast", pointType: "Beach / Waterfront", city: "Bellefontaine", submarket: "North Atlantic", latitude: 14.6734, longitude: -61.1689, sourceReference: "https://www.martinique.org/en" },
    { name: "Le Lorrain Atlantic Coast", pointType: "Beach / Waterfront", city: "Le Lorrain", submarket: "North Atlantic", latitude: 14.8312, longitude: -61.0534, sourceReference: "https://www.martinique.org/en" },
    { name: "Le François Bay and Islets", pointType: "Tourist Attraction", city: "Le François", submarket: "North Atlantic", latitude: 14.6189, longitude: -60.9012, sourceReference: "https://www.martinique.org/en" },
    { name: "Habitation Clément Rum Distillery", pointType: "Tourist Attraction", city: "Le François", submarket: "North Atlantic", latitude: 14.6512, longitude: -60.9234, sourceReference: "https://www.habitation-clement.fr/" },
    { name: "Robert Atlantic Coast", pointType: "Beach / Waterfront", city: "Le Robert", submarket: "North Atlantic", latitude: 14.6789, longitude: -60.9412, sourceReference: "https://www.martinique.org/en" },
    { name: "Presqu'île de la Caravelle Nature Reserve", pointType: "Tourist Attraction", city: "La Trinité", submarket: "North Atlantic", latitude: 14.7612, longitude: -60.9012, sourceReference: "https://www.martinique.org/en" },
    { name: "Le Marin Marina and Yacht Hub", pointType: "Mixed-Use Development", city: "Le Marin", submarket: "Other", latitude: 14.4712, longitude: -60.8689, sourceReference: "https://www.martinique.org/en", manuallyVerified: true },
    { name: "Rivière-Pilote East Coast Gateway", pointType: "Future Growth Node", city: "Rivière-Pilote", submarket: "Other", latitude: 14.4789, longitude: -60.9012, sourceReference: "https://www.martinique.org/en" },
    { name: "Le Vauclin Kitesurf Lagoon", pointType: "Beach / Waterfront", city: "Le Vauclin", submarket: "Other", latitude: 14.5489, longitude: -60.8412, sourceReference: "https://www.martinique.org/en" },
    { name: "Sainte-Marie Banana Museum Corridor", pointType: "Tourist Attraction", city: "Sainte-Marie", submarket: "Other", latitude: 14.7812, longitude: -60.9234, sourceReference: "https://www.martinique.org/en" },
    { name: "Le Morne-Rouge Highland Gateway", pointType: "Tourist Attraction", city: "Le Morne-Rouge", submarket: "Other", latitude: 14.7089, longitude: -61.1312, sourceReference: "https://www.martinique.org/en" },
    { name: "Fort-de-France Convention and Events Zone", pointType: "Convention Center", city: "Fort-de-France", submarket: "Fort-de-France", latitude: 14.6089, longitude: -61.0634, sourceReference: "https://www.martinique.org/en" },
    { name: "ZAC Étang Z'Abricots Industrial Zone", pointType: "Industrial / Logistics Zone", city: "Fort-de-France", submarket: "Fort-de-France", latitude: 14.5912, longitude: -61.0589, sourceReference: "https://www.martinique.org/en" },
    { name: "Case-Pilote West Coast Village", pointType: "Tourist Attraction", city: "Case-Pilote", submarket: "Other", latitude: 14.6412, longitude: -61.1389, sourceReference: "https://www.martinique.org/en" },
    { name: "Ducos Commercial and Retail Hub", pointType: "Business District", city: "Ducos", submarket: "Fort-de-France", latitude: 14.5789, longitude: -60.9712, sourceReference: "https://www.martinique.org/en" },
    { name: "Martinique South Cape Growth Corridor", pointType: "Future Growth Node", city: "Sainte-Anne", submarket: "South Coast", latitude: 14.4289, longitude: -60.8789, sourceReference: "https://www.martinique.org/en" },
  ],
  tiRecords: [
    { name: "Martinique Aimé Césaire Airport Access", pointType: "Highway Access", pointSubtype: "Airport Access", city: "Le Lamentin", submarket: "Fort-de-France", latitude: 14.591, longitude: -61.0032, sourceReference: "https://www.martinique.aeroport.fr/", notes: "Primary international gateway for Fort-de-France metro demand." },
    { name: "Fort-de-France Cruise Port Access", pointType: "Port / Maritime", pointSubtype: "Cruise Terminal", city: "Fort-de-France", submarket: "Fort-de-France", latitude: 14.6012, longitude: -61.0712, sourceReference: "https://www.martinique.org/en", notes: "Pointe Simon cruise terminal for capital and south-coast demand.", useCaseTags: ["Cruise / Port", "Resort / Leisure"] },
    { name: "Les Trois-Îlets Ferry and Marina Access", pointType: "Ferry Terminal", pointSubtype: "Marina", city: "Les Trois-Îlets", submarket: "South Coast", latitude: 14.5312, longitude: -61.0512, sourceReference: "https://www.martinique.org/en", notes: "South coast ferry link from Fort-de-France to resort beaches." },
    { name: "Le Marin Marina Access", pointType: "Port / Maritime", pointSubtype: "Marina", city: "Le Marin", submarket: "Other", latitude: 14.4712, longitude: -60.8689, sourceReference: "https://www.martinique.org/en", notes: "Major yacht marina hub for south Martinique sailing demand.", useCaseTags: ["Cruise / Port", "Resort / Leisure"] },
    { name: "Autoroute A1 Fort-de-France Access", pointType: "Highway Access", pointSubtype: "National Highway", city: "Fort-de-France", submarket: "Fort-de-France", latitude: 14.5989, longitude: -61.0512, sourceReference: "https://www.martinique.org/en", notes: "Primary highway connector from airport to capital." },
    { name: "Saint-Pierre North Coast Scenic Access", pointType: "Highway Access", pointSubtype: "Scenic Corridor", city: "Saint-Pierre", submarket: "North Atlantic", latitude: 14.7412, longitude: -61.1756, sourceReference: "https://www.martinique.org/en", notes: "North Atlantic scenic road to volcano heritage tourism." },
    { name: "Grande Anse des Salines Beach Access", pointType: "Highway Access", pointSubtype: "Resort Corridor", city: "Saint-Anne", submarket: "South Coast", latitude: 14.4389, longitude: -60.8812, sourceReference: "https://www.martinique.org/en", notes: "South cape beach road access for resort and day-trip demand." },
    { name: "Le François Bay Maritime Access", pointType: "Port / Maritime", pointSubtype: "Harbour Access", city: "Le François", submarket: "North Atlantic", latitude: 14.6189, longitude: -60.9012, sourceReference: "https://www.martinique.org/en", notes: "Atlantic bay harbour access for islet excursions and leisure boating." },
  ],
  googleCorrections: {},
};
