/** @typedef {import("./market-build-types.js").MarketBuildSpec} MarketBuildSpec */

/** @type {MarketBuildSpec} */
export const MERIDA_YUCATAN_BUILD = {
  slug: "merida-yucatan",
  country: "Mexico",
  region: "North America",
  sequence: 7,
  market: "Mérida / Yucatán",
  submarkets: [
    "Centro Histórico / Paseo de Montejo",
    "Siglo XXI / Convention Zone",
    "Airport Corridor",
    "Progreso / Costa Yucateca",
    "Industrial / Periférico",
    "Other",
  ],
  notes:
    "Yucatán capital and heritage gateway: Paseo de Montejo and centro histórico; Siglo XXI convention cluster; MID airport corridor; Progreso cruise and beach port; Uxmal and Chichén Itzá day-trip heritage demand.",
  tourismUrl: "https://www.visitmexico.com/en/main-destinations/yucatan/merida",
  microPass: {
    names: [],
    rules: [
      {
        base: ["https://www.visitmexico.com/", "https://www.visitmexico.com"],
        template: "https://www.visitmexico.com/en/main-destinations/yucatan/merida/{key}",
      },
      {
        base: ["https://www.yucatan.travel/", "https://www.yucatan.travel"],
        template: "https://www.yucatan.travel/{key}",
      },
    ],
  },
  audit: {
    keywords: [
      "merida",
      "yucatan",
      "mid",
      "paseo de montejo",
      "centro historico",
      "siglo xxi",
      "progreso",
      "chichen itza",
      "uxmal",
      "cruise",
      "malecon progreso",
      "cenote",
    ],
    expectedPatterns: [
      { label: "Mérida International Airport / MID", patterns: [/m[eé]rida international/i, /\bMID\b/i, /manuel crescencio/i] },
      { label: "Paseo de Montejo", patterns: [/paseo de montejo/i] },
      { label: "Centro Histórico Mérida", patterns: [/centro hist[oó]rico/i, /plaza grande/i] },
      { label: "Centro de Convenciones Yucatán Siglo XXI", patterns: [/siglo xxi/i, /convenciones yucat[aá]n/i] },
      { label: "Progreso cruise and beach port", patterns: [/progreso/i, /malec[oó]n.*progreso/i] },
      { label: "Chichén Itzá UNESCO", patterns: [/chich[eé]n itz[aá]/i, /unesco/i] },
      { label: "Uxmal archaeological zone", patterns: [/uxmal/i] },
    ],
  },
  candidates: [
    { name: "Mérida International Airport Corridor", pointType: "Future Growth Node", city: "Mérida", submarket: "Airport Corridor", latitude: 20.937, longitude: -89.6577, sourceReference: "https://www.aeropuertosasa.mx/", manuallyVerified: true },
    { name: "Paseo de Montejo Historic Boulevard", pointType: "Tourist Attraction", city: "Mérida", submarket: "Centro Histórico / Paseo de Montejo", latitude: 20.9756, longitude: -89.6178, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida" },
    { name: "Plaza Grande Centro Histórico", pointType: "Government / Civic Center", city: "Mérida", submarket: "Centro Histórico / Paseo de Montejo", latitude: 20.9674, longitude: -89.5926, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida" },
    { name: "Catedral de San Ildefonso Mérida", pointType: "Tourist Attraction", city: "Mérida", submarket: "Centro Histórico / Paseo de Montejo", latitude: 20.9671, longitude: -89.5923, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida" },
    { name: "Palacio de Gobierno Yucatán", pointType: "Government / Civic Center", city: "Mérida", submarket: "Centro Histórico / Paseo de Montejo", latitude: 20.9678, longitude: -89.5912, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida" },
    { name: "Teatro Peón Contreras", pointType: "Tourist Attraction", city: "Mérida", submarket: "Centro Histórico / Paseo de Montejo", latitude: 20.9689, longitude: -89.6234, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida" },
    { name: "Museo Regional de Antropología Palacio Cantón", pointType: "Tourist Attraction", city: "Mérida", submarket: "Centro Histórico / Paseo de Montejo", latitude: 20.9789, longitude: -89.6234, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida" },
    { name: "Gran Museo del Mundo Maya", pointType: "Tourist Attraction", city: "Mérida", submarket: "Centro Histórico / Paseo de Montejo", latitude: 20.9512, longitude: -89.6234, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida" },
    { name: "Santa Lucía Park Dining Corridor", pointType: "Entertainment District", city: "Mérida", submarket: "Centro Histórico / Paseo de Montejo", latitude: 20.9712, longitude: -89.6189, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida" },
    { name: "Centro Histórico Boutique Hotel Zone", pointType: "Mixed-Use Development", city: "Mérida", submarket: "Centro Histórico / Paseo de Montejo", latitude: 20.9667, longitude: -89.5945, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida" },
    { name: "Centro de Convenciones Yucatán Siglo XXI", pointType: "Convention Center", city: "Mérida", submarket: "Siglo XXI / Convention Zone", latitude: 20.9939, longitude: -89.6142, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida" },
    { name: "Hotel Zone Siglo XXI Convention Hotels", pointType: "Mixed-Use Development", city: "Mérida", submarket: "Siglo XXI / Convention Zone", latitude: 20.9912, longitude: -89.6167, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida" },
    { name: "Plaza Galerías Mérida", pointType: "Entertainment District", city: "Mérida", submarket: "Siglo XXI / Convention Zone", latitude: 20.9889, longitude: -89.6189, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida" },
    { name: "City Center Mérida Shopping Complex", pointType: "Entertainment District", city: "Mérida", submarket: "Siglo XXI / Convention Zone", latitude: 20.9867, longitude: -89.6212, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida" },
    { name: "Siglo XXI Government and Civic Precinct", pointType: "Government / Civic Center", city: "Mérida", submarket: "Siglo XXI / Convention Zone", latitude: 20.9956, longitude: -89.6123, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida" },
    { name: "MID Airport Hotel and Business Corridor", pointType: "Business District", city: "Mérida", submarket: "Airport Corridor", latitude: 20.9312, longitude: -89.6512, sourceReference: "https://www.aeropuertosasa.mx/" },
    { name: "Mérida Airport Cargo and Logistics Zone", pointType: "Industrial / Logistics Zone", city: "Mérida", submarket: "Airport Corridor", latitude: 20.9412, longitude: -89.6623, sourceReference: "https://www.aeropuertosasa.mx/" },
    { name: "Progreso Malecón Beach and Cruise Port", pointType: "Beach / Waterfront", city: "Progreso", submarket: "Progreso / Costa Yucateca", latitude: 21.2853, longitude: -89.6644, sourceReference: "https://www.yucatan.travel/", manuallyVerified: true },
    { name: "Puerto Progreso Cruise Ship Terminal", pointType: "Mixed-Use Development", city: "Progreso", submarket: "Progreso / Costa Yucateca", latitude: 21.2812, longitude: -89.6689, sourceReference: "https://www.yucatan.travel/", manuallyVerified: true },
    { name: "Progreso Beach Resort Strip", pointType: "Beach / Waterfront", city: "Progreso", submarket: "Progreso / Costa Yucateca", latitude: 21.2789, longitude: -89.6712, sourceReference: "https://www.yucatan.travel/" },
    { name: "Chicxulub Puerto Beach Town", pointType: "Beach / Waterfront", city: "Chicxulub Puerto", submarket: "Progreso / Costa Yucateca", latitude: 21.2689, longitude: -89.6012, sourceReference: "https://www.yucatan.travel/" },
    { name: "Telchac Puerto Beach Corridor", pointType: "Beach / Waterfront", city: "Telchac Puerto", submarket: "Progreso / Costa Yucateca", latitude: 21.3234, longitude: -89.2789, sourceReference: "https://www.yucatan.travel/" },
    { name: "Chichén Itzá Archaeological Zone UNESCO", pointType: "Tourist Attraction", city: "Tinúm", submarket: "Other", latitude: 20.6843, longitude: -88.5678, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/chichen-itza", manuallyVerified: true },
    { name: "Uxmal Archaeological Zone UNESCO", pointType: "Tourist Attraction", city: "Santa Elena", submarket: "Other", latitude: 20.3594, longitude: -89.7715, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/uxmal", manuallyVerified: true },
    { name: "Cenote Ik Kil Chichén Itzá", pointType: "Tourist Attraction", city: "Tinúm", submarket: "Other", latitude: 20.6612, longitude: -88.5534, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/chichen-itza" },
    { name: "Valladolid Colonial Pueblo Mágico", pointType: "Tourist Attraction", city: "Valladolid", submarket: "Other", latitude: 20.6889, longitude: -88.2012, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/valladolid" },
    { name: "Izamal Yellow City Pueblo Mágico", pointType: "Tourist Attraction", city: "Izamal", submarket: "Other", latitude: 20.9334, longitude: -89.0178, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/izamal" },
    { name: "Celestún Biosphere Reserve Flamingo Coast", pointType: "Tourist Attraction", city: "Celestún", submarket: "Other", latitude: 20.8612, longitude: -90.4012, sourceReference: "https://www.yucatan.travel/" },
    { name: "Ruta de los Cenotes Corridor", pointType: "Tourist Attraction", city: "Cuzamá", submarket: "Other", latitude: 20.7412, longitude: -89.3234, sourceReference: "https://www.yucatan.travel/" },
    { name: "Hospital Star Médica Mérida", pointType: "Medical Campus", city: "Mérida", submarket: "Siglo XXI / Convention Zone", latitude: 20.9845, longitude: -89.6234, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida" },
    { name: "Clínica de Mérida Medical District", pointType: "Medical Campus", city: "Mérida", submarket: "Centro Histórico / Paseo de Montejo", latitude: 20.9734, longitude: -89.6012, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida" },
    { name: "Universidad Autónoma de Yucatán Campus", pointType: "University / College", city: "Mérida", submarket: "Centro Histórico / Paseo de Montejo", latitude: 20.9889, longitude: -89.6345, sourceReference: "https://www.uady.mx/" },
    { name: "Universidad Marista de Mérida", pointType: "University / College", city: "Mérida", submarket: "Industrial / Periférico", latitude: 20.9612, longitude: -89.6512, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida" },
    { name: "Parque Industrial Yucatán", pointType: "Industrial / Logistics Zone", city: "Umán", submarket: "Industrial / Periférico", latitude: 20.8912, longitude: -89.7512, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida" },
    { name: "Periférico Mérida Industrial Corridor", pointType: "Industrial / Logistics Zone", city: "Mérida", submarket: "Industrial / Periférico", latitude: 20.9512, longitude: -89.6789, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida" },
    { name: "Ciudad Industrial Mérida Norte", pointType: "Industrial / Logistics Zone", city: "Mérida", submarket: "Industrial / Periférico", latitude: 21.0012, longitude: -89.6345, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida" },
    { name: "Mérida Norte Residential Growth Node", pointType: "Future Growth Node", city: "Mérida", submarket: "Industrial / Periférico", latitude: 21.0234, longitude: -89.6123, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida" },
    { name: "La Isla Mérida Shopping Center", pointType: "Entertainment District", city: "Mérida", submarket: "Siglo XXI / Convention Zone", latitude: 20.9823, longitude: -89.6267, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida" },
    { name: "Altabrisa Mall Mérida", pointType: "Entertainment District", city: "Mérida", submarket: "Industrial / Periférico", latitude: 20.9689, longitude: -89.6412, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida" },
    { name: "Hacienda Sotuta de Peón Living Museum", pointType: "Tourist Attraction", city: "Tekit", submarket: "Other", latitude: 20.5312, longitude: -89.2789, sourceReference: "https://www.yucatan.travel/" },
    { name: "Mayapán Archaeological Site", pointType: "Tourist Attraction", city: "Telchaquillo", submarket: "Other", latitude: 20.6289, longitude: -89.4612, sourceReference: "https://www.yucatan.travel/" },
    { name: "Dzibilchaltún Archaeological Site", pointType: "Tourist Attraction", city: "Mérida", submarket: "Other", latitude: 21.0912, longitude: -89.5912, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida" },
    { name: "Mérida Gastronomic Corridor Santiago", pointType: "Entertainment District", city: "Mérida", submarket: "Centro Histórico / Paseo de Montejo", latitude: 20.9645, longitude: -89.6234, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida" },
    { name: "Paseo de Montejo Mansion Row", pointType: "Tourist Attraction", city: "Mérida", submarket: "Centro Histórico / Paseo de Montejo", latitude: 20.9812, longitude: -89.6189, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida" },
    { name: "Mérida International Convention Hotel Cluster", pointType: "Convention Center", city: "Mérida", submarket: "Siglo XXI / Convention Zone", latitude: 20.9901, longitude: -89.6156, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida" },
    { name: "Progreso International Terminal Logistics", pointType: "Industrial / Logistics Zone", city: "Progreso", submarket: "Progreso / Costa Yucateca", latitude: 21.2834, longitude: -89.6712, sourceReference: "https://www.yucatan.travel/" },
    { name: "Mérida Periférico Convention Access Node", pointType: "Future Growth Node", city: "Mérida", submarket: "Siglo XXI / Convention Zone", latitude: 20.9878, longitude: -89.6089, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida" },
    { name: "Chuburná Puerto Beach Residential", pointType: "Beach / Waterfront", city: "Progreso", submarket: "Progreso / Costa Yucateca", latitude: 21.2734, longitude: -89.6634, sourceReference: "https://www.yucatan.travel/" },
    { name: "Mérida Centro Histórico Sunday Market", pointType: "Entertainment District", city: "Mérida", submarket: "Centro Histórico / Paseo de Montejo", latitude: 20.9672, longitude: -89.5934, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida" },
    { name: "Yucatán Industrial Port of Progreso Access", pointType: "Future Growth Node", city: "Progreso", submarket: "Progreso / Costa Yucateca", latitude: 21.2798, longitude: -89.6656, sourceReference: "https://www.yucatan.travel/" },
    { name: "Mérida Airport Business Park Growth Node", pointType: "Future Growth Node", city: "Mérida", submarket: "Airport Corridor", latitude: 20.9289, longitude: -89.6489, sourceReference: "https://www.aeropuertosasa.mx/" },
    { name: "Hacienda Temozón Luxury Hotel Zone", pointType: "Mixed-Use Development", city: "Temozón", submarket: "Other", latitude: 20.9012, longitude: -88.9234, sourceReference: "https://www.yucatan.travel/" },
    { name: "Mérida North Periférico Office Corridor", pointType: "Business District", city: "Mérida", submarket: "Industrial / Periférico", latitude: 21.0123, longitude: -89.6234, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida" },
  ],
  tiRecords: [
    { name: "Mérida International Airport Access", pointType: "Highway Access", pointSubtype: "Airport Access", city: "Mérida", submarket: "Airport Corridor", latitude: 20.937, longitude: -89.6577, sourceReference: "https://www.aeropuertosasa.mx/", notes: "Primary international gateway for Mérida urban and Yucatán tourism demand." },
    { name: "Paseo de Montejo Boulevard Access", pointType: "Highway Access", pointSubtype: "Urban Artery", city: "Mérida", submarket: "Centro Histórico / Paseo de Montejo", latitude: 20.9756, longitude: -89.6178, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida", notes: "Main historic boulevard access for centro and boutique hotel demand." },
    { name: "Centro de Convenciones Siglo XXI Access", pointType: "Highway Access", pointSubtype: "Convention Access", city: "Mérida", submarket: "Siglo XXI / Convention Zone", latitude: 20.9939, longitude: -89.6142, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida", notes: "Convention center highway access for MICE and group compression." },
    { name: "Progreso Cruise Terminal Access", pointType: "Port / Maritime", pointSubtype: "Cruise Terminal", city: "Progreso", submarket: "Progreso / Costa Yucateca", latitude: 21.2812, longitude: -89.6689, sourceReference: "https://www.yucatan.travel/", notes: "Gulf cruise terminal supporting day-call and pre/post-stay lodging.", useCaseTags: ["Cruise / Port", "Resort / Leisure"] },
    { name: "Progreso Malecón Beach Access", pointType: "Highway Access", pointSubtype: "Resort Corridor", city: "Progreso", submarket: "Progreso / Costa Yucateca", latitude: 21.2853, longitude: -89.6644, sourceReference: "https://www.yucatan.travel/", notes: "Coastal highway access for Progreso weekend beach and cruise demand." },
    { name: "Chichén Itzá Tourism Highway Access", pointType: "Highway Access", pointSubtype: "Tourism Corridor", city: "Tinúm", submarket: "Other", latitude: 20.6843, longitude: -88.5678, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/chichen-itza", notes: "Primary heritage day-trip corridor from Mérida hotel base." },
    { name: "Uxmal Ruta Puuc Highway Access", pointType: "Highway Access", pointSubtype: "Tourism Corridor", city: "Santa Elena", submarket: "Other", latitude: 20.3594, longitude: -89.7715, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/uxmal", notes: "Southwest heritage corridor for Uxmal and Ruta Puuc visitation." },
    { name: "Periférico Mérida Ring Road Access", pointType: "Highway Access", pointSubtype: "Urban Artery", city: "Mérida", submarket: "Industrial / Periférico", latitude: 20.9512, longitude: -89.6789, sourceReference: "https://www.visitmexico.com/en/main-destinations/yucatan/merida", notes: "Periférico ring road linking airport, industrial parks, and north Mérida growth." },
  ],
  googleCorrections: {},
};
