/** @typedef {import("./market-build-types.js").MarketBuildSpec} MarketBuildSpec */

/** @type {MarketBuildSpec} */
export const MEXICO_CITY_BUILD = {
  slug: "mexico-city",
  country: "Mexico",
  region: "North America",
  sequence: 2,
  market: "Mexico City",
  submarkets: [
    "Polanco",
    "Reforma / Juárez",
    "Santa Fe",
    "Condesa / Roma",
    "Centro Histórico",
    "Insurgentes / WTC",
    "Airport Corridor",
    "Coyoacán / San Ángel",
    "Other",
  ],
  notes:
    "CDMX urban benchmark: Polanco/Reforma corporate-luxury; Santa Fe west business district; Condesa/Roma lifestyle; Centro Histórico UNESCO civic; AICM airport corridor.",
  tourismUrl: "https://www.visitmexico.com/en/main-destinations/mexico-city",
  microPass: {
    names: [],
    rules: [
      {
        base: ["https://www.visitmexico.com/", "https://www.visitmexico.com"],
        template: "https://www.visitmexico.com/en/main-destinations/mexico-city/{key}",
      },
    ],
  },
  audit: {
    keywords: [
      "mexico city",
      "cdmx",
      "polanco",
      "reforma",
      "santa fe",
      "condesa",
      "roma",
      "centro historico",
      "zocalo",
      "chapultepec",
      "wtc",
      "coyoacan",
      "aicm",
      "mex",
      "benito juarez",
      "bellas artes",
      "unam",
    ],
    expectedPatterns: [
      { label: "Benito Juárez International Airport / MEX", patterns: [/benito ju[aá]rez/i, /\bMEX\b/i, /\bAICM\b/i] },
      { label: "Centro Histórico UNESCO", patterns: [/centro hist[oó]rico/i, /z[oó]calo/i, /unesco/i] },
      { label: "Paseo de la Reforma corridor", patterns: [/reforma/i, /angel de la independencia/i] },
      { label: "Polanco luxury corridor", patterns: [/polanco/i, /soumaya/i, /antara/i] },
      { label: "Santa Fe business district", patterns: [/santa fe/i, /centro santa fe/i] },
      { label: "World Trade Center CDMX", patterns: [/world trade center/i, /\bWTC\b/i] },
      { label: "Chapultepec Park anchor", patterns: [/chapultepec/i] },
      { label: "Coyoacán cultural corridor", patterns: [/coyoac[aá]n/i, /frida kahlo/i] },
    ],
  },
  candidates: [
    { name: "Benito Juárez International Airport Corridor", pointType: "Future Growth Node", city: "Mexico City", submarket: "Airport Corridor", latitude: 19.4363, longitude: -99.0721, sourceReference: "https://www.aicm.com.mx/", manuallyVerified: true },
    { name: "Museo Soumaya Polanco", pointType: "Tourist Attraction", city: "Mexico City", submarket: "Polanco", latitude: 19.4407, longitude: -99.2056, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Antara Fashion Hall Polanco", pointType: "Entertainment District", city: "Mexico City", submarket: "Polanco", latitude: 19.4383, longitude: -99.2017, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Museo Jumex Polanco", pointType: "Tourist Attraction", city: "Mexico City", submarket: "Polanco", latitude: 19.4401, longitude: -99.2041, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Polanco Business and Embassy Corridor", pointType: "Business District", city: "Mexico City", submarket: "Polanco", latitude: 19.4336, longitude: -99.1991, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Centro Citibanamex Convention Precinct", pointType: "Convention Center", city: "Mexico City", submarket: "Polanco", latitude: 19.4378, longitude: -99.2045, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Lago Mayor Chapultepec Polanco Edge", pointType: "Beach / Waterfront", city: "Mexico City", submarket: "Polanco", latitude: 19.4245, longitude: -99.1945, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Ángel de la Independencia Reforma", pointType: "Tourist Attraction", city: "Mexico City", submarket: "Reforma / Juárez", latitude: 19.427, longitude: -99.1677, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Chapultepec Castle and Park", pointType: "Tourist Attraction", city: "Mexico City", submarket: "Reforma / Juárez", latitude: 19.4204, longitude: -99.1817, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Museo Nacional de Antropología", pointType: "Tourist Attraction", city: "Mexico City", submarket: "Reforma / Juárez", latitude: 19.426, longitude: -99.1863, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Paseo de la Reforma Financial Corridor", pointType: "Business District", city: "Mexico City", submarket: "Reforma / Juárez", latitude: 19.4286, longitude: -99.1611, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Torre Mayor Reforma CBD", pointType: "Business District", city: "Mexico City", submarket: "Reforma / Juárez", latitude: 19.4245, longitude: -99.1758, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Diana Cazadora Roundabout Reforma", pointType: "Entertainment District", city: "Mexico City", submarket: "Reforma / Juárez", latitude: 19.4252, longitude: -99.1708, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Zona Rosa Entertainment Corridor", pointType: "Entertainment District", city: "Mexico City", submarket: "Reforma / Juárez", latitude: 19.4268, longitude: -99.1635, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Centro Santa Fe", pointType: "Mixed-Use Development", city: "Mexico City", submarket: "Santa Fe", latitude: 19.3594, longitude: -99.2767, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Samara Shops Santa Fe", pointType: "Entertainment District", city: "Mexico City", submarket: "Santa Fe", latitude: 19.3631, longitude: -99.2712, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Hospital ABC Santa Fe Campus", pointType: "Medical Campus", city: "Mexico City", submarket: "Santa Fe", latitude: 19.3678, longitude: -99.2634, sourceReference: "https://www.abchospital.com/" },
    { name: "Parque La Mexicana Santa Fe", pointType: "Mixed-Use Development", city: "Mexico City", submarket: "Santa Fe", latitude: 19.3712, longitude: -99.2689, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Torre Corporativa Santa Fe", pointType: "Business District", city: "Mexico City", submarket: "Santa Fe", latitude: 19.3567, longitude: -99.2745, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Tecnológico de Monterrey Santa Fe Campus", pointType: "University / College", city: "Mexico City", submarket: "Santa Fe", latitude: 19.3523, longitude: -99.2812, sourceReference: "https://www.tec.mx/" },
    { name: "Parque México Condesa", pointType: "Entertainment District", city: "Mexico City", submarket: "Condesa / Roma", latitude: 19.4117, longitude: -99.1717, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Condesa Dining and Nightlife Corridor", pointType: "Entertainment District", city: "Mexico City", submarket: "Condesa / Roma", latitude: 19.4123, longitude: -99.1756, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Roma Norte Art and Design District", pointType: "Entertainment District", city: "Mexico City", submarket: "Condesa / Roma", latitude: 19.4189, longitude: -99.1623, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Plaza Luis Cabrera Condesa", pointType: "Mixed-Use Development", city: "Mexico City", submarket: "Condesa / Roma", latitude: 19.4089, longitude: -99.1689, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Centro Cultural de España en México", pointType: "Tourist Attraction", city: "Mexico City", submarket: "Condesa / Roma", latitude: 19.4212, longitude: -99.1589, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Mercado Roma Food Hall", pointType: "Entertainment District", city: "Mexico City", submarket: "Condesa / Roma", latitude: 19.4167, longitude: -99.1612, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Zócalo Plaza de la Constitución UNESCO", pointType: "Government / Civic Center", city: "Mexico City", submarket: "Centro Histórico", latitude: 19.4326, longitude: -99.1332, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city", manuallyVerified: true },
    { name: "Palacio de Bellas Artes", pointType: "Tourist Attraction", city: "Mexico City", submarket: "Centro Histórico", latitude: 19.4352, longitude: -99.1413, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Metropolitan Cathedral Mexico City", pointType: "Tourist Attraction", city: "Mexico City", submarket: "Centro Histórico", latitude: 19.4345, longitude: -99.1312, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Templo Mayor Archaeological Zone", pointType: "Tourist Attraction", city: "Mexico City", submarket: "Centro Histórico", latitude: 19.435, longitude: -99.1313, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Torre Latinoamericana Observation Deck", pointType: "Tourist Attraction", city: "Mexico City", submarket: "Centro Histórico", latitude: 19.4338, longitude: -99.1406, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Alameda Central Park", pointType: "Entertainment District", city: "Mexico City", submarket: "Centro Histórico", latitude: 19.4358, longitude: -99.1442, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Palacio Nacional Government Precinct", pointType: "Government / Civic Center", city: "Mexico City", submarket: "Centro Histórico", latitude: 19.4324, longitude: -99.1315, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Mercado de San Juan Gourmet Market", pointType: "Entertainment District", city: "Mexico City", submarket: "Centro Histórico", latitude: 19.4278, longitude: -99.1389, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "World Trade Center Mexico City", pointType: "Convention Center", city: "Mexico City", submarket: "Insurgentes / WTC", latitude: 19.3942, longitude: -99.1735, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Insurgentes Sur Corporate Corridor", pointType: "Business District", city: "Mexico City", submarket: "Insurgentes / WTC", latitude: 19.3812, longitude: -99.1789, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Torre Insignia WTC District", pointType: "Business District", city: "Mexico City", submarket: "Insurgentes / WTC", latitude: 19.3934, longitude: -99.1712, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Pepsi Center WTC Arena", pointType: "Sports Venue", city: "Mexico City", submarket: "Insurgentes / WTC", latitude: 19.3956, longitude: -99.1756, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Centro Banorte WTC Convention Annex", pointType: "Convention Center", city: "Mexico City", submarket: "Insurgentes / WTC", latitude: 19.3923, longitude: -99.1767, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Aeropuerto Cargo and Logistics Zone", pointType: "Industrial / Logistics Zone", city: "Mexico City", submarket: "Airport Corridor", latitude: 19.4289, longitude: -99.0656, sourceReference: "https://www.aicm.com.mx/" },
    { name: "Peñón de los Baños Transit Hub", pointType: "Future Growth Node", city: "Mexico City", submarket: "Airport Corridor", latitude: 19.4512, longitude: -99.0789, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Pantitlán Multimodal Station", pointType: "Future Growth Node", city: "Mexico City", submarket: "Airport Corridor", latitude: 19.4156, longitude: -99.0723, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Museo Frida Kahlo Casa Azul", pointType: "Tourist Attraction", city: "Coyoacán", submarket: "Coyoacán / San Ángel", latitude: 19.355, longitude: -99.1623, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "UNAM Ciudad Universitaria Campus", pointType: "University / College", city: "Coyoacán", submarket: "Coyoacán / San Ángel", latitude: 19.3244, longitude: -99.2, sourceReference: "https://www.unam.mx/" },
    { name: "Estadio Olímpico Universitario", pointType: "Sports Venue", city: "Coyoacán", submarket: "Coyoacán / San Ángel", latitude: 19.3312, longitude: -99.1912, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "San Ángel Bazaar and Cultural District", pointType: "Tourist Attraction", city: "Álvaro Obregón", submarket: "Coyoacán / San Ángel", latitude: 19.3456, longitude: -99.1945, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Estadio Azteca", pointType: "Sports Venue", city: "Tlalpan", submarket: "Coyoacán / San Ángel", latitude: 19.3029, longitude: -99.1505, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Basilica of Our Lady of Guadalupe", pointType: "Tourist Attraction", city: "Gustavo A. Madero", submarket: "Other", latitude: 19.4847, longitude: -99.1176, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Teotihuacán Archaeological Zone", pointType: "Tourist Attraction", city: "San Juan Teotihuacán", submarket: "Other", latitude: 19.6925, longitude: -98.8437, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-state/teotihuacan", manuallyVerified: true },
    { name: "Arena Ciudad de México", pointType: "Sports Venue", city: "Azcapotzalco", submarket: "Other", latitude: 19.4931, longitude: -99.2386, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Autódromo Hermanos Rodríguez", pointType: "Sports Venue", city: "Iztacalco", submarket: "Other", latitude: 19.4042, longitude: -99.0908, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
    { name: "Foro Sol Entertainment Complex", pointType: "Entertainment District", city: "Iztacalco", submarket: "Other", latitude: 19.4056, longitude: -99.0923, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city" },
  ],
  tiRecords: [
    { name: "Benito Juárez International Airport Access", pointType: "Highway Access", pointSubtype: "Airport Access", city: "Mexico City", submarket: "Airport Corridor", latitude: 19.4363, longitude: -99.0721, sourceReference: "https://www.aicm.com.mx/", notes: "Primary international gateway for CDMX corporate and leisure demand." },
    { name: "Paseo de la Reforma Corridor Access", pointType: "Highway Access", pointSubtype: "Urban Artery", city: "Mexico City", submarket: "Reforma / Juárez", latitude: 19.427, longitude: -99.1677, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city", notes: "Main reforma corridor linking Polanco, Reforma hotels, and Chapultepec." },
    { name: "Centro Santa Fe Highway Access", pointType: "Highway Access", pointSubtype: "Business District", city: "Mexico City", submarket: "Santa Fe", latitude: 19.3594, longitude: -99.2767, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city", notes: "West CDMX corporate campus access via Santa Fe toll road network." },
    { name: "World Trade Center Mexico Access", pointType: "Highway Access", pointSubtype: "Convention Access", city: "Mexico City", submarket: "Insurgentes / WTC", latitude: 19.3942, longitude: -99.1735, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city", notes: "Insurgentes Sur access for WTC meetings and group demand." },
    { name: "Centro Histórico Transit Hub Access", pointType: "Highway Access", pointSubtype: "Historic Core", city: "Mexico City", submarket: "Centro Histórico", latitude: 19.4326, longitude: -99.1332, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city", notes: "Zócalo and historic core multimodal access for cultural tourism." },
    { name: "Chapultepec Park Connector Access", pointType: "Highway Access", pointSubtype: "Park Corridor", city: "Mexico City", submarket: "Reforma / Juárez", latitude: 19.4204, longitude: -99.1817, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city", notes: "Chapultepec access linking Reforma hotels to museum and park demand." },
    { name: "Coyoacán Cultural District Access", pointType: "Highway Access", pointSubtype: "Cultural Corridor", city: "Coyoacán", submarket: "Coyoacán / San Ángel", latitude: 19.355, longitude: -99.1623, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-city", notes: "Southern cultural corridor access for Frida Kahlo and UNAM visitation." },
    { name: "Teotihuacán Day-Trip Highway Access", pointType: "Highway Access", pointSubtype: "Tourism Corridor", city: "San Juan Teotihuacán", submarket: "Other", latitude: 19.6925, longitude: -98.8437, sourceReference: "https://www.visitmexico.com/en/main-destinations/mexico-state/teotihuacan", notes: "Northeast tourism corridor for day-trip and group heritage demand from CDMX hotels." },
  ],
  googleCorrections: {},
};
