/** @typedef {import("../islands/island-build-types.js").IslandBuildSpec} IslandBuildSpec */

/** @type {IslandBuildSpec} */
export const US_VIRGIN_ISLANDS_BUILD = {
  slug: "us-virgin-islands",
  country: "U.S. Virgin Islands",
  region: "Caribbean",
  sequence: 33,
  market: "U.S. Virgin Islands Countrywide",
  submarkets: ["St. Thomas", "St. Croix", "St. John", "Other"],
  notes: "St. Thomas cruise and duty-free hub; St. Croix historic and industrial mix; St. John national park leisure; Water Island and outer cays.",
  tourismUrl: "https://www.visitusvi.com/",
  microPass: {
    names: [],
    rules: [{ base: ["https://www.visitusvi.com/", "https://www.visitusvi.com"], template: "https://www.visitusvi.com/places/{key}" }],
  },
  audit: {
    keywords: ["usvi", "st thomas", "st croix", "st john", "charlotte amalie", "christiansted", "cruz bay", "magens bay", "stt", "stx"],
    expectedPatterns: [
      { label: "Cyril E. King Airport / STT", patterns: [/cyril e\.? king/i, /\bSTT\b/i] },
      { label: "Henry E. Rohlsen Airport / STX", patterns: [/henry e\.? rohlsen/i, /\bSTX\b/i] },
      { label: "Charlotte Amalie cruise port", patterns: [/charlotte amalie.*cruise/i, /havensight/i] },
      { label: "Christiansted historic district", patterns: [/christiansted/i] },
      { label: "Cruz Bay St. John ferry", patterns: [/cruz bay/i] },
    ],
  },
  candidates: [
    { name: "Cyril E. King International Airport Corridor", pointType: "Future Growth Node", city: "St. Thomas", submarket: "St. Thomas", latitude: 18.3373, longitude: -64.9734, sourceReference: "https://www.viport.com/", manuallyVerified: true },
    { name: "Charlotte Amalie Cruise Port — Havensight", pointType: "Mixed-Use Development", city: "Charlotte Amalie", submarket: "St. Thomas", latitude: 18.3312, longitude: -64.9289, sourceReference: "https://www.visitusvi.com/", manuallyVerified: true },
    { name: "Charlotte Amalie Historic District", pointType: "Tourist Attraction", city: "Charlotte Amalie", submarket: "St. Thomas", latitude: 18.3412, longitude: -64.9312, sourceReference: "https://www.visitusvi.com/" },
    { name: "Main Street Duty-Free Shopping Corridor", pointType: "Entertainment District", city: "Charlotte Amalie", submarket: "St. Thomas", latitude: 18.3423, longitude: -64.9334, sourceReference: "https://www.visitusvi.com/" },
    { name: "Magens Bay Beach", pointType: "Beach / Waterfront", city: "St. Thomas", submarket: "St. Thomas", latitude: 18.3689, longitude: -64.9234, sourceReference: "https://www.visitusvi.com/", manuallyVerified: true },
    { name: "Red Hook Ferry Terminal and Marina", pointType: "Beach / Waterfront", city: "Red Hook", submarket: "St. Thomas", latitude: 18.3189, longitude: -64.8512, sourceReference: "https://www.visitusvi.com/", manuallyVerified: true },
    { name: "Sapphire Beach Resort Corridor", pointType: "Beach / Waterfront", city: "Red Hook", submarket: "St. Thomas", latitude: 18.3234, longitude: -64.8567, sourceReference: "https://www.visitusvi.com/" },
    { name: "Coki Beach and Coral World", pointType: "Tourist Attraction", city: "St. Thomas", submarket: "St. Thomas", latitude: 18.3512, longitude: -64.8678, sourceReference: "https://www.visitusvi.com/" },
    { name: "University of the Virgin Islands — St. Thomas", pointType: "University / College", city: "St. Thomas", submarket: "St. Thomas", latitude: 18.3389, longitude: -64.9812, sourceReference: "https://www.uvi.edu/" },
    { name: "Schneider Regional Medical Center", pointType: "Medical Campus", city: "St. Thomas", submarket: "St. Thomas", latitude: 18.3456, longitude: -64.9456, sourceReference: "https://www.srmedicalcenter.org/" },
    { name: "Emancipation Garden Civic Precinct", pointType: "Government / Civic Center", city: "Charlotte Amalie", submarket: "St. Thomas", latitude: 18.3401, longitude: -64.9345, sourceReference: "https://www.visitusvi.com/" },
    { name: "Yacht Haven Grande Marina", pointType: "Mixed-Use Development", city: "Charlotte Amalie", submarket: "St. Thomas", latitude: 18.3356, longitude: -64.9267, sourceReference: "https://www.visitusvi.com/" },
    { name: "Drake's Seat Scenic Overlook", pointType: "Tourist Attraction", city: "St. Thomas", submarket: "St. Thomas", latitude: 18.3612, longitude: -64.9123, sourceReference: "https://www.visitusvi.com/" },
    { name: "Henry E. Rohlsen International Airport Corridor", pointType: "Future Growth Node", city: "St. Croix", submarket: "St. Croix", latitude: 17.7019, longitude: -64.7986, sourceReference: "https://www.viport.com/", manuallyVerified: true },
    { name: "Christiansted Historic Waterfront", pointType: "Tourist Attraction", city: "Christiansted", submarket: "St. Croix", latitude: 17.7467, longitude: -64.7034, sourceReference: "https://www.visitusvi.com/", manuallyVerified: true },
    { name: "Fort Christiansvaern Historic Site", pointType: "Tourist Attraction", city: "Christiansted", submarket: "St. Croix", latitude: 17.7478, longitude: -64.7012, sourceReference: "https://www.visitusvi.com/" },
    { name: "Frederiksted Cruise Pier", pointType: "Mixed-Use Development", city: "Frederiksted", submarket: "St. Croix", latitude: 17.7123, longitude: -64.8834, sourceReference: "https://www.visitusvi.com/", manuallyVerified: true },
    { name: "Buck Island Reef National Monument", pointType: "Tourist Attraction", city: "St. Croix", submarket: "St. Croix", latitude: 17.7867, longitude: -64.6234, sourceReference: "https://www.nps.gov/buis/" },
    { name: "Sandy Point National Wildlife Refuge", pointType: "Tourist Attraction", city: "St. Croix", submarket: "St. Croix", latitude: 17.6734, longitude: -64.8912, sourceReference: "https://www.fws.gov/refuge/sandy-point" },
    { name: "University of the Virgin Islands — St. Croix", pointType: "University / College", city: "Kingshill", submarket: "St. Croix", latitude: 17.7234, longitude: -64.7512, sourceReference: "https://www.uvi.edu/" },
    { name: "Juan F. Luis Hospital", pointType: "Medical Campus", city: "St. Croix", submarket: "St. Croix", latitude: 17.7312, longitude: -64.7589, sourceReference: "https://www.jflusvi.org/" },
    { name: "Hovensa Industrial Heritage Zone", pointType: "Industrial / Logistics Zone", city: "St. Croix", submarket: "St. Croix", latitude: 17.6989, longitude: -64.7612, sourceReference: "https://www.visitusvi.com/" },
    { name: "Point Udall — Easternmost U.S. Point", pointType: "Tourist Attraction", city: "St. Croix", submarket: "St. Croix", latitude: 17.7567, longitude: -64.5667, sourceReference: "https://www.visitusvi.com/" },
    { name: "Cruz Bay Ferry Terminal", pointType: "Mixed-Use Development", city: "Cruz Bay", submarket: "St. John", latitude: 18.3312, longitude: -64.7934, sourceReference: "https://www.visitusvi.com/", manuallyVerified: true },
    { name: "Virgin Islands National Park — Trunk Bay", pointType: "Tourist Attraction", city: "St. John", submarket: "St. John", latitude: 18.3489, longitude: -64.7678, sourceReference: "https://www.nps.gov/viis/", manuallyVerified: true },
    { name: "Cinnamon Bay Beach Campground", pointType: "Beach / Waterfront", city: "St. John", submarket: "St. John", latitude: 18.3567, longitude: -64.7512, sourceReference: "https://www.nps.gov/viis/" },
    { name: "Maho Bay Beach", pointType: "Beach / Waterfront", city: "St. John", submarket: "St. John", latitude: 18.3612, longitude: -64.7456, sourceReference: "https://www.nps.gov/viis/" },
    { name: "Coral Bay Village", pointType: "Tourist Attraction", city: "Coral Bay", submarket: "St. John", latitude: 18.3234, longitude: -64.7234, sourceReference: "https://www.visitusvi.com/" },
    { name: "Estate Whim Plantation Museum", pointType: "Tourist Attraction", city: "St. Croix", submarket: "St. Croix", latitude: 17.7012, longitude: -64.8234, sourceReference: "https://www.visitusvi.com/" },
    { name: "Cane Bay Beach Dive Corridor", pointType: "Beach / Waterfront", city: "St. Croix", submarket: "St. Croix", latitude: 17.7634, longitude: -64.7912, sourceReference: "https://www.visitusvi.com/" },
    { name: "Water Island Ferry Access", pointType: "Future Growth Node", city: "Water Island", submarket: "Other", latitude: 18.3189, longitude: -64.9567, sourceReference: "https://www.visitusvi.com/" },
    { name: "St. Thomas Skyride to Paradise Point", pointType: "Tourist Attraction", city: "Charlotte Amalie", submarket: "St. Thomas", latitude: 18.3389, longitude: -64.9389, sourceReference: "https://www.visitusvi.com/" },
    { name: "Bolongo Bay Beach Resort Area", pointType: "Beach / Waterfront", city: "St. Thomas", submarket: "St. Thomas", latitude: 18.3012, longitude: -64.8912, sourceReference: "https://www.visitusvi.com/" },
    { name: "Frenchtown Dining and Marina District", pointType: "Entertainment District", city: "Charlotte Amalie", submarket: "St. Thomas", latitude: 18.3334, longitude: -64.9412, sourceReference: "https://www.visitusvi.com/" },
    { name: "Renaissance St. Croix Convention Zone", pointType: "Convention Center", city: "Christiansted", submarket: "St. Croix", latitude: 17.7512, longitude: -64.7089, sourceReference: "https://www.visitusvi.com/" },
    { name: "Tutu Park Mall Commercial Hub", pointType: "Business District", city: "St. Thomas", submarket: "St. Thomas", latitude: 18.3489, longitude: -64.9612, sourceReference: "https://www.visitusvi.com/" },
    { name: "Hull Bay Surf and Fishing Village", pointType: "Beach / Waterfront", city: "St. Thomas", submarket: "St. Thomas", latitude: 18.3712, longitude: -64.9567, sourceReference: "https://www.visitusvi.com/" },
    { name: "Salt River Bay National Historical Park", pointType: "Tourist Attraction", city: "St. Croix", submarket: "St. Croix", latitude: 17.7789, longitude: -64.7612, sourceReference: "https://www.nps.gov/sari/" },
    { name: "Annaberg Plantation Ruins", pointType: "Tourist Attraction", city: "St. John", submarket: "St. John", latitude: 18.3612, longitude: -64.7289, sourceReference: "https://www.nps.gov/viis/" },
    { name: "St. Thomas Legislature and Government District", pointType: "Government / Civic Center", city: "Charlotte Amalie", submarket: "St. Thomas", latitude: 18.3434, longitude: -64.9289, sourceReference: "https://www.vilegis.gov/" },
    { name: "St. Croix Renaissance Park Growth Node", pointType: "Future Growth Node", city: "St. Croix", submarket: "St. Croix", latitude: 17.7189, longitude: -64.7489, sourceReference: "https://www.visitusvi.com/" },
  ],
  tiRecords: [
    { name: "Cyril E. King International Airport Access", pointType: "Highway Access", pointSubtype: "Airport Access", city: "St. Thomas", submarket: "St. Thomas", latitude: 18.3373, longitude: -64.9734, sourceReference: "https://www.viport.com/", notes: "Primary international gateway for St. Thomas cruise and resort demand." },
    { name: "Charlotte Amalie Cruise Port Access", pointType: "Port / Maritime", pointSubtype: "Cruise Terminal", city: "Charlotte Amalie", submarket: "St. Thomas", latitude: 18.3312, longitude: -64.9289, sourceReference: "https://www.visitusvi.com/", notes: "Havensight cruise terminal supporting day-call and pre/post-stay lodging.", useCaseTags: ["Cruise / Port", "Resort / Leisure"] },
    { name: "Red Hook Ferry Terminal Access", pointType: "Ferry Terminal", pointSubtype: "Inter-Island Ferry", city: "Red Hook", submarket: "St. Thomas", latitude: 18.3189, longitude: -64.8512, sourceReference: "https://www.visitusvi.com/", notes: "Ferry hub linking St. Thomas to St. John and BVI." },
    { name: "Henry E. Rohlsen International Airport Access", pointType: "Highway Access", pointSubtype: "Airport Access", city: "St. Croix", submarket: "St. Croix", latitude: 17.7019, longitude: -64.7986, sourceReference: "https://www.viport.com/", notes: "St. Croix international air gateway for south USVI demand." },
    { name: "Frederiksted Cruise Pier Access", pointType: "Port / Maritime", pointSubtype: "Cruise Terminal", city: "Frederiksted", submarket: "St. Croix", latitude: 17.7123, longitude: -64.8834, sourceReference: "https://www.visitusvi.com/", notes: "West St. Croix cruise berth for heritage and beach tourism.", useCaseTags: ["Cruise / Port"] },
    { name: "Cruz Bay Ferry Terminal Access", pointType: "Ferry Terminal", pointSubtype: "Inter-Island Ferry", city: "Cruz Bay", submarket: "St. John", latitude: 18.3312, longitude: -64.7934, sourceReference: "https://www.visitusvi.com/", notes: "St. John ferry landing for national park and villa demand." },
    { name: "Christiansted Waterfront Highway Access", pointType: "Highway Access", pointSubtype: "Historic Corridor", city: "Christiansted", submarket: "St. Croix", latitude: 17.7467, longitude: -64.7034, sourceReference: "https://www.visitusvi.com/", notes: "Historic waterfront road access for east St. Croix tourism." },
    { name: "Magens Bay Scenic Road Access", pointType: "Highway Access", pointSubtype: "Scenic Corridor", city: "St. Thomas", submarket: "St. Thomas", latitude: 18.3689, longitude: -64.9234, sourceReference: "https://www.visitusvi.com/", notes: "North shore scenic access to Magens Bay beach demand." },
  ],
  googleCorrections: {},
};
