/**
 * GDI Publication Trigger Monitor V1 — constants.
 * Campaign-level monitors for PUBLIC_DATA_CEILING list publication.
 * Does not lower Ready/Watch gates. No Apify. No broad SERP on every check.
 */

export const PUBLICATION_MONITOR_VERSION = "gdi_publication_monitor_v1";

export const MONITOR_STATUS = Object.freeze({
  ACTIVE: "ACTIVE",
  PAUSED: "PAUSED",
  TRIGGERED: "TRIGGERED",
  COMPLETED: "COMPLETED",
  EXPIRED: "EXPIRED",
});

/** Artifact / trigger types (Part 2). */
export const PUBLICATION_TRIGGER_TYPE = Object.freeze({
  PARTICIPANT_LIST_PUBLISHED: "PARTICIPANT_LIST_PUBLISHED",
  EXHIBITOR_LIST_PUBLISHED: "EXHIBITOR_LIST_PUBLISHED",
  SPONSOR_LIST_PUBLISHED: "SPONSOR_LIST_PUBLISHED",
  SPEAKER_LIST_PUBLISHED: "SPEAKER_LIST_PUBLISHED",
  ACCEPTED_PAPERS_PUBLISHED: "ACCEPTED_PAPERS_PUBLISHED",
  PROGRAMME_PUBLISHED: "PROGRAMME_PUBLISHED",
  DELEGATION_LIST_PUBLISHED: "DELEGATION_LIST_PUBLISHED",
  EXHIBITOR_MANUAL_PUBLISHED: "EXHIBITOR_MANUAL_PUBLISHED",
  LODGING_PAGE_PUBLISHED: "LODGING_PAGE_PUBLISHED",
  HOTEL_LIST_PUBLISHED: "HOTEL_LIST_PUBLISHED",
  HOUSING_VENDOR_NAMED: "HOUSING_VENDOR_NAMED",
  REGISTRATION_OPENED: "REGISTRATION_OPENED",
  PCO_NAMED: "PCO_NAMED",
  PROCUREMENT_RFP_PUBLISHED: "PROCUREMENT_RFP_PUBLISHED",
});

export const REDECOMPOSITION_STATUS = Object.freeze({
  IDLE: "IDLE",
  QUEUED: "QUEUED",
  RUNNING: "RUNNING",
  COMPLETED: "COMPLETED",
  SKIPPED_NO_NEW_EVIDENCE: "SKIPPED_NO_NEW_EVIDENCE",
  FAILED: "FAILED",
});

export const CURRENT_SOURCE_STATE = Object.freeze({
  LIST_NOT_YET_PUBLISHED: "LIST_NOT_YET_PUBLISHED",
  LIST_PARTIAL: "LIST_PARTIAL",
  LIST_AVAILABLE: "LIST_AVAILABLE",
  LIST_PRIVATE: "LIST_PRIVATE",
  SOURCE_UNREACHABLE: "SOURCE_UNREACHABLE",
  SOURCE_MOVED: "SOURCE_MOVED",
  UNCHANGED: "UNCHANGED",
});

export const CHANGE_CLASS = Object.freeze({
  NONE: "NONE",
  TRIVIAL: "TRIVIAL",
  MEANINGFUL: "MEANINGFUL",
  ARTIFACT_PUBLISHED: "ARTIFACT_PUBLISHED",
});

/** Customer-safe labels for Watch cards (no crawler jargon). */
export const CUSTOMER_MONITORING_LABEL = Object.freeze({
  [PUBLICATION_TRIGGER_TYPE.EXHIBITOR_LIST_PUBLISHED]: "Exhibitor list",
  [PUBLICATION_TRIGGER_TYPE.SPEAKER_LIST_PUBLISHED]: "Speaker programme",
  [PUBLICATION_TRIGGER_TYPE.PROGRAMME_PUBLISHED]: "Programme",
  [PUBLICATION_TRIGGER_TYPE.PARTICIPANT_LIST_PUBLISHED]: "Participant list",
  [PUBLICATION_TRIGGER_TYPE.ACCEPTED_PAPERS_PUBLISHED]: "Accepted papers",
  [PUBLICATION_TRIGGER_TYPE.DELEGATION_LIST_PUBLISHED]: "Delegation list",
  [PUBLICATION_TRIGGER_TYPE.SPONSOR_LIST_PUBLISHED]: "Sponsor list",
  [PUBLICATION_TRIGGER_TYPE.EXHIBITOR_MANUAL_PUBLISHED]: "Exhibitor manual",
  [PUBLICATION_TRIGGER_TYPE.LODGING_PAGE_PUBLISHED]: "Accommodation guidance",
  [PUBLICATION_TRIGGER_TYPE.HOTEL_LIST_PUBLISHED]: "Hotel list",
  [PUBLICATION_TRIGGER_TYPE.HOUSING_VENDOR_NAMED]: "Housing vendor",
  [PUBLICATION_TRIGGER_TYPE.REGISTRATION_OPENED]: "Registration",
  [PUBLICATION_TRIGGER_TYPE.PCO_NAMED]: "Conference organizer",
  [PUBLICATION_TRIGGER_TYPE.PROCUREMENT_RFP_PUBLISHED]: "Procurement / RFP",
});

export const CHECK_FREQUENCY = Object.freeze({
  LOW: "LOW", // far from window
  MEDIUM: "MEDIUM",
  HIGH: "HIGH", // inside publication window
  GRACE: "GRACE", // after expected date
});

export const FREQUENCY_DAYS = Object.freeze({
  LOW: 21,
  MEDIUM: 7,
  HIGH: 3,
  GRACE: 7,
});

export function isValidMonitorStatus(s) {
  return Object.values(MONITOR_STATUS).includes(s);
}

export function isValidPublicationTriggerType(t) {
  return Object.values(PUBLICATION_TRIGGER_TYPE).includes(t);
}
