/**
 * Ownership research strategy — shared contracts (country-extensible).
 * Brazil V1 is the first concrete strategy; others plug in via resolveOwnershipResearchStrategy.
 */

/** @typedef {'CURRENT_IDENTITY'|'HISTORICAL_IDENTITY'|'REBRANDED_PROPERTY'|'RENAMED_PROPERTY'|'CLOSED_PROPERTY'|'DEMOLISHED_OR_REDEVELOPED'|'IDENTITY_UNCERTAIN'} PropertyLineageState */

/** @typedef {'PROPERTY_OWNER'|'OWNER_SPV'|'REAL_ESTATE_FUND'|'CONDO_OR_FRACTIONAL_OWNERSHIP'|'OPERATING_ENTITY'|'HOTEL_OPERATOR'|'MANAGEMENT_COMPANY'|'BRAND_FRANCHISOR'|'DEVELOPER'|'INVESTOR'|'LENDER'|'HISTORICAL_OWNER'|'HISTORICAL_OPERATOR'|'UNKNOWN_ROLE'} EntityCandidateRole */

/** @typedef {'SUPPORTED_CURRENT_PROPERTY_OWNER'|'SUPPORTED_CURRENT_OWNER_SPV'|'SUPPORTED_REAL_ESTATE_FUND'|'SUPPORTED_CURRENT_OPERATING_ENTITY'|'SUPPORTED_CURRENT_OPERATOR'|'SUPPORTED_CURRENT_DEVELOPER'|'SUPPORTED_HISTORICAL_OWNER'|'SUPPORTED_HISTORICAL_OPERATOR'|'STRONG_OWNER_CANDIDATE_NEEDS_PROPERTY_CONFIRMATION'|'LEGAL_ENTITY_IDENTIFIED_OWNER_UNCONFIRMED'|'CONFLICTING_EVIDENCE'|'PROPERTY_LINEAGE_REQUIRES_REVIEW'|'UNRESOLVED'} OwnershipConclusionState */

export const PROPERTY_LINEAGE_STATE = Object.freeze({
  CURRENT_IDENTITY: "CURRENT_IDENTITY",
  HISTORICAL_IDENTITY: "HISTORICAL_IDENTITY",
  REBRANDED_PROPERTY: "REBRANDED_PROPERTY",
  RENAMED_PROPERTY: "RENAMED_PROPERTY",
  CLOSED_PROPERTY: "CLOSED_PROPERTY",
  DEMOLISHED_OR_REDEVELOPED: "DEMOLISHED_OR_REDEVELOPED",
  IDENTITY_UNCERTAIN: "IDENTITY_UNCERTAIN",
});

export const ENTITY_CANDIDATE_ROLE = Object.freeze({
  PROPERTY_OWNER: "PROPERTY_OWNER",
  OWNER_SPV: "OWNER_SPV",
  REAL_ESTATE_FUND: "REAL_ESTATE_FUND",
  CONDO_OR_FRACTIONAL_OWNERSHIP: "CONDO_OR_FRACTIONAL_OWNERSHIP",
  OPERATING_ENTITY: "OPERATING_ENTITY",
  HOTEL_OPERATOR: "HOTEL_OPERATOR",
  MANAGEMENT_COMPANY: "MANAGEMENT_COMPANY",
  BRAND_FRANCHISOR: "BRAND_FRANCHISOR",
  DEVELOPER: "DEVELOPER",
  INVESTOR: "INVESTOR",
  LENDER: "LENDER",
  HISTORICAL_OWNER: "HISTORICAL_OWNER",
  HISTORICAL_OPERATOR: "HISTORICAL_OPERATOR",
  UNKNOWN_ROLE: "UNKNOWN_ROLE",
});

export const OWNERSHIP_CONCLUSION_STATE = Object.freeze({
  SUPPORTED_CURRENT_PROPERTY_OWNER: "SUPPORTED_CURRENT_PROPERTY_OWNER",
  SUPPORTED_CURRENT_OWNER_SPV: "SUPPORTED_CURRENT_OWNER_SPV",
  SUPPORTED_REAL_ESTATE_FUND: "SUPPORTED_REAL_ESTATE_FUND",
  /** Research staging: FII/ticker lead without titled ownership proof. */
  SUPPORTED_REAL_ESTATE_FUND_LEAD: "SUPPORTED_REAL_ESTATE_FUND_LEAD",
  SUPPORTED_CURRENT_OPERATING_ENTITY: "SUPPORTED_CURRENT_OPERATING_ENTITY",
  SUPPORTED_CURRENT_OPERATOR: "SUPPORTED_CURRENT_OPERATOR",
  SUPPORTED_CURRENT_DEVELOPER: "SUPPORTED_CURRENT_DEVELOPER",
  SUPPORTED_HISTORICAL_OWNER: "SUPPORTED_HISTORICAL_OWNER",
  SUPPORTED_HISTORICAL_OPERATING_ENTITY: "SUPPORTED_HISTORICAL_OPERATING_ENTITY",
  SUPPORTED_HISTORICAL_OPERATOR: "SUPPORTED_HISTORICAL_OPERATOR",
  STRONG_OWNER_CANDIDATE_NEEDS_PROPERTY_CONFIRMATION:
    "STRONG_OWNER_CANDIDATE_NEEDS_PROPERTY_CONFIRMATION",
  STRONG_PROPERTY_OWNER_CANDIDATE_NEEDS_CONFIRMATION:
    "STRONG_PROPERTY_OWNER_CANDIDATE_NEEDS_CONFIRMATION",
  LEGAL_ENTITY_IDENTIFIED_OWNER_UNCONFIRMED: "LEGAL_ENTITY_IDENTIFIED_OWNER_UNCONFIRMED",
  LEGAL_ENTITY_AMBIGUOUS: "LEGAL_ENTITY_AMBIGUOUS",
  CONFLICTING_EVIDENCE: "CONFLICTING_EVIDENCE",
  PROPERTY_LINEAGE_REQUIRES_REVIEW: "PROPERTY_LINEAGE_REQUIRES_REVIEW",
  UNRESOLVED: "UNRESOLVED",
});

/**
 * Conceptual source taxonomy (numeric tiers remain for ranking compatibility).
 * PRIMARY/REGULATORY = gov/CVM/Receita
 * STRONG_REGISTRY_DERIVED = trusted commercial CNPJ mirrors (econodata, cnpj.biz, …)
 * CORROBORATING = press / LinkedIn / secondary
 * LOW_VALUE_TRAVEL = OTA / Google Travel / directories
 *
 * Operationally, STRONG_REGISTRY_DERIVED is ranked with Tier 1 for ownership scrape
 * priority (live canary: econodata/cnpj.biz are actionable), but they are not
 * primary regulatory filings.
 */
export const SOURCE_CLASS = Object.freeze({
  PRIMARY_REGULATORY: "PRIMARY_REGULATORY",
  STRONG_REGISTRY_DERIVED: "STRONG_REGISTRY_DERIVED",
  OFFICIAL_LEGAL_OR_PRIVACY: "OFFICIAL_LEGAL_OR_PRIVACY",
  FII_OR_INVESTOR: "FII_OR_INVESTOR",
  CORROBORATING: "CORROBORATING",
  LOW_VALUE_TRAVEL: "LOW_VALUE_TRAVEL",
  SYNTHETIC_OR_TEST: "SYNTHETIC_OR_TEST",
  UNKNOWN: "UNKNOWN",
});

export const PROPERTY_ENTITY_MATCH = Object.freeze({
  EXACT_PROPERTY_MATCH: "EXACT_PROPERTY_MATCH",
  STRONG_PROPERTY_MATCH: "STRONG_PROPERTY_MATCH",
  PARTIAL_MATCH: "PARTIAL_MATCH",
  NAME_ONLY_MATCH: "NAME_ONLY_MATCH",
  CONFLICTING_LOCATION: "CONFLICTING_LOCATION",
  WRONG_PROPERTY: "WRONG_PROPERTY",
  UNKNOWN: "UNKNOWN",
});

export const RESEARCH_GOAL_KIND = Object.freeze({
  LEGAL_ENTITY: "LEGAL_ENTITY",
  PROPERTY_OWNER: "PROPERTY_OWNER",
  PRINCIPALS: "PRINCIPALS",
  PROPERTY_LINEAGE: "PROPERTY_LINEAGE",
  PHYSICAL_IDENTITY: "PHYSICAL_IDENTITY",
  FII_INVESTMENT: "FII_INVESTMENT",
});

export const SOURCE_TIER = Object.freeze({
  TIER_1_PRIMARY_REGULATORY: 1,
  TIER_2_STRONG_CORPORATE: 2,
  TIER_3_CORROBORATING: 3,
  TIER_4_WEAK: 4,
});

/** Roles that must NEVER auto-map to PROPERTY_OWNER without independent ownership evidence. */
export const NON_OWNER_WITHOUT_INDEPENDENT_EVIDENCE = Object.freeze([
  ENTITY_CANDIDATE_ROLE.OPERATING_ENTITY,
  ENTITY_CANDIDATE_ROLE.HOTEL_OPERATOR,
  ENTITY_CANDIDATE_ROLE.MANAGEMENT_COMPANY,
  ENTITY_CANDIDATE_ROLE.BRAND_FRANCHISOR,
]);

export const RESEARCH_PROGRESS_KEYS = Object.freeze([
  "current_property_identity_resolved",
  "historical_lineage_resolved",
  "legal_entity_resolved",
  "operating_entity_resolved",
  "property_owner_resolved",
  "principal_identified",
  "owner_domain_identified",
  "decision_maker_identified",
  "contact_identified",
]);

export const STRATEGY_VERSION = "ownership-research-strategy-v1";
