/**
 * Contact Intelligence V1 — vocabulary (canonical enums).
 * Dimensions stay separate; never collapse into one score.
 */

export const CONTACT_INTELLIGENCE_VERSION = "contact-intelligence-v1";

/** How a channel is bound to a person / org / property. */
export const ATTRIBUTION = Object.freeze({
  OFFICIAL: "OFFICIAL",
  NAMED_PERSON: "NAMED_PERSON",
  ROLE_MAILBOX: "ROLE_MAILBOX",
  ORGANIZATION: "ORGANIZATION",
  PROPERTY: "PROPERTY",
  INFERRED: "INFERRED",
  UNATTRIBUTED: "UNATTRIBUTED",
});

/** Operational likelihood the channel works — not attribution. */
export const DELIVERABILITY = Object.freeze({
  HIGH: "HIGH",
  MEDIUM: "MEDIUM",
  LOW: "LOW",
  UNKNOWN: "UNKNOWN",
});

/** Whether a person's role/title is still current. */
export const ROLE_CURRENCY = Object.freeze({
  CURRENT: "CURRENT",
  STALE: "STALE",
  UNKNOWN: "UNKNOWN",
});

/** Why this contact matters for the focus hotel. */
export const PROPERTY_RELEVANCE = Object.freeze({
  PROPERTY_DIRECT: "PROPERTY_DIRECT",
  OWNER_ORG: "OWNER_ORG",
  OPERATOR: "OPERATOR",
  PORTFOLIO_REUSED: "PORTFOLIO_REUSED",
  BRAND_NETWORK: "BRAND_NETWORK",
  UNRELATED: "UNRELATED",
});

export const FRESHNESS = Object.freeze({
  FRESH: "FRESH",
  AGING: "AGING",
  STALE: "STALE",
  UNKNOWN: "UNKNOWN",
});

export const USAGE_RIGHTS = Object.freeze({
  PUBLIC_SAFE: "PUBLIC_SAFE",
  INTERNAL_ONLY: "INTERNAL_ONLY",
  RESTRICTED: "RESTRICTED",
});

export const CHANNEL_KIND = Object.freeze({
  HOTEL_PHONE: "HOTEL_PHONE",
  HOTEL_EMAIL: "HOTEL_EMAIL",
  HOTEL_WEBSITE: "HOTEL_WEBSITE",
  ORG_PHONE: "ORG_PHONE",
  ORG_EMAIL: "ORG_EMAIL",
  ORG_WEBSITE: "ORG_WEBSITE",
  CONTACT_FORM: "CONTACT_FORM",
  PERSON_EMAIL: "PERSON_EMAIL",
  PERSON_PHONE: "PERSON_PHONE",
  PERSON_LINKEDIN: "PERSON_LINKEDIN",
  ROLE_MAILBOX: "ROLE_MAILBOX",
  SWITCHBOARD: "SWITCHBOARD",
});

export const CONTACT_SUBJECT_KIND = Object.freeze({
  HOTEL: "HOTEL",
  ORGANIZATION: "ORGANIZATION",
  PERSON: "PERSON",
});

export const UNRESOLVED_REASON = Object.freeze({
  OWNER_UNRESOLVED: "OWNER_UNRESOLVED",
  NO_HOTEL_CONTACT: "NO_HOTEL_CONTACT",
  NO_ORG_ROUTE: "NO_ORG_ROUTE",
  NO_PERSON_EVIDENCE: "NO_PERSON_EVIDENCE",
  PERSON_ROLE_STALE: "PERSON_ROLE_STALE",
  CHANNEL_INFERRED_ONLY: "CHANNEL_INFERRED_ONLY",
  USAGE_RESTRICTED: "USAGE_RESTRICTED",
  REFRESH_REQUIRED: "REFRESH_REQUIRED",
  EVIDENCE_CONFLICT: "EVIDENCE_CONFLICT",
  PAID_ENRICHMENT_DISABLED: "PAID_ENRICHMENT_DISABLED",
});

export const REFRESH_STATUS = Object.freeze({
  NEVER: "NEVER",
  QUEUED: "QUEUED",
  RUNNING: "RUNNING",
  COMPLETE: "COMPLETE",
  PARTIAL: "PARTIAL",
  FAILED: "FAILED",
  STALE: "STALE",
});

export const CONTACT_WRITE_GUARANTEES = Object.freeze({
  owner_name_auto_writes: 0,
  census_owner_mutations: 0,
  airtable_ownership_writes: 0,
  paid_enrichment_default: 0,
  webhound_calls_default: 0,
  inferred_labeled_as_official: 0,
  switchboard_labeled_as_direct_personal: 0,
  outreach_sent: 0,
  production_auto_writes: 0,
});

/**
 * Explicit verification taxonomy.
 * Critical: INFERRED ≠ VERIFIED. Pattern-supported ≠ mailbox-verified.
 */
export const VERIFICATION_STATUS = Object.freeze({
  VERIFIED_OFFICIAL: "VERIFIED_OFFICIAL",
  VERIFIED_PUBLIC: "VERIFIED_PUBLIC",
  VERIFIED_MAILBOX: "VERIFIED_MAILBOX",
  DOMAIN_PATTERN_SUPPORTED: "DOMAIN_PATTERN_SUPPORTED",
  PUBLICLY_PUBLISHED: "PUBLICLY_PUBLISHED",
  CATCH_ALL_PROBABLE: "CATCH_ALL_PROBABLE",
  PROBABLE: "PROBABLE",
  INFERRED: "INFERRED",
  STALE: "STALE",
  INVALID: "INVALID",
  UNRESOLVED: "UNRESOLVED",
});

/** Granular contact types — do not collapse phones/emails into one field. */
export const CONTACT_TYPE = Object.freeze({
  HOTEL_MAIN_PHONE: "HOTEL_MAIN_PHONE",
  HOTEL_RESERVATIONS_PHONE: "HOTEL_RESERVATIONS_PHONE",
  HOTEL_SALES_PHONE: "HOTEL_SALES_PHONE",
  HOTEL_GENERAL_EMAIL: "HOTEL_GENERAL_EMAIL",
  HOTEL_RESERVATIONS_EMAIL: "HOTEL_RESERVATIONS_EMAIL",
  HOTEL_SALES_EMAIL: "HOTEL_SALES_EMAIL",
  HOTEL_WEBSITE: "HOTEL_WEBSITE",
  HOTEL_CONTACT_PAGE: "HOTEL_CONTACT_PAGE",
  ORG_MAIN_PHONE: "ORG_MAIN_PHONE",
  ORG_DEVELOPMENT_PHONE: "ORG_DEVELOPMENT_PHONE",
  ORG_GENERAL_EMAIL: "ORG_GENERAL_EMAIL",
  ORG_DEVELOPMENT_EMAIL: "ORG_DEVELOPMENT_EMAIL",
  ORG_CONTACT_PAGE: "ORG_CONTACT_PAGE",
  ORG_WEBSITE: "ORG_WEBSITE",
  PERSON_BUSINESS_EMAIL: "PERSON_BUSINESS_EMAIL",
  PERSON_DIRECT_BUSINESS_PHONE: "PERSON_DIRECT_BUSINESS_PHONE",
  PERSON_CORPORATE_PHONE: "PERSON_CORPORATE_PHONE",
  PERSON_PROFILE_URL: "PERSON_PROFILE_URL",
  PERSON_LINKEDIN_URL: "PERSON_LINKEDIN_URL",
});

/** Owner / development role categories (relevance ranking). */
export const ROLE_CATEGORY = Object.freeze({
  OWNER_PRINCIPAL: "OWNER_PRINCIPAL",
  CHAIRMAN_CEO: "CHAIRMAN_CEO",
  DEVELOPMENT_EXECUTIVE: "DEVELOPMENT_EXECUTIVE",
  ACQUISITIONS_EXECUTIVE: "ACQUISITIONS_EXECUTIVE",
  INVESTMENT_EXECUTIVE: "INVESTMENT_EXECUTIVE",
  ASSET_MANAGEMENT_EXECUTIVE: "ASSET_MANAGEMENT_EXECUTIVE",
  PORTFOLIO_EXECUTIVE: "PORTFOLIO_EXECUTIVE",
  REAL_ESTATE_EXECUTIVE: "REAL_ESTATE_EXECUTIVE",
  OWNER_RELATIONS: "OWNER_RELATIONS",
  DEVELOPMENT_CONTACT: "DEVELOPMENT_CONTACT",
  OPERATOR_SIDE: "OPERATOR_SIDE",
  OTHER: "OTHER",
});

export const RELEVANCE_RANK = Object.freeze({
  PRIMARY_CONTACT: "PRIMARY_CONTACT",
  SECONDARY_CONTACT: "SECONDARY_CONTACT",
  ORGANIZATION_FALLBACK: "ORGANIZATION_FALLBACK",
  REJECTED: "REJECTED",
});

export const NEGATIVE_SCREEN = Object.freeze({
  WRONG_PERSON: "WRONG_PERSON",
  SAME_NAME_COLLISION: "SAME_NAME_COLLISION",
  FORMER_EMPLOYEE_NOT_CURRENT: "FORMER_EMPLOYEE_NOT_CURRENT",
  WRONG_COMPANY: "WRONG_COMPANY",
  ADJACENT_COMPANY: "ADJACENT_COMPANY",
  OPERATOR_PERSON_NOT_OWNER_PERSON: "OPERATOR_PERSON_NOT_OWNER_PERSON",
  BRAND_PERSON_NOT_OWNER_PERSON: "BRAND_PERSON_NOT_OWNER_PERSON",
  PERSON_NOT_DECISION_RELEVANT: "PERSON_NOT_DECISION_RELEVANT",
  EMAIL_PATTERN_UNVERIFIED: "EMAIL_PATTERN_UNVERIFIED",
  CATCH_ALL_NOT_VERIFIED: "CATCH_ALL_NOT_VERIFIED",
  STALE_CONTACT: "STALE_CONTACT",
  PERSONAL_EMAIL_NOT_BUSINESS_CONTACT: "PERSONAL_EMAIL_NOT_BUSINESS_CONTACT",
  PERSONAL_PHONE_NOT_PUBLIC_BUSINESS_CONTACT: "PERSONAL_PHONE_NOT_PUBLIC_BUSINESS_CONTACT",
  SEARCH_SNIPPET_NOT_DECISIVE_EVIDENCE: "SEARCH_SNIPPET_NOT_DECISIVE_EVIDENCE",
});

/** Provider-neutral waterfall levels — stop when quality threshold met. */
export const WATERFALL_LEVEL = Object.freeze({
  L0_EXISTING_EVIDENCE: "L0_EXISTING_EVIDENCE",
  L1_OFFICIAL_SOURCE: "L1_OFFICIAL_SOURCE",
  L2_NATIVE_PUBLIC_WEB: "L2_NATIVE_PUBLIC_WEB",
  L3_DOMAIN_PUBLIC_HARVEST: "L3_DOMAIN_PUBLIC_HARVEST",
  L4_PATTERN_CANDIDATES: "L4_PATTERN_CANDIDATES",
  L5_EMAIL_VERIFICATION: "L5_EMAIL_VERIFICATION",
  L6_EXTERNAL_PROVIDER: "L6_EXTERNAL_PROVIDER",
  L7_MANUAL_EXCEPTION: "L7_MANUAL_EXCEPTION",
});

export const CONFIDENCE_BAND = Object.freeze({
  HIGH: "HIGH",
  MODERATE: "MODERATE",
  LOW: "LOW",
  UNKNOWN: "UNKNOWN",
});

export const PROVIDER_ID = Object.freeze({
  NATIVE_WEB: "native_web",
  PARALLEL_RESEARCH: "parallel_research",
  CONTEXT_DEV: "context_dev",
  SURFE: "surfe",
  PDL: "pdl",
  FUTURE_APOLLO: "future_apollo",
  FUTURE_HUNTER: "future_hunter",
  FUTURE_PROSPEO: "future_prospeo",
  FUTURE_FULLENRICH: "future_fullenrich",
  FUTURE_PDL: "future_pdl",
  FUTURE_ROCKETREACH: "future_rocketreach",
  FUTURE_SURFE: "future_surfe",
});
