/**
 * GDI Private Events + Wedding Demand V1 — constants.
 * No hotel-, city-, or venue-name hardcodes in production logic.
 */

export const PRIVATE_EVENTS_V1 = "gdi_private_events_v1";

export const VENUE_TYPE = Object.freeze({
  WEDDING_VENUE: "WEDDING_VENUE",
  EVENT_VENUE: "EVENT_VENUE",
  COUNTRY_CLUB: "COUNTRY_CLUB",
  HISTORIC_ESTATE: "HISTORIC_ESTATE",
  MUSEUM: "MUSEUM",
  GARDEN: "GARDEN",
  WINERY: "WINERY",
  BANQUET_HALL: "BANQUET_HALL",
  RELIGIOUS_VENUE: "RELIGIOUS_VENUE",
  PRIVATE_CLUB: "PRIVATE_CLUB",
  CONFERENCE_EVENT_CENTER: "CONFERENCE_EVENT_CENTER",
  SOCIAL_EVENT_SPACE: "SOCIAL_EVENT_SPACE",
  RESORT_OFFSITE: "RESORT_OFFSITE",
  OTHER: "OTHER",
});

export const ON_SITE_LODGING_STATUS = Object.freeze({
  NO_LODGING: "NO_LODGING",
  LIMITED_LODGING: "LIMITED_LODGING",
  ADEQUATE_LODGING: "ADEQUATE_LODGING",
  UNKNOWN: "UNKNOWN",
});

export const VENUE_PRIORITY = Object.freeze({
  HIGH_POTENTIAL_PARTNER: "HIGH_POTENTIAL_PARTNER",
  EVENT_SIGNAL_TARGET: "EVENT_SIGNAL_TARGET",
  WATCH: "WATCH",
  LOW_HOTEL_OPPORTUNITY: "LOW_HOTEL_OPPORTUNITY",
});

/**
 * Repeated private-event activity without requiring exact annual counts.
 * CONFIRMED_VOLUME / STRONG_REPEATED_ACTIVITY may support TRUE partnership.
 * MODERATE_ACTIVITY stays EVENT_SIGNAL_TARGET by default.
 */
export const EVENT_ACTIVITY_EVIDENCE_STATUS = Object.freeze({
  CONFIRMED_VOLUME: "CONFIRMED_VOLUME",
  STRONG_REPEATED_ACTIVITY: "STRONG_REPEATED_ACTIVITY",
  MODERATE_ACTIVITY: "MODERATE_ACTIVITY",
  LIMITED_ACTIVITY: "LIMITED_ACTIVITY",
  UNKNOWN: "UNKNOWN",
});

export const ACTIVITY_EVIDENCE_TYPE = Object.freeze({
  OFFICIAL_WEDDING_PAGE: "OFFICIAL_WEDDING_PAGE",
  OFFICIAL_PRIVATE_EVENT_PAGE: "OFFICIAL_PRIVATE_EVENT_PAGE",
  EVENT_PACKAGE: "EVENT_PACKAGE",
  EVENT_CALENDAR: "EVENT_CALENDAR",
  DATED_EVENT_POST: "DATED_EVENT_POST",
  PLANNER_REFERENCE: "PLANNER_REFERENCE",
  VENDOR_REFERENCE: "VENDOR_REFERENCE",
  TESTIMONIAL: "TESTIMONIAL",
  GALLERY: "GALLERY",
  EVENT_EXPO: "EVENT_EXPO",
  FUTURE_EVENT: "FUTURE_EVENT",
  PUBLIC_BOOKING_LANGUAGE: "PUBLIC_BOOKING_LANGUAGE",
  ANNUAL_VOLUME_STATEMENT: "ANNUAL_VOLUME_STATEMENT",
  OTHER: "OTHER",
});

/**
 * Public hotel-partner research outcome.
 * NO_PUBLIC_PARTNER_FOUND ≠ confirmed absence of all hotel relationships.
 */
export const PARTNER_STATUS = Object.freeze({
  EXCLUSIVE_PARTNER_FOUND: "EXCLUSIVE_PARTNER_FOUND",
  PREFERRED_PARTNER_FOUND: "PREFERRED_PARTNER_FOUND",
  NONEXCLUSIVE_PARTNERS_FOUND: "NONEXCLUSIVE_PARTNERS_FOUND",
  NO_PUBLIC_PARTNER_FOUND: "NO_PUBLIC_PARTNER_FOUND",
  UNKNOWN: "UNKNOWN",
});

export const PARTNERSHIP_CONFIDENCE = Object.freeze({
  HIGH: "HIGH",
  MODERATE: "MODERATE",
  LOW: "LOW",
});

export const BUYER_PATH = Object.freeze({
  NAMED_PLANNER: "NAMED_PLANNER",
  VENUE_EVENT_DIRECTOR: "VENUE_EVENT_DIRECTOR",
  VENUE_SALES: "VENUE_SALES",
  EVENT_TEAM: "EVENT_TEAM",
  EVENT_COMPANY: "EVENT_COMPANY",
  FUNCTIONAL_EVENT_CONTACT: "FUNCTIONAL_EVENT_CONTACT",
  ORGANIZATION_PATH: "ORGANIZATION_PATH",
  NO_BUYER_PATH: "NO_BUYER_PATH",
});

/** Buyer paths that satisfy commercial-path requirement for TRUE partnership. */
export const COMMERCIAL_BUYER_PATHS = Object.freeze([
  BUYER_PATH.NAMED_PLANNER,
  BUYER_PATH.VENUE_EVENT_DIRECTOR,
  BUYER_PATH.VENUE_SALES,
  BUYER_PATH.EVENT_TEAM,
  BUYER_PATH.EVENT_COMPANY,
  BUYER_PATH.FUNCTIONAL_EVENT_CONTACT,
  BUYER_PATH.ORGANIZATION_PATH,
]);

export const ATTENDANCE_STATUS = Object.freeze({
  CONFIRMED: "CONFIRMED",
  ESTIMATED: "ESTIMATED",
  UNKNOWN: "UNKNOWN",
});

export const ROOM_DEMAND_CLAIM = Object.freeze({
  CONFIRMED: "CONFIRMED",
  ESTIMATED: "ESTIMATED",
  MODELED: "MODELED",
  UNKNOWN: "UNKNOWN",
});

export const NONLOCALITY = Object.freeze({
  STRONG: "STRONG",
  MODERATE: "MODERATE",
  LOCAL_LIKELY: "LOCAL_LIKELY",
  UNKNOWN: "UNKNOWN",
});

export const HOTEL_ARCHETYPE_PE = Object.freeze({
  URBAN_FULL_SERVICE: "URBAN_FULL_SERVICE",
  SUBURBAN_FULL_SERVICE: "SUBURBAN_FULL_SERVICE",
  LUXURY_URBAN: "LUXURY_URBAN",
  RESORT_DESTINATION: "RESORT_DESTINATION",
  SELECT_SERVICE: "SELECT_SERVICE",
  BOUTIQUE: "BOUTIQUE",
});

/** Practical catchment miles by archetype — not city-specific. */
export const CATCHMENT_MILES_BY_ARCHETYPE = Object.freeze({
  [HOTEL_ARCHETYPE_PE.URBAN_FULL_SERVICE]: { core: 5, stretch: 12 },
  [HOTEL_ARCHETYPE_PE.SUBURBAN_FULL_SERVICE]: { core: 8, stretch: 18 },
  [HOTEL_ARCHETYPE_PE.LUXURY_URBAN]: { core: 6, stretch: 14 },
  [HOTEL_ARCHETYPE_PE.RESORT_DESTINATION]: { core: 25, stretch: 60 },
  [HOTEL_ARCHETYPE_PE.SELECT_SERVICE]: { core: 6, stretch: 14 },
  [HOTEL_ARCHETYPE_PE.BOUTIQUE]: { core: 8, stretch: 20 },
});

/** Preferred venue-type mix by archetype (discovery routing hints). */
export const ARCHETYPE_VENUE_MIX = Object.freeze({
  [HOTEL_ARCHETYPE_PE.URBAN_FULL_SERVICE]: [
    VENUE_TYPE.MUSEUM,
    VENUE_TYPE.PRIVATE_CLUB,
    VENUE_TYPE.SOCIAL_EVENT_SPACE,
    VENUE_TYPE.EVENT_VENUE,
    VENUE_TYPE.HISTORIC_ESTATE,
  ],
  [HOTEL_ARCHETYPE_PE.SUBURBAN_FULL_SERVICE]: [
    VENUE_TYPE.COUNTRY_CLUB,
    VENUE_TYPE.HISTORIC_ESTATE,
    VENUE_TYPE.RELIGIOUS_VENUE,
    VENUE_TYPE.GARDEN,
    VENUE_TYPE.BANQUET_HALL,
    VENUE_TYPE.WEDDING_VENUE,
  ],
  [HOTEL_ARCHETYPE_PE.LUXURY_URBAN]: [
    VENUE_TYPE.MUSEUM,
    VENUE_TYPE.PRIVATE_CLUB,
    VENUE_TYPE.HISTORIC_ESTATE,
    VENUE_TYPE.SOCIAL_EVENT_SPACE,
  ],
  [HOTEL_ARCHETYPE_PE.RESORT_DESTINATION]: [
    VENUE_TYPE.RESORT_OFFSITE,
    VENUE_TYPE.WEDDING_VENUE,
    VENUE_TYPE.WINERY,
    VENUE_TYPE.GARDEN,
    VENUE_TYPE.EVENT_VENUE,
  ],
  [HOTEL_ARCHETYPE_PE.SELECT_SERVICE]: [
    VENUE_TYPE.BANQUET_HALL,
    VENUE_TYPE.WEDDING_VENUE,
    VENUE_TYPE.EVENT_VENUE,
    VENUE_TYPE.RELIGIOUS_VENUE,
  ],
  [HOTEL_ARCHETYPE_PE.BOUTIQUE]: [
    VENUE_TYPE.HISTORIC_ESTATE,
    VENUE_TYPE.GARDEN,
    VENUE_TYPE.SOCIAL_EVENT_SPACE,
    VENUE_TYPE.WEDDING_VENUE,
  ],
});

export const SENSITIVE_PERSONAL_RE =
  /\b(?:bride|groom|couple'?s?\s+home|personal\s+address|ssn|date\s+of\s+birth|ethnicity|religion\s+of\s+the\s+couple|income)\b/i;
