/**
 * GDI International Discovery V2 — constants.
 * Ready / Watch thresholds unchanged. Evidence routes expand.
 */

export const IDV2_VERSION = "gdi_international_discovery_v2";

/** Five parallel discovery spines — converge to same packet. */
export const DISCOVERY_SPINE = Object.freeze({
  PARTICIPANT_FIRST: "PARTICIPANT_FIRST",
  DEMAND_CONTROLLER_FIRST: "DEMAND_CONTROLLER_FIRST",
  ACCOUNT_FIRST: "ACCOUNT_FIRST",
  HISTORICAL_PROCESS_FIRST: "HISTORICAL_PROCESS_FIRST",
  HOTEL_HISTORY_FIRST: "HOTEL_HISTORY_FIRST",
});

export const CONTROLLER_TYPE = Object.freeze({
  PCO: "PCO",
  DMC: "DMC",
  HOUSING_BUREAU: "HOUSING_BUREAU",
  ASSOCIATION_SECRETARIAT: "ASSOCIATION_SECRETARIAT",
  HOST_INSTITUTION: "HOST_INSTITUTION",
  CORPORATE_TRAVEL: "CORPORATE_TRAVEL",
  PROCUREMENT: "PROCUREMENT",
  EVENT_AGENCY: "EVENT_AGENCY",
  TRAVEL_MANAGEMENT_COMPANY: "TRAVEL_MANAGEMENT_COMPANY",
  CONVENTION_BUREAU: "CONVENTION_BUREAU",
  VENUE_CONGRESS_OFFICE: "VENUE_CONGRESS_OFFICE",
  SPORTS_TRAVEL: "SPORTS_TRAVEL",
  PRODUCTION_COORDINATOR: "PRODUCTION_COORDINATOR",
  REGISTRATION_VENDOR: "REGISTRATION_VENDOR",
  UNKNOWN: "UNKNOWN",
});

export const CONTROLLER_AUTHORITY = Object.freeze({
  CONFIRMED_LODGING_CONTROLLER: "CONFIRMED_LODGING_CONTROLLER",
  STRONG_SELECTION_INFLUENCE: "STRONG_SELECTION_INFLUENCE",
  PLAUSIBLE_CONTROLLER: "PLAUSIBLE_CONTROLLER",
  CONTACT_ONLY: "CONTACT_ONLY",
  UNCONFIRMED: "UNCONFIRMED",
});

export const HOTEL_SUPPLIED_EVIDENCE_TYPE = Object.freeze({
  PAST_CLIENT: "PAST_CLIENT",
  PAST_GROUP: "PAST_GROUP",
  LOST_GROUP: "LOST_GROUP",
  PAST_RFP: "PAST_RFP",
  CURRENT_RFP: "CURRENT_RFP",
  SALES_TARGET: "SALES_TARGET",
  ORGANIZER_RESPONSE: "ORGANIZER_RESPONSE",
  PCO_RESPONSE: "PCO_RESPONSE",
  RATE_REQUEST: "RATE_REQUEST",
  HOTEL_LIST_INVITATION: "HOTEL_LIST_INVITATION",
  ROOM_BLOCK_REQUEST: "ROOM_BLOCK_REQUEST",
  PROCUREMENT_INVITATION: "PROCUREMENT_INVITATION",
  OTHER: "OTHER",
});

export const PACKET_PILLAR_ID = Object.freeze({
  NAMED_ENTITY: "NAMED_ENTITY",
  GROUP_MOTION: "DEFINED_GROUP_MOTION",
  BUYER_OR_CONTROLLER: "BUYER_OR_DEMAND_CONTROLLER",
  FUTURE_DECISION: "FUTURE_DECISION_POINT",
  LODGING_EVIDENCE: "HOTEL_LODGING_EVIDENCE",
  HOTEL_FIT: "TARGET_HOTEL_FIT",
});

export const EVIDENCE_ROUTE = Object.freeze({
  OFFICIAL_PUBLIC: "OFFICIAL_PUBLIC",
  PCO_DMC: "PCO_DMC",
  HOUSING_PROVIDER: "HOUSING_PROVIDER",
  REGISTRATION_PORTAL: "REGISTRATION_PORTAL",
  PROCUREMENT_RFP: "PROCUREMENT_RFP",
  ORGANIZER_RESPONSE: "ORGANIZER_RESPONSE",
  HOTEL_SUPPLIED: "HOTEL_SUPPLIED",
  TRAVEL_PARTNER: "TRAVEL_PARTNER",
  EVENT_MANUAL: "EVENT_MANUAL",
  HISTORICAL_PROCESS: "HISTORICAL_PROCESS",
  UNKNOWN: "UNKNOWN",
});

/** Spine → typical 10 Bases mapping (non-exclusive). */
export const SPINE_BASE_MAP = Object.freeze({
  [DISCOVERY_SPINE.PARTICIPANT_FIRST]: [
    "PUBLISHED_EVENT_DECOMPOSITION",
    "PARTICIPANT_EXHIBITOR_SPONSOR_MINING",
    "INTERNATIONAL_ORG_RECURRING_GROUPS",
  ],
  [DISCOVERY_SPINE.DEMAND_CONTROLLER_FIRST]: [
    "PUBLISHED_EVENT_DECOMPOSITION",
    "INTERNATIONAL_ORG_RECURRING_GROUPS",
    "PHARMA_MEDICAL_ECOSYSTEM",
  ],
  [DISCOVERY_SPINE.ACCOUNT_FIRST]: [
    "RECURRING_CORPORATE_MEETINGS",
    "CORPORATE_TRIGGER_DEMAND",
    "PROJECT_WORKFORCE_DEMAND",
  ],
  [DISCOVERY_SPINE.HISTORICAL_PROCESS_FIRST]: [
    "HISTORIC_ROTATION_PREDICTION",
    "PUBLISHED_EVENT_DECOMPOSITION",
  ],
  [DISCOVERY_SPINE.HOTEL_HISTORY_FIRST]: ["HOTEL_HISTORY_LOOKALIKE", "RECURRING_CORPORATE_MEETINGS"],
});
