/**
 * Contact Resolution V2 — vocabulary extensions (owner-level).
 * Does not replace V1 vocabulary; layers strength / email / phone statuses.
 */

export const CONTACT_RESOLUTION_V2 = "contact-resolution-v2";

/** Customer/admin strength labels — never collapse into one opaque score. */
export const CONTACT_STRENGTH = Object.freeze({
  VERIFIED_DIRECT_CONTACT: "VERIFIED_DIRECT_CONTACT",
  VERIFIED_WORK_EMAIL: "VERIFIED_WORK_EMAIL",
  INFERRED_VERIFIED_EMAIL: "INFERRED_VERIFIED_EMAIL",
  EXECUTIVE_OFFICE: "EXECUTIVE_OFFICE",
  CORPORATE_CONTACT: "CORPORATE_CONTACT",
  GENERAL_CONTACT: "GENERAL_CONTACT",
});

export const EMAIL_STATUS = Object.freeze({
  EXPLICIT_VERIFIED: "EXPLICIT_VERIFIED",
  EXPLICIT_UNVERIFIED: "EXPLICIT_UNVERIFIED",
  INFERRED_VERIFIED: "INFERRED_VERIFIED",
  INFERRED_UNVERIFIED: "INFERRED_UNVERIFIED",
  REJECTED: "REJECTED",
  NOT_FOUND: "NOT_FOUND",
});

export const EMAIL_METHOD = Object.freeze({
  EXPLICIT_OFFICIAL: "EXPLICIT_OFFICIAL",
  EXPLICIT_THIRD_PARTY: "EXPLICIT_THIRD_PARTY",
  PATTERN_FROM_PEERS: "PATTERN_FROM_PEERS",
  PATTERN_GENERATED: "PATTERN_GENERATED",
  PAID_PROVIDER: "PAID_PROVIDER",
  NONE: "NONE",
});

export const PHONE_TYPE = Object.freeze({
  DIRECT_MOBILE: "DIRECT_MOBILE",
  DIRECT_OFFICE: "DIRECT_OFFICE",
  EXECUTIVE_OFFICE: "EXECUTIVE_OFFICE",
  CORPORATE_PHONE: "CORPORATE_PHONE",
  GENERAL_PHONE: "GENERAL_PHONE",
  HOTEL_PHONE: "HOTEL_PHONE",
  UNKNOWN: "UNKNOWN",
});

export const PHONE_METHOD = Object.freeze({
  EXPLICIT_OFFICIAL_PERSON: "EXPLICIT_OFFICIAL_PERSON",
  EXPLICIT_CREDIBLE_PERSON: "EXPLICIT_CREDIBLE_PERSON",
  EXECUTIVE_OFFICE_PAGE: "EXECUTIVE_OFFICE_PAGE",
  OWNER_ORG_CORPORATE: "OWNER_ORG_CORPORATE",
  REGISTRY_DIRECTORY: "REGISTRY_DIRECTORY",
  ASSOCIATION_PROFILE: "ASSOCIATION_PROFILE",
  SEARCH_RESULT: "SEARCH_RESULT",
  PAID_PROVIDER: "PAID_PROVIDER",
  NONE: "NONE",
});

export const SOURCE_CLASS = Object.freeze({
  OFFICIAL_OWNER_SITE: "OFFICIAL_OWNER_SITE",
  OFFICIAL_HOTEL_SITE: "OFFICIAL_HOTEL_SITE",
  BRAND_PRESS_RELEASE: "BRAND_PRESS_RELEASE",
  OWNER_PRESS_RELEASE: "OWNER_PRESS_RELEASE",
  TRANSACTION_ANNOUNCEMENT: "TRANSACTION_ANNOUNCEMENT",
  DEVELOPMENT_ANNOUNCEMENT: "DEVELOPMENT_ANNOUNCEMENT",
  FINANCING_ANNOUNCEMENT: "FINANCING_ANNOUNCEMENT",
  GOVERNMENT_REGISTRY: "GOVERNMENT_REGISTRY",
  COMPANY_REGISTRY: "COMPANY_REGISTRY",
  TOURISM_REGISTRY: "TOURISM_REGISTRY",
  CHAMBER_OF_COMMERCE: "CHAMBER_OF_COMMERCE",
  HOTEL_ASSOCIATION: "HOTEL_ASSOCIATION",
  CONFERENCE_SPEAKER: "CONFERENCE_SPEAKER",
  PDF_DOCUMENT: "PDF_DOCUMENT",
  NEWS_ARTICLE: "NEWS_ARTICLE",
  PUBLIC_PROFESSIONAL_PROFILE: "PUBLIC_PROFESSIONAL_PROFILE",
  GOOGLE_BUSINESS: "GOOGLE_BUSINESS",
  OTHER_PUBLIC_SOURCE: "OTHER_PUBLIC_SOURCE",
});

export const RESOLUTION_STATUS = Object.freeze({
  RESOLVED_DIRECT: "RESOLVED_DIRECT",
  RESOLVED_CORPORATE_ONLY: "RESOLVED_CORPORATE_ONLY",
  PARTIAL: "PARTIAL",
  UNRESOLVED: "UNRESOLVED",
  CACHED: "CACHED",
  BUDGET_EXHAUSTED: "BUDGET_EXHAUSTED",
  OWNER_MISSING: "OWNER_MISSING",
});

export const ROLE_TIER = Object.freeze({
  TIER_1: 1,
  TIER_2: 2,
  TIER_3: 3,
  EXCLUDED: 99,
});

/** Cache TTLs (ms). */
export const CACHE_TTL = Object.freeze({
  domain_ms: 365 * 24 * 60 * 60 * 1000,
  verified_email_ms: 180 * 24 * 60 * 60 * 1000,
  verified_phone_ms: 180 * 24 * 60 * 60 * 1000,
  negative_provider_ms: 14 * 24 * 60 * 60 * 1000,
  resolution_default_ms: 30 * 24 * 60 * 60 * 1000,
});
