/**
 * GDI Demand Generator Intelligence V1 — enums & constants.
 * Research intelligence layer; never customer-facing as raw generator cards.
 */

export const DG_SCHEMA_VERSION = "gdi_demand_generator_v1";

export const GENERATOR_ID_PREFIX = "dg_";
export const PROGRAM_ID_PREFIX = "dgp_";
export const FIT_ID_PREFIX = "hdgf_";
export const SIGNAL_ID_PREFIX = "dgs_";
export const SERIES_ID_PREFIX = "dgsr_";

export const ORGANIZATION_TYPE = Object.freeze({
  ASSOCIATION: "ASSOCIATION",
  GOVERNMENT_AGENCY: "GOVERNMENT_AGENCY",
  GOVERNMENT_CONTRACTOR: "GOVERNMENT_CONTRACTOR",
  CONSULTING_FIRM: "CONSULTING_FIRM",
  UNIVERSITY: "UNIVERSITY",
  HOSPITAL_HEALTH_SYSTEM: "HOSPITAL_HEALTH_SYSTEM",
  RESEARCH_INSTITUTION: "RESEARCH_INSTITUTION",
  LARGE_EMPLOYER: "LARGE_EMPLOYER",
  SPORTS_ORGANIZATION: "SPORTS_ORGANIZATION",
  CONFERENCE_PRODUCER: "CONFERENCE_PRODUCER",
  NONPROFIT: "NONPROFIT",
  PROFESSIONAL_BODY: "PROFESSIONAL_BODY",
  TRAINING_PROVIDER: "TRAINING_PROVIDER",
  PROJECT_HEAVY_COMPANY: "PROJECT_HEAVY_COMPANY",
  OTHER: "OTHER",
});

export const GENERATOR_STATUS = Object.freeze({
  DISCOVERED: "DISCOVERED",
  VERIFIED: "VERIFIED",
  ACTIVE_GENERATOR: "ACTIVE_GENERATOR",
  WATCH: "WATCH",
  LOW_RELEVANCE: "LOW_RELEVANCE",
  STALE: "STALE",
});

export const PROGRAM_TYPE = Object.freeze({
  ANNUAL_CONFERENCE: "ANNUAL_CONFERENCE",
  TRAINING_ACADEMY: "TRAINING_ACADEMY",
  REGIONAL_MEETING: "REGIONAL_MEETING",
  IMPLEMENTATION_PROGRAM: "IMPLEMENTATION_PROGRAM",
  SPORTS_TOURNAMENT_SERIES: "SPORTS_TOURNAMENT_SERIES",
  BOARD_CYCLE: "BOARD_CYCLE",
  UNIVERSITY_RESIDENTIAL: "UNIVERSITY_RESIDENTIAL",
  PROJECT_DEPLOYMENT: "PROJECT_DEPLOYMENT",
  CONSULTING_ENGAGEMENT_SERIES: "CONSULTING_ENGAGEMENT_SERIES",
  GOVERNMENT_PROGRAM: "GOVERNMENT_PROGRAM",
  CERTIFICATION_PROGRAM: "CERTIFICATION_PROGRAM",
  SYMPOSIUM: "SYMPOSIUM",
  OTHER: "OTHER",
});

export const RECURRENCE_STATUS = Object.freeze({
  RECURRING_CONFIRMED: "RECURRING_CONFIRMED",
  RECURRING_HISTORICAL: "RECURRING_HISTORICAL",
  POSSIBLE_RECURRING: "POSSIBLE_RECURRING",
  ONE_TIME: "ONE_TIME",
  UNKNOWN: "UNKNOWN",
});

export const GENERATOR_RELEVANCE_CLASS = Object.freeze({
  HIGH_VALUE_GENERATOR: "HIGH_VALUE_GENERATOR",
  MEDIUM_VALUE_GENERATOR: "MEDIUM_VALUE_GENERATOR",
  WATCH_GENERATOR: "WATCH_GENERATOR",
  LOW_VALUE_GENERATOR: "LOW_VALUE_GENERATOR",
});

export const GENERATOR_PRIORITY = Object.freeze({
  HIGH: "HIGH",
  MEDIUM: "MEDIUM",
  WATCH: "WATCH",
  LOW: "LOW",
});

export const SIGNAL_STATUS = Object.freeze({
  DISCOVERED: "DISCOVERED",
  QUALIFIED: "QUALIFIED",
  TRUE_ACTIONABLE: "TRUE_ACTIONABLE",
  WATCH: "WATCH",
  REJECTED: "REJECTED",
  PROMOTED: "PROMOTED",
});

export const TRIGGER_TYPE = Object.freeze({
  NEW_PROGRAM_CYCLE: "NEW_PROGRAM_CYCLE",
  REGISTRATION_OPENING: "REGISTRATION_OPENING",
  FUTURE_DATES_ANNOUNCED: "FUTURE_DATES_ANNOUNCED",
  VENUE_ANNOUNCED: "VENUE_ANNOUNCED",
  HOUSING_INFO_POSTED: "HOUSING_INFO_POSTED",
  TRAINING_SCHEDULE_RELEASED: "TRAINING_SCHEDULE_RELEASED",
  CONTRACT_AWARDED: "CONTRACT_AWARDED",
  PROJECT_MOBILIZATION: "PROJECT_MOBILIZATION",
  IMPLEMENTATION_START: "IMPLEMENTATION_START",
  OFFICE_OPENING: "OFFICE_OPENING",
  RELOCATION: "RELOCATION",
  FACILITY_LAUNCH: "FACILITY_LAUNCH",
  SPORTS_TOURNAMENT_DATES: "SPORTS_TOURNAMENT_DATES",
  BOARD_COMMITTEE_CALENDAR: "BOARD_COMMITTEE_CALENDAR",
  ACADEMIC_PROGRAM: "ACADEMIC_PROGRAM",
  CONFERENCE_CALENDAR_UPDATE: "CONFERENCE_CALENDAR_UPDATE",
  OTHER: "OTHER",
});

export const SOURCE_AUTHORITY = Object.freeze({
  OFFICIAL_ORG: "OFFICIAL_ORG",
  OFFICIAL_PROGRAM: "OFFICIAL_PROGRAM",
  GOVERNMENT: "GOVERNMENT",
  UNIVERSITY: "UNIVERSITY",
  TRADE_PRESS: "TRADE_PRESS",
  DIRECTORY: "DIRECTORY",
  OTHER: "OTHER",
});

/** Adaptive research cadence hints (days). Scheduler may override. */
export const RESEARCH_CADENCE_DAYS = Object.freeze({
  [GENERATOR_STATUS.ACTIVE_GENERATOR]: 7,
  [GENERATOR_STATUS.VERIFIED]: 30,
  [GENERATOR_STATUS.DISCOVERED]: 30,
  [GENERATOR_STATUS.WATCH]: 60,
  [GENERATOR_STATUS.LOW_RELEVANCE]: 90,
  [GENERATOR_STATUS.STALE]: 180,
});

export const DEMAND_GENERATORS_TABLE_NAME = "Demand Generators";
export const DEMAND_PROGRAMS_TABLE_NAME = "Demand Programs";
export const HOTEL_DEMAND_GENERATOR_FIT_TABLE_NAME = "Hotel Demand Generator Fit";
export const DEMAND_GENERATOR_SIGNALS_TABLE_NAME = "Demand Generator Signals";
