/**
 * Packet 2.5 — Intelligence Claim types + temporal / conflict enums.
 * Normalize only what Hotel Intelligence currently requires.
 */

export const CLAIM_ENGINE_VERSION = "ownership-claim-engine-v1";

export const CLAIM_TYPES = Object.freeze([
  "ENTITY_IS_OWNER_OF_PROPERTY",
  "ENTITY_CONTROLS_ENTITY",
  "ENTITY_OWNS_PERCENT_OF_ENTITY",
  "ENTITY_OPERATES_HOTEL",
  "ENTITY_MANAGES_HOTEL",
  "ENTITY_DEVELOPED_PROPERTY",
  "ENTITY_SPONSORED_PROJECT",
  "ENTITY_PARTICIPATES_IN_JV",
  "ENTITY_IS_PARENT_OF_ENTITY",
  "ENTITY_IS_SUBSIDIARY_OF_ENTITY",
  "ENTITY_LEASES_PROPERTY",
  "ENTITY_BRANDS_HOTEL",
  "HOTEL_CURRENT_BRAND",
  "HOTEL_FORMER_BRAND",
  "HOTEL_ANNOUNCED_BRAND",
  "ENTITY_ACQUIRED_ENTITY_OR_ASSET",
  "ENTITY_SOLD_ENTITY_OR_ASSET",
  "ENTITY_FINANCED_PROPERTY",
  "ENTITY_IS_BORROWER",
  "ENTITY_HOLDS_TITLE",
  "PERSON_HAS_TITLE",
  "PERSON_REPRESENTS_ORGANIZATION",
  "PERSON_HAS_SIGNING_AUTHORITY",
  "PROPERTY_HAS_ROOM_COUNT",
  "PROPERTY_OPENED_ON_DATE",
  "PROPERTY_WAS_RENAMED",
  "PROPERTY_WAS_REBRANDED",
  "PROPERTY_IS_ADJACENT_TO",
  "PROPERTY_ALIAS",
  "OTHER_STRUCTURED_CLAIM",
]);

/** Critical for evaluation / promotion safety. */
export const CRITICAL_CLAIM_TYPES = Object.freeze([
  "ENTITY_IS_OWNER_OF_PROPERTY",
  "ENTITY_OWNS_PERCENT_OF_ENTITY",
  "ENTITY_OPERATES_HOTEL",
  "ENTITY_HOLDS_TITLE",
  "ENTITY_PARTICIPATES_IN_JV",
  "ENTITY_CONTROLS_ENTITY",
  "ENTITY_IS_PARENT_OF_ENTITY",
  "ENTITY_IS_SUBSIDIARY_OF_ENTITY",
  "HOTEL_CURRENT_BRAND",
  "HOTEL_FORMER_BRAND",
  "HOTEL_ANNOUNCED_BRAND",
  "PROPERTY_IS_ADJACENT_TO",
  "PROPERTY_ALIAS",
]);

export const CLAIM_IMPORTANCE = Object.freeze([
  "CRITICAL",
  "IMPORTANT",
  "ENRICHMENT",
]);

export const TEMPORAL_STATUSES = Object.freeze([
  "CURRENT",
  "FORMER",
  "ANNOUNCED",
  "PLANNED",
  "CONTESTED",
  "CANCELLED",
  "UNKNOWN",
  "CURRENT_UNVERIFIED",
]);

export const CLAIM_VERIFICATION_STATUSES = Object.freeze([
  "EXTRACTED",
  "ENTITY_RESOLVED",
  "VALIDATED",
  "CANDIDATE",
  "PROMOTED",
  "REJECTED",
  "NEEDS_REVIEW",
]);

export const CONTRADICTION_STATUSES = Object.freeze([
  "NONE",
  "CONFIRMED",
  "SUPERSEDED",
  "CONTRADICTED",
  "UNRESOLVED_CONFLICT",
]);

export const ENTITY_SCOPES = Object.freeze([
  "PROPERTY_SPECIFIC",
  "MULTI_PROPERTY",
  "PORTFOLIO_LEVEL",
  "ORGANIZATION_LEVEL",
  "FUND_LEVEL",
  "TRUST_LEVEL",
  "UNKNOWN_SCOPE",
]);

export const ALIAS_TYPES = Object.freeze([
  "LEGAL_NAME",
  "TRADE_NAME",
  "ABBREVIATION",
  "FORMER_NAME",
  "FORMER_BRAND_IDENTITY",
  "PROJECT_NAME",
  "DEVELOPMENT_NAME",
  "LOCAL_NAME",
  "TICKER_ALIAS",
  "DOMAIN_NAME",
  "OTHER",
]);

export const PROMOTION_STATUSES = Object.freeze([
  "observation",
  "candidate",
  "needs_review",
  "promoted",
  "rejected",
  "superseded",
]);

export const INTELLIGENCE_EVENT_TYPES = Object.freeze([
  "ACQUISITION",
  "SALE",
  "OWNERSHIP_CHANGE",
  "BRAND_CHANGE",
  "OPENING",
  "DEVELOPMENT",
  "JV_FORMATION",
  "FINANCING",
  "RENOVATION",
]);

export const EXTRACTION_ERROR_CODES = Object.freeze([
  "MISSED_ENTITY",
  "WRONG_ENTITY",
  "MISSED_RELATION",
  "WRONG_RELATION",
  "WRONG_HOTEL_CONTEXT",
  "WRONG_PERCENTAGE",
  "WRONG_DATE",
  "WRONG_TEMPORAL_STATUS",
  "WRONG_ROLE",
  "OVERINFERENCE",
  "UNDERINFERENCE",
  "DUPLICATE_CLAIM",
  "OTHER",
]);

export const ENTITY_RESOLUTION_ERROR_CODES = Object.freeze([
  "FALSE_MERGE",
  "FALSE_SPLIT",
  "ALIAS_MISSED",
  "WRONG_HOTEL",
  "WRONG_PARENT",
  "PROPCO_PARENT_CONFUSION",
  "ADJACENT_PROPERTY",
  "SIMILAR_NAME_COLLISION",
  "UNKNOWN_ENTITY",
]);

export const RELATIONSHIP_RECONCILE_ERROR_CODES = Object.freeze([
  "DUPLICATE_EDGE",
  "WRONG_EDGE_TYPE",
  "WRONG_DIRECTION",
  "WRONG_TIME_PERIOD",
  "PARTIAL_OWNERSHIP_LOST",
  "HISTORICAL_PROMOTED_CURRENT",
  "OPERATOR_PROMOTED_OWNER",
  "DEVELOPER_PROMOTED_OWNER",
  "BRAND_PROMOTED_OWNER",
  "CONTRADICTORY_EDGE_NOT_RESOLVED",
]);
