/**
 * Canonical Decision & Outcome types — shared across GDI, ADP, future modules.
 * Permanent law: never collapse RECOMMENDATION / VALIDATION / ACTION / OUTCOME.
 */

export const SCHEMA_VERSION = "decision_outcome_v1";

export const PRODUCT_MODULE = Object.freeze({
  GDI: "GDI",
  ADP: "ADP",
  BRAND_EXPLORER: "BRAND_EXPLORER",
  OPERATOR_ALIGNMENT: "OPERATOR_ALIGNMENT",
  OWNERSHIP_INTELLIGENCE: "OWNERSHIP_INTELLIGENCE",
});

export const DECISION_TYPE = Object.freeze({
  OPPORTUNITY_PURSUIT: "OPPORTUNITY_PURSUIT",
  POSITIONING_ACTION: "POSITIONING_ACTION",
  CONTACT_SELECTION: "CONTACT_SELECTION",
  BRAND_SELECTION: "BRAND_SELECTION",
  OPERATOR_SELECTION: "OPERATOR_SELECTION",
  OWNERSHIP_VALIDATION: "OWNERSHIP_VALIDATION",
});

export const SUBJECT_TYPE = Object.freeze({
  GROUP_OPPORTUNITY: "GROUP_OPPORTUNITY",
  ADP_FINDING: "ADP_FINDING",
  DEMAND_SEGMENT: "DEMAND_SEGMENT",
  CONTACT: "CONTACT",
  BRAND: "BRAND",
  OPERATOR: "OPERATOR",
  PROPERTY: "PROPERTY",
});

export const DECISION_LIFECYCLE = Object.freeze({
  RECOMMENDED: "RECOMMENDED",
  VALIDATED: "VALIDATED",
  ACTION_PLANNED: "ACTION_PLANNED",
  ACTION_TAKEN: "ACTION_TAKEN",
  OUTCOME_PENDING: "OUTCOME_PENDING",
  OUTCOME_RECORDED: "OUTCOME_RECORDED",
  CLOSED: "CLOSED",
});

export const ACTOR_ROLE = Object.freeze({
  GM: "GM",
  DOS: "DOS",
  SALES_MANAGER: "SALES_MANAGER",
  MARKETING: "MARKETING",
  OWNER: "OWNER",
  ASSET_MANAGER: "ASSET_MANAGER",
  DEALALITY_ADMIN: "DEALALITY_ADMIN",
  SYSTEM: "SYSTEM",
  OTHER: "OTHER",
});

/** GDI validation types (canonical) */
export const GDI_VALIDATION_TYPE = Object.freeze({
  FAMILIARITY: "FAMILIARITY",
  COMMERCIAL_VALUE: "COMMERCIAL_VALUE",
  CONTACT_PERSON_VALIDATION: "CONTACT_PERSON_VALIDATION",
  EMAIL_VALIDATION: "EMAIL_VALIDATION",
  PHONE_VALIDATION: "PHONE_VALIDATION",
  NOTE: "NOTE",
});

export const GDI_FAMILIARITY = Object.freeze({
  NEVER_SEEN: "NEVER_SEEN",
  ALREADY_KNOWN: "ALREADY_KNOWN",
  ACTIVELY_PURSUING: "ACTIVELY_PURSUING",
  PREVIOUSLY_PURSUED: "PREVIOUSLY_PURSUED",
  BOOKED_WON: "BOOKED_WON",
  NOT_RELEVANT: "NOT_RELEVANT",
  UNSURE: "UNSURE",
});

export const GDI_COMMERCIAL_VALUE = Object.freeze({
  WORTH_PURSUING_NOW: "WORTH_PURSUING_NOW",
  WORTH_WATCHING: "WORTH_WATCHING",
  NOT_WORTH_PURSUING: "NOT_WORTH_PURSUING",
  UNSURE: "UNSURE",
});

export const GDI_CONTACT_PERSON = Object.freeze({
  RIGHT_PERSON: "RIGHT_PERSON",
  RELEVANT_NOT_DECISION_MAKER: "RELEVANT_NOT_DECISION_MAKER",
  WRONG_PERSON: "WRONG_PERSON",
  UNSURE: "UNSURE",
});

export const GDI_EMAIL = Object.freeze({
  USEFUL: "USEFUL",
  WRONG: "WRONG",
  GENERIC: "GENERIC",
  NOT_TESTED: "NOT_TESTED",
});

export const GDI_PHONE = Object.freeze({
  DIRECT_USABLE: "DIRECT_USABLE",
  MAIN_SHARED: "MAIN_SHARED",
  WRONG: "WRONG",
  NOT_TESTED: "NOT_TESTED",
});

export const GDI_ACTION_TYPE = Object.freeze({
  NOT_CONTACTED: "NOT_CONTACTED",
  PLANNED_TO_CONTACT: "PLANNED_TO_CONTACT",
  CONTACTED: "CONTACTED",
  FOLLOW_UP_REQUIRED: "FOLLOW_UP_REQUIRED",
  RFP_REQUESTED: "RFP_REQUESTED",
  RFP_RECEIVED: "RFP_RECEIVED",
  SITE_VISIT_REQUESTED: "SITE_VISIT_REQUESTED",
  SITE_VISIT_COMPLETED: "SITE_VISIT_COMPLETED",
  PROPOSAL_SUBMITTED: "PROPOSAL_SUBMITTED",
  NEGOTIATING: "NEGOTIATING",
  NO_ACTION: "NO_ACTION",
});

export const GDI_OUTCOME_TYPE = Object.freeze({
  WON: "WON",
  LOST: "LOST",
  BOOKED: "BOOKED",
  NO_RESPONSE: "NO_RESPONSE",
  NOT_QUALIFIED: "NOT_QUALIFIED",
  OPPORTUNITY_CLOSED: "OPPORTUNITY_CLOSED",
  DEFERRED: "DEFERRED",
  /** Hotel added to planner/sourcing set — earlier than RFP/proposal/win. */
  ADDED_TO_SOURCED_PROPERTIES: "ADDED_TO_SOURCED_PROPERTIES",
  UNKNOWN: "UNKNOWN",
});

/**
 * Optional commercial funnel stage — derived from Action/Outcome events.
 * Distinct from research priority and from final win/loss outcomes.
 */
export const GDI_COMMERCIAL_FUNNEL_STAGE = Object.freeze({
  IDENTIFIED: "IDENTIFIED",
  CONTACTED: "CONTACTED",
  ADDED_TO_SOURCING: "ADDED_TO_SOURCING",
  RFP_RECEIVED: "RFP_RECEIVED",
  PROPOSAL_SUBMITTED: "PROPOSAL_SUBMITTED",
  SHORTLISTED: "SHORTLISTED",
  WON: "WON",
  LOST: "LOST",
  CLOSED_NO_DECISION: "CLOSED_NO_DECISION",
});

/** Customer-facing labels (never show raw enums). */
export const GDI_OUTCOME_TYPE_LABEL = Object.freeze({
  WON: "Won",
  LOST: "Lost",
  BOOKED: "Booked",
  NO_RESPONSE: "No response",
  NOT_QUALIFIED: "Not qualified",
  OPPORTUNITY_CLOSED: "Opportunity closed",
  DEFERRED: "Deferred",
  ADDED_TO_SOURCED_PROPERTIES: "Added to sourced properties",
  UNKNOWN: "Unknown",
});

export const GDI_ACTION_TYPE_LABEL = Object.freeze({
  NOT_CONTACTED: "Not contacted",
  PLANNED_TO_CONTACT: "Planned to contact",
  CONTACTED: "Hotel contacted opportunity",
  FOLLOW_UP_REQUIRED: "Follow-up required",
  RFP_REQUESTED: "RFP requested",
  RFP_RECEIVED: "RFP received",
  SITE_VISIT_REQUESTED: "Site visit requested",
  SITE_VISIT_COMPLETED: "Site visit completed",
  PROPOSAL_SUBMITTED: "Proposal submitted",
  NEGOTIATING: "Negotiating",
  NO_ACTION: "No action",
});

export const GDI_COMMERCIAL_FUNNEL_STAGE_LABEL = Object.freeze({
  IDENTIFIED: "Identified",
  CONTACTED: "Contacted",
  ADDED_TO_SOURCING: "Added to sourcing",
  RFP_RECEIVED: "RFP received",
  PROPOSAL_SUBMITTED: "Proposal submitted",
  SHORTLISTED: "Shortlisted",
  WON: "Won",
  LOST: "Lost",
  CLOSED_NO_DECISION: "Closed — no decision",
});

export function labelGdiOutcomeType(type) {
  const t = String(type || "").trim();
  return GDI_OUTCOME_TYPE_LABEL[t] || null;
}

export function labelGdiActionType(type) {
  const t = String(type || "").trim();
  return GDI_ACTION_TYPE_LABEL[t] || null;
}

export function labelGdiCommercialFunnelStage(stage) {
  const s = String(stage || "").trim();
  return GDI_COMMERCIAL_FUNNEL_STAGE_LABEL[s] || null;
}

export const GDI_LOSS_REASON = Object.freeze({
  RATE: "RATE",
  AVAILABILITY: "AVAILABILITY",
  LOCATION: "LOCATION",
  MEETING_SPACE: "MEETING_SPACE",
  BRAND: "BRAND",
  COMPETITOR: "COMPETITOR",
  ROOM_BLOCK: "ROOM_BLOCK",
  DATES: "DATES",
  NO_RESPONSE: "NO_RESPONSE",
  OTHER: "OTHER",
  UNKNOWN: "UNKNOWN",
});

/** ADP validation / action / outcome */
export const ADP_VALIDATION_TYPE = Object.freeze({
  HOTEL_RESPONSE: "HOTEL_RESPONSE",
});

export const ADP_VALIDATION_VALUE = Object.freeze({
  AGREE: "AGREE",
  DISAGREE: "DISAGREE",
  ALREADY_ADDRESSING: "ALREADY_ADDRESSING",
  ALREADY_COMPLETED: "ALREADY_COMPLETED",
  NOT_ACTIONABLE: "NOT_ACTIONABLE",
  NEED_HELP: "NEED_HELP",
  UNSURE: "UNSURE",
});

export const ADP_ACTION_TYPE = Object.freeze({
  WEBSITE_CONTENT_UPDATED: "WEBSITE_CONTENT_UPDATED",
  BRAND_SITE_CONTENT_REQUESTED: "BRAND_SITE_CONTENT_REQUESTED",
  OTA_CONTENT_UPDATED: "OTA_CONTENT_UPDATED",
  LOCAL_CONTENT_UPDATED: "LOCAL_CONTENT_UPDATED",
  STRUCTURED_DATA_UPDATED: "STRUCTURED_DATA_UPDATED",
  REVIEW_REPUTATION_ACTION: "REVIEW_REPUTATION_ACTION",
  SOURCE_CITATION_ACTION: "SOURCE_CITATION_ACTION",
  MARKETING_ACTION: "MARKETING_ACTION",
  BRAND_ESCALATION: "BRAND_ESCALATION",
  OTHER_ACTION: "OTHER_ACTION",
  NO_ACTION: "NO_ACTION",
});

export const ADP_OUTCOME_TYPE = Object.freeze({
  PRESENCE_IMPROVED: "PRESENCE_IMPROVED",
  CONSIDERATION_IMPROVED: "CONSIDERATION_IMPROVED",
  SEGMENT_POSITION_IMPROVED: "SEGMENT_POSITION_IMPROVED",
  CITATION_IMPROVED: "CITATION_IMPROVED",
  COMPETITOR_DISPLACEMENT_IMPROVED: "COMPETITOR_DISPLACEMENT_IMPROVED",
  NO_MEASURABLE_CHANGE: "NO_MEASURABLE_CHANGE",
  DECLINED: "DECLINED",
  TOO_EARLY_TO_MEASURE: "TOO_EARLY_TO_MEASURE",
  UNKNOWN: "UNKNOWN",
});

export const EVENT_KIND = Object.freeze({
  VALIDATION: "VALIDATION",
  ACTION: "ACTION",
  OUTCOME: "OUTCOME",
});

export const CAUSAL_CONFIDENCE = Object.freeze({
  UNKNOWN: "UNKNOWN",
  TEMPORAL_ASSOCIATION_ONLY: "TEMPORAL_ASSOCIATION_ONLY",
  SUPPORTED_INFERENCE: "SUPPORTED_INFERENCE",
});
