/**
 * GDI Hidden Demand Expansion V1 — constants.
 * Market intelligence first; hotel matching second. No hotel-name hardcodes in logic.
 */

export const HIDDEN_DEMAND_VERSION = "gdi_hidden_demand_v1";

export const HIDDEN_DEMAND_ID_PREFIX = "hd_";
export const DEMAND_GENERATOR_ID_PREFIX = "hdg_";
export const HOTEL_MATCH_ID_PREFIX = "hdhm_";

export const DISCOVERY_DEPTH = Object.freeze({
  OBVIOUS_MARKET_DEMAND: "OBVIOUS_MARKET_DEMAND",
  ONE_LAYER_DEEP: "ONE_LAYER_DEEP",
  TWO_LAYERS_DEEP: "TWO_LAYERS_DEEP",
  DIRECT_HIDDEN_SIGNAL: "DIRECT_HIDDEN_SIGNAL",
});

export const DEMAND_FAMILY = Object.freeze({
  EXHIBITOR_VENDOR: "EXHIBITOR_VENDOR",
  PRODUCTION_CREW: "PRODUCTION_CREW",
  CORPORATE_PROJECT: "CORPORATE_PROJECT",
  TRAINING: "TRAINING",
  TOUR_SERIES: "TOUR_SERIES",
  DELEGATION: "DELEGATION",
  EDUCATION: "EDUCATION",
  SPORTS_ADJACENT: "SPORTS_ADJACENT",
  AGENCY: "AGENCY",
  FASHION: "FASHION",
  MEDICAL_PHARMA: "MEDICAL_PHARMA",
  SOCIAL: "SOCIAL",
  ASSOCIATION_SUBGROUP: "ASSOCIATION_SUBGROUP",
});

export const HIDDEN_MOTION = Object.freeze({
  EXHIBITOR_BLOCK: "EXHIBITOR_BLOCK",
  VENDOR_BLOCK: "VENDOR_BLOCK",
  PROJECT_TEAM: "PROJECT_TEAM",
  CREW_LODGING: "CREW_LODGING",
  PRODUCTION_TEAM: "PRODUCTION_TEAM",
  ENTERTAINMENT_BLOCK: "ENTERTAINMENT_BLOCK",
  CORPORATE_PROJECT_BLOCK: "CORPORATE_PROJECT_BLOCK",
  TRAINING_COHORT: "TRAINING_COHORT",
  TEMPORARY_ASSIGNMENT: "TEMPORARY_ASSIGNMENT",
  TOUR_SERIES: "TOUR_SERIES",
  RECURRING_ROOM_BLOCK: "RECURRING_ROOM_BLOCK",
  DELEGATION_BLOCK: "DELEGATION_BLOCK",
  STUDENT_GROUP: "STUDENT_GROUP",
  EDUCATIONAL_GROUP: "EDUCATIONAL_GROUP",
  ALUMNI_BLOCK: "ALUMNI_BLOCK",
  SPORTS_TEAM_BLOCK: "SPORTS_TEAM_BLOCK",
  SPORTS_SUPPORT_BLOCK: "SPORTS_SUPPORT_BLOCK",
  AGENCY_PROJECT_BLOCK: "AGENCY_PROJECT_BLOCK",
  BRAND_ACTIVATION_TEAM: "BRAND_ACTIVATION_TEAM",
  FASHION_PROJECT_BLOCK: "FASHION_PROJECT_BLOCK",
  SHOWROOM_TEAM: "SHOWROOM_TEAM",
  PHARMA_PROJECT_BLOCK: "PHARMA_PROJECT_BLOCK",
  ADVISORY_BOARD: "ADVISORY_BOARD",
  SOCIAL_ROOM_BLOCK: "SOCIAL_ROOM_BLOCK",
  WEDDING_HOUSING: "WEDDING_HOUSING",
  VENUE_PARTNERSHIP: "VENUE_PARTNERSHIP",
  ASSOCIATION_SUBGROUP: "ASSOCIATION_SUBGROUP",
  BOARD_RETREAT: "BOARD_RETREAT",
  LEADERSHIP_MEETING: "LEADERSHIP_MEETING",
  OVERFLOW: "OVERFLOW",
  ROOM_BLOCK: "ROOM_BLOCK",
});

export const LODGING_SIGNAL_STRENGTH = Object.freeze({
  STRONG: "STRONG",
  MEDIUM: "MEDIUM",
  WEAK: "WEAK",
  UNKNOWN: "UNKNOWN",
});

export const RECLASS_LABEL = Object.freeze({
  GENUINELY_HIDDEN: "GENUINELY_HIDDEN",
  OBVIOUS_GENERATOR_ONLY: "OBVIOUS_GENERATOR_ONLY",
  DEEPER_MOTION_EXISTS: "DEEPER_MOTION_EXISTS",
  NEEDS_MORE_RESEARCH: "NEEDS_MORE_RESEARCH",
});

export const CUSTOMER_PROMOTABLE_DEPTHS = Object.freeze([
  DISCOVERY_DEPTH.TWO_LAYERS_DEEP,
  DISCOVERY_DEPTH.DIRECT_HIDDEN_SIGNAL,
]);
