/**
 * GDI Hidden Demand V3 — market candidate vs hotel opportunity states.
 * Lodging ladder, triage, travel, team bands — no hotel hardcodes.
 */

export const HIDDEN_DEMAND_V3 = "gdi_hidden_demand_v3";

/** Pipeline states — do not skip ahead to HOTEL_OPPORTUNITY. */
export const CANDIDATE_STATE = Object.freeze({
  MARKET_ENTITY: "MARKET_ENTITY",
  MARKET_HIDDEN_CANDIDATE: "MARKET_HIDDEN_CANDIDATE",
  LODGING_PLAUSIBLE: "LODGING_PLAUSIBLE",
  HOTEL_MATCH_CANDIDATE: "HOTEL_MATCH_CANDIDATE",
  HOTEL_OPPORTUNITY: "HOTEL_OPPORTUNITY",
  ACTIONABLE_NOW: "ACTIONABLE_NOW",
});

export const RESEARCH_TRIAGE = Object.freeze({
  HIGH_RESEARCH_VALUE: "HIGH_RESEARCH_VALUE",
  MEDIUM_RESEARCH_VALUE: "MEDIUM_RESEARCH_VALUE",
  LOW_RESEARCH_VALUE: "LOW_RESEARCH_VALUE",
  STOP: "STOP",
});

export const TEAM_SIZE_BAND = Object.freeze({
  SOLO_OR_TINY: "SOLO_OR_TINY",
  SMALL_TEAM: "SMALL_TEAM",
  MEDIUM_TEAM: "MEDIUM_TEAM",
  LARGE_TEAM: "LARGE_TEAM",
  UNKNOWN: "UNKNOWN",
});

export const TRAVEL_LIKELIHOOD = Object.freeze({
  STRONG: "STRONG",
  MEDIUM: "MEDIUM",
  WEAK: "WEAK",
  UNKNOWN: "UNKNOWN",
});

/** Lodging proof ladder (V3) — not inventable room counts. */
export const LODGING_PROOF = Object.freeze({
  CONFIRMED: "CONFIRMED",
  STRONG_INFERENCE: "STRONG_INFERENCE",
  PLAUSIBLE: "PLAUSIBLE",
  WEAK: "WEAK",
  UNKNOWN: "UNKNOWN",
});

export const COMPANY_LOCALITY = Object.freeze({
  NYC_LOCAL: "NYC_LOCAL",
  NY_METRO: "NY_METRO",
  DOMESTIC_OUT_OF_MARKET: "DOMESTIC_OUT_OF_MARKET",
  INTERNATIONAL: "INTERNATIONAL",
  UNKNOWN: "UNKNOWN",
});

export const ADDRESSABILITY = Object.freeze({
  NAMED_PERSON: "NAMED_PERSON",
  FUNCTIONAL_PATH: "FUNCTIONAL_PATH",
  COMPANY_PATH: "COMPANY_PATH",
  NO_USABLE_PATH: "NO_USABLE_PATH",
});

export const CONTACT_CURRENTNESS = Object.freeze({
  CURRENT_CONFIRMED: "CURRENT_CONFIRMED",
  CURRENT_LIKELY: "CURRENT_LIKELY",
  HISTORICAL_ONLY: "HISTORICAL_ONLY",
  FORMER: "FORMER",
  UNKNOWN: "UNKNOWN",
});

export const EXHIBITOR_WHO_ROLES = Object.freeze([
  "EVENT_MARKETING",
  "FIELD_MARKETING",
  "EVENTS_DIRECTOR",
  "TRADE_SHOW_MANAGER",
  "EXPERIENTIAL_MARKETING",
  "SALES_OPERATIONS",
  "REGIONAL_SALES",
  "MARKETING_OPERATIONS",
  "PROJECT_MANAGER",
  "TRAVEL_MANAGER",
  "EXECUTIVE_ASSISTANT",
  "OPERATIONS_LEAD",
  "AGENCY_ACCOUNT_LEAD",
  "OTHER_RELEVANT",
]);

export const EXHIBITOR_TEAM_RESEARCH_PATH_CHOICES = Object.freeze([
  "COMPANY_EVENT_PAGE",
  "NEWSROOM",
  "SPEAKER_ROSTER",
  "PROFESSIONAL_STAFF",
  "AGENCY_RELATIONSHIP",
  "TRAVEL_EVIDENCE",
  "FUNCTIONAL_CONTACT",
  "STOP_LOW_PROBABILITY",
  "STOP_SUFFICIENT",
]);

export const LODGING_EVIDENCE_NEXT_STEP_CHOICES = Object.freeze([
  "HOUSING_SOURCE",
  "COMPANY_TRAVEL_PAGE",
  "EVENT_REGISTRATION",
  "TEAM_ROSTER",
  "AGENCY_SOURCE",
  "STOP_PLAUSIBLE_ONLY",
  "STOP_SUFFICIENT",
  "STOP_LOW_VALUE",
]);

/** Hotel opportunity requires these lodging proof levels. */
export const HOTEL_OPPORTUNITY_LODGING = Object.freeze([
  LODGING_PROOF.CONFIRMED,
  LODGING_PROOF.STRONG_INFERENCE,
]);

// Re-export participation depth / travel class from earlier V3 scaffold if used
export {
  PARTICIPATION_DEPTH,
  TRAVEL_CLASS,
  BUYER_ROLE,
} from "./v3-constants.js";
