/** @type {import("./island-build-types.js").IslandBuildSpec} */
export const BRITISH_VIRGIN_ISLANDS_BUILD = {
  slug: "british-virgin-islands",
  country: "British Virgin Islands",
  sequence: 24,
  market: "British Virgin Islands Countrywide",
  submarkets: ["Tortola", "Virgin Gorda", "Other Islands", "Other"],
  notes: "Tortola Road Town civic and yacht hub; Virgin Gorda resort; Jost Van Dyke and Anegada leisure satellites.",
  tourismUrl: "https://www.bvitourism.com/",
  microPass: {
    names: [],
    rules: [{ base: ["https://www.bvitourism.com/", "https://www.bvitourism.com"], template: "https://www.bvitourism.com/places/{key}" }],
  },
  audit: {
    keywords: ["british virgin", "bvi", "tortola", "road town", "virgin gorda", "terrance lett", "eis", "jost van dyke", "anegada", "yacht", "sopers hole"],
    expectedPatterns: [
      { label: "Terrance B. Lettsome Airport / EIS", patterns: [/terrance.*lettsome/i, /\bEIS\b/i] },
      { label: "Road Town ferry terminal", patterns: [/road town.*ferry/i] },
      { label: "Virgin Gorda Yacht Harbour", patterns: [/virgin gorda.*yacht/i, /spanish town/i] },
      { label: "The Baths Virgin Gorda", patterns: [/the baths/i] },
      { label: "Jost Van Dyke Great Harbour", patterns: [/jost van dyke/i, /great harbour/i] },
    ],
  },
  candidates: [
    { name: "Terrance B. Lettsome International Airport Corridor", pointType: "Future Growth Node", city: "Beef Island", submarket: "Tortola", latitude: 18.4448, longitude: -64.5430, sourceReference: "https://www.bviaa.com/", manuallyVerified: true },
    { name: "Road Town Central Business District", pointType: "Business District", city: "Road Town", submarket: "Tortola", latitude: 18.4261, longitude: -64.6205, sourceReference: "https://www.bvitourism.com/", manuallyVerified: true },
    { name: "Road Town Ferry Terminal", pointType: "Mixed-Use Development", city: "Road Town", submarket: "Tortola", latitude: 18.4245, longitude: -64.6189, sourceReference: "https://www.bvitourism.com/", manuallyVerified: true },
    { name: "Wickham's Cay Marina District", pointType: "Beach / Waterfront", city: "Road Town", submarket: "Tortola", latitude: 18.4212, longitude: -64.6156, sourceReference: "https://www.bvitourism.com/" },
    { name: "Soper's Hole Marina West End", pointType: "Beach / Waterfront", city: "West End", submarket: "Tortola", latitude: 18.4123, longitude: -64.6678, sourceReference: "https://www.bvitourism.com/" },
    { name: "Nanny Cay Marina and Resort", pointType: "Mixed-Use Development", city: "Nanny Cay", submarket: "Tortola", latitude: 18.3789, longitude: -64.6234, sourceReference: "https://www.bvitourism.com/" },
    { name: "Cane Garden Bay Beach", pointType: "Beach / Waterfront", city: "Cane Garden Bay", submarket: "Tortola", latitude: 18.4345, longitude: -64.6456, sourceReference: "https://www.bvitourism.com/", manuallyVerified: true },
    { name: "Smuggler's Cove Beach", pointType: "Beach / Waterfront", city: "West End", submarket: "Tortola", latitude: 18.4567, longitude: -64.6789, sourceReference: "https://www.bvitourism.com/" },
    { name: "Long Bay Beach Tortola", pointType: "Beach / Waterfront", city: "East End", submarket: "Tortola", latitude: 18.4456, longitude: -64.5678, sourceReference: "https://www.bvitourism.com/" },
    { name: "J.R. O'Neal Botanic Gardens", pointType: "Tourist Attraction", city: "Road Town", submarket: "Tortola", latitude: 18.4289, longitude: -64.6123, sourceReference: "https://www.bvitourism.com/" },
    { name: "Peebles Hospital", pointType: "Medical Campus", city: "Road Town", submarket: "Tortola", latitude: 18.4256, longitude: -64.6234, sourceReference: "https://www.bvi.gov.vg/" },
    { name: "H. Lavity Stoutt Community College", pointType: "University / College", city: "Road Town", submarket: "Tortola", latitude: 18.4312, longitude: -64.6089, sourceReference: "https://www.bvi.gov.vg/" },
    { name: "A.O. Shirley Recreation Ground", pointType: "Sports Venue", city: "Road Town", submarket: "Tortola", latitude: 18.4234, longitude: -64.6267, sourceReference: "https://www.bvitourism.com/" },
    { name: "Virgin Gorda Yacht Harbour", pointType: "Beach / Waterfront", city: "Spanish Town", submarket: "Virgin Gorda", latitude: 18.4512, longitude: -64.4345, sourceReference: "https://www.bvitourism.com/", manuallyVerified: true },
    { name: "The Baths National Park", pointType: "Tourist Attraction", city: "Spanish Town", submarket: "Virgin Gorda", latitude: 18.4312, longitude: -64.4456, sourceReference: "https://www.bvitourism.com/", manuallyVerified: true },
    { name: "Oil Nut Bay Resort", pointType: "Mixed-Use Development", city: "Virgin Gorda", submarket: "Virgin Gorda", latitude: 18.4789, longitude: -64.4012, sourceReference: "https://www.bvitourism.com/" },
    { name: "Leverick Bay Resort Marina", pointType: "Beach / Waterfront", city: "North Sound", submarket: "Virgin Gorda", latitude: 18.5012, longitude: -64.3789, sourceReference: "https://www.bvitourism.com/" },
    { name: "Bitter End Yacht Club", pointType: "Mixed-Use Development", city: "North Sound", submarket: "Virgin Gorda", latitude: 18.5123, longitude: -64.3678, sourceReference: "https://www.bvitourism.com/" },
    { name: "Virgin Gorda Airport Corridor", pointType: "Future Growth Node", city: "Spanish Town", submarket: "Virgin Gorda", latitude: 18.4464, longitude: -64.4275, sourceReference: "https://www.bviaa.com/", manuallyVerified: true },
    { name: "Jost Van Dyke Great Harbour", pointType: "Beach / Waterfront", city: "Great Harbour", submarket: "Other Islands", latitude: 18.4456, longitude: -64.7512, sourceReference: "https://www.bvitourism.com/" },
    { name: "White Bay Beach Jost Van Dyke", pointType: "Beach / Waterfront", city: "White Bay", submarket: "Other Islands", latitude: 18.4389, longitude: -64.7567, sourceReference: "https://www.bvitourism.com/" },
    { name: "Foxy's Tamarind Bar District", pointType: "Entertainment District", city: "Great Harbour", submarket: "Other Islands", latitude: 18.4467, longitude: -64.7523, sourceReference: "https://www.bvitourism.com/" },
    { name: "Anegada Reef Hotel Zone", pointType: "Mixed-Use Development", city: "The Settlement", submarket: "Other Islands", latitude: 18.7234, longitude: -64.3234, sourceReference: "https://www.bvitourism.com/" },
    { name: "Anegada Flamingo Pond", pointType: "Tourist Attraction", city: "The Settlement", submarket: "Other Islands", latitude: 18.7123, longitude: -64.3345, sourceReference: "https://www.bvitourism.com/" },
    { name: "Loblolly Bay Anegada", pointType: "Beach / Waterfront", city: "The Settlement", submarket: "Other Islands", latitude: 18.7456, longitude: -64.3123, sourceReference: "https://www.bvitourism.com/" },
    { name: "Anegada Airport Corridor", pointType: "Future Growth Node", city: "The Settlement", submarket: "Other Islands", latitude: 18.7272, longitude: -64.3296, sourceReference: "https://www.bviaa.com/" },
    { name: "Peter Island Resort Zone", pointType: "Mixed-Use Development", city: "Peter Island", submarket: "Other Islands", latitude: 18.3512, longitude: -64.6234, sourceReference: "https://www.bvitourism.com/" },
    { name: "Cooper Island Beach Club", pointType: "Beach / Waterfront", city: "Cooper Island", submarket: "Other Islands", latitude: 18.3789, longitude: -64.5234, sourceReference: "https://www.bvitourism.com/" },
    { name: "Norman Island Pirate Bight", pointType: "Tourist Attraction", city: "Norman Island", submarket: "Other Islands", latitude: 18.3234, longitude: -64.6123, sourceReference: "https://www.bvitourism.com/" },
    { name: "Saba Rock Resort", pointType: "Mixed-Use Development", city: "Virgin Gorda", submarket: "Virgin Gorda", latitude: 18.5012, longitude: -64.3567, sourceReference: "https://www.bvitourism.com/" },
    { name: "BVI Finance Business Precinct", pointType: "Government / Civic Center", city: "Road Town", submarket: "Tortola", latitude: 18.4278, longitude: -64.6212, sourceReference: "https://www.bvi.gov.vg/" },
    { name: "Tortola Yacht Charter Hub", pointType: "Future Growth Node", city: "Road Town", submarket: "Tortola", latitude: 18.4251, longitude: -64.6178, sourceReference: "https://www.bvitourism.com/" },
    { name: "BVI Convention Centre Road Town", pointType: "Convention Center", city: "Road Town", submarket: "Tortola", latitude: 18.4267, longitude: -64.6198, sourceReference: "https://www.bvitourism.com/" },
    { name: "Tortola Cruise Pier Expansion Node", pointType: "Future Growth Node", city: "Road Town", submarket: "Tortola", latitude: 18.4239, longitude: -64.6167, sourceReference: "https://www.bvi.gov.vg/" },
    { name: "East End Tortola Growth Corridor", pointType: "Future Growth Node", city: "East End", submarket: "Tortola", latitude: 18.4478, longitude: -64.5612, sourceReference: "https://www.bvi.gov.vg/" },
    { name: "BVI Port Authority Logistics Zone", pointType: "Industrial / Logistics Zone", city: "Road Town", submarket: "Tortola", latitude: 18.4223, longitude: -64.6145, sourceReference: "https://www.bviports.org/" },
    { name: "Rhone Marine Park Dive Site", pointType: "Tourist Attraction", city: "Salt Island", submarket: "Other Islands", latitude: 18.3678, longitude: -64.5345, sourceReference: "https://www.bvitourism.com/" },
    { name: "Sage Mountain National Park", pointType: "Tourist Attraction", city: "Road Town", submarket: "Tortola", latitude: 18.4567, longitude: -64.6012, sourceReference: "https://www.bvitourism.com/" },
    { name: "Treasure Point Resort Growth", pointType: "Mixed-Use Development", city: "East End", submarket: "Tortola", latitude: 18.4412, longitude: -64.5789, sourceReference: "https://www.bvitourism.com/" },
  ],
  tiRecords: [
    { name: "Terrance B. Lettsome Airport Access", pointType: "Highway Access", pointSubtype: "Airport Access", city: "Beef Island", submarket: "Tortola", latitude: 18.4448, longitude: -64.5430, sourceReference: "https://www.bviaa.com/", notes: "Primary international gateway for BVI on Beef Island." },
    { name: "Road Town Ferry Terminal Access", pointType: "Ferry Terminal", pointSubtype: "Inter-Island Ferry", city: "Road Town", submarket: "Tortola", latitude: 18.4245, longitude: -64.6189, sourceReference: "https://www.bvitourism.com/", notes: "Main ferry hub linking Tortola to USVI and outer islands." },
    { name: "Soper's Hole Marina Access", pointType: "Port / Maritime", pointSubtype: "Marina", city: "West End", submarket: "Tortola", latitude: 18.4123, longitude: -64.6678, sourceReference: "https://www.bvitourism.com/", notes: "West End yacht marina and village access.", useCaseTags: ["Cruise / Port", "Resort / Leisure"] },
    { name: "Nanny Cay Marina Access", pointType: "Port / Maritime", pointSubtype: "Marina", city: "Nanny Cay", submarket: "Tortola", latitude: 18.3789, longitude: -64.6234, sourceReference: "https://www.bvitourism.com/", notes: "South Tortola marina resort access." },
    { name: "Virgin Gorda Yacht Harbour Access", pointType: "Port / Maritime", pointSubtype: "Marina", city: "Spanish Town", submarket: "Virgin Gorda", latitude: 18.4512, longitude: -64.4345, sourceReference: "https://www.bvitourism.com/", notes: "Virgin Gorda marina and resort gateway." },
    { name: "Virgin Gorda Airport Access", pointType: "Highway Access", pointSubtype: "Airport Access", city: "Spanish Town", submarket: "Virgin Gorda", latitude: 18.4464, longitude: -64.4275, sourceReference: "https://www.bviaa.com/", notes: "Virgin Gorda air link for inter-island demand." },
    { name: "Jost Van Dyke Ferry Access", pointType: "Ferry Terminal", pointSubtype: "Inter-Island Ferry", city: "Great Harbour", submarket: "Other Islands", latitude: 18.4456, longitude: -64.7512, sourceReference: "https://www.bvitourism.com/", notes: "Ferry access to Jost Van Dyke leisure district." },
    { name: "BVI Port Authority Road Town Access", pointType: "Port / Maritime", pointSubtype: "Commercial Port", city: "Road Town", submarket: "Tortola", latitude: 18.4223, longitude: -64.6145, sourceReference: "https://www.bviports.org/", notes: "Cargo and cruise port logistics access.", useCaseTags: ["Industrial / Logistics", "Cruise / Port"] },
  ],
  googleCorrections: {},
};
