/** @type {import("./island-build-types.js").IslandBuildSpec} */
export const DOMINICA_BUILD = {
  slug: "dominica",
  country: "Dominica",
  sequence: 21,
  market: "Dominica Countrywide",
  submarkets: ["Roseau", "Portsmouth", "East Coast", "South Coast", "Other"],
  notes: "Nature-island eco/adventure positioning; Roseau cruise/civic; Portsmouth north gateway.",
  tourismUrl: "https://www.discoverdominica.com/",
  microPass: {
    names: [],
    rules: [{ base: ["https://www.discoverdominica.com/", "https://www.discoverdominica.com"], template: "https://www.discoverdominica.com/places/{key}" }],
  },
  audit: {
    keywords: ["dominica", "roseau", "portsmouth", "douglas-charles", "dom", "cruise", "boiling lake", "scotts head", "cabrits"],
    expectedPatterns: [
      { label: "Douglas-Charles Airport / DOM", patterns: [/douglas.?charles/i, /\bDOM\b/i] },
      { label: "Roseau cruise berth", patterns: [/roseau.*cruise/i] },
      { label: "Portsmouth Cabrits", patterns: [/portsmouth/i, /cabrits/i] },
      { label: "Boiling Lake trailhead", patterns: [/boiling lake/i] },
    ],
  },
  candidates: [
    { name: "Douglas-Charles Airport Corridor", pointType: "Future Growth Node", city: "Marigot", submarket: "Portsmouth", latitude: 15.5470, longitude: -61.3000, sourceReference: "https://www.dominica.gov.dm/", manuallyVerified: true },
    { name: "Canefield Airport", pointType: "Future Growth Node", city: "Canefield", submarket: "Roseau", latitude: 15.3367, longitude: -61.3922, sourceReference: "https://www.dominica.gov.dm/", manuallyVerified: true },
    { name: "Roseau Cruise Ship Berth", pointType: "Mixed-Use Development", city: "Roseau", submarket: "Roseau", latitude: 15.2978, longitude: -61.3871, sourceReference: "https://www.discoverdominica.com/", manuallyVerified: true },
    { name: "Roseau Central Business District", pointType: "Business District", city: "Roseau", submarket: "Roseau", latitude: 15.3012, longitude: -61.3889, sourceReference: "https://www.discoverdominica.com/" },
    { name: "Old Market Roseau", pointType: "Entertainment District", city: "Roseau", submarket: "Roseau", latitude: 15.2989, longitude: -61.3867, sourceReference: "https://www.discoverdominica.com/" },
    { name: "Dominica Botanic Gardens", pointType: "Tourist Attraction", city: "Roseau", submarket: "Roseau", latitude: 15.3123, longitude: -61.3912, sourceReference: "https://www.discoverdominica.com/" },
    { name: "Dominica State College", pointType: "University / College", city: "Roseau", submarket: "Roseau", latitude: 15.3056, longitude: -61.3845, sourceReference: "https://www.dominica.gov.dm/" },
    { name: "Princess Margaret Hospital", pointType: "Medical Campus", city: "Roseau", submarket: "Roseau", latitude: 15.3034, longitude: -61.3823, sourceReference: "https://www.dominica.gov.dm/" },
    { name: "Windsor Park Sports Stadium", pointType: "Sports Venue", city: "Roseau", submarket: "Roseau", latitude: 15.3089, longitude: -61.3789, sourceReference: "https://www.discoverdominica.com/" },
    { name: "Morne Bruce Viewpoint", pointType: "Tourist Attraction", city: "Roseau", submarket: "Roseau", latitude: 15.3234, longitude: -61.3756, sourceReference: "https://www.discoverdominica.com/" },
    { name: "Trafalgar Falls", pointType: "Tourist Attraction", city: "Trafalgar", submarket: "Roseau", latitude: 15.3345, longitude: -61.3567, sourceReference: "https://www.discoverdominica.com/" },
    { name: "Emerald Pool Nature Trail", pointType: "Tourist Attraction", city: "Morne Trois Pitons", submarket: "Other", latitude: 15.3234, longitude: -61.3234, sourceReference: "https://www.discoverdominica.com/" },
    { name: "Boiling Lake Trailhead", pointType: "Tourist Attraction", city: "Laudat", submarket: "Other", latitude: 15.3345, longitude: -61.3012, sourceReference: "https://www.discoverdominica.com/", manuallyVerified: true },
    { name: "Morne Trois Pitons National Park UNESCO", pointType: "Tourist Attraction", city: "Laudat", submarket: "Other", latitude: 15.3456, longitude: -61.3123, sourceReference: "https://www.discoverdominica.com/", manuallyVerified: true },
    { name: "Champagne Reef Snorkel Site", pointType: "Beach / Waterfront", city: "Soufriere", submarket: "South Coast", latitude: 15.2234, longitude: -61.3567, sourceReference: "https://www.discoverdominica.com/" },
    { name: "Scotts Head Marine Reserve", pointType: "Beach / Waterfront", city: "Scotts Head", submarket: "South Coast", latitude: 15.2123, longitude: -61.3789, sourceReference: "https://www.discoverdominica.com/", manuallyVerified: true },
    { name: "Soufriere Bay Village", pointType: "Tourist Attraction", city: "Soufriere", submarket: "South Coast", latitude: 15.2345, longitude: -61.3567, sourceReference: "https://www.discoverdominica.com/" },
    { name: "Calibishie Coastal Village", pointType: "Beach / Waterfront", city: "Calibishie", submarket: "East Coast", latitude: 15.5923, longitude: -61.3456, sourceReference: "https://www.discoverdominica.com/" },
    { name: "Red Rock Beach East Coast", pointType: "Beach / Waterfront", city: "Calibishie", submarket: "East Coast", latitude: 15.6012, longitude: -61.3389, sourceReference: "https://www.discoverdominica.com/" },
    { name: "Cabrits National Park Portsmouth", pointType: "Tourist Attraction", city: "Portsmouth", submarket: "Portsmouth", latitude: 15.5845, longitude: -61.4678, sourceReference: "https://www.discoverdominica.com/", manuallyVerified: true },
    { name: "Fort Shirley Historic Site", pointType: "Tourist Attraction", city: "Portsmouth", submarket: "Portsmouth", latitude: 15.5867, longitude: -61.4623, sourceReference: "https://www.discoverdominica.com/" },
    { name: "Portsmouth Bay Marina", pointType: "Beach / Waterfront", city: "Portsmouth", submarket: "Portsmouth", latitude: 15.5789, longitude: -61.4567, sourceReference: "https://www.discoverdominica.com/" },
    { name: "Indian River Tour Gateway", pointType: "Tourist Attraction", city: "Portsmouth", submarket: "Portsmouth", latitude: 15.5712, longitude: -61.4512, sourceReference: "https://www.discoverdominica.com/" },
    { name: "Secret Bay Resort", pointType: "Mixed-Use Development", city: "Coulibistrie", submarket: "Other", latitude: 15.4123, longitude: -61.4456, sourceReference: "https://www.discoverdominica.com/" },
    { name: "Jungle Bay Resort Spa", pointType: "Mixed-Use Development", city: "Soufriere", submarket: "South Coast", latitude: 15.2289, longitude: -61.3512, sourceReference: "https://www.discoverdominica.com/" },
    { name: "Papillote Wilderness Retreat", pointType: "Tourist Attraction", city: "Trafalgar", submarket: "Roseau", latitude: 15.3312, longitude: -61.3589, sourceReference: "https://www.discoverdominica.com/" },
    { name: "Middleham Falls", pointType: "Tourist Attraction", city: "Laudat", submarket: "Other", latitude: 15.3567, longitude: -61.3234, sourceReference: "https://www.discoverdominica.com/" },
    { name: "Titou Gorge", pointType: "Tourist Attraction", city: "Laudat", submarket: "Other", latitude: 15.3489, longitude: -61.3189, sourceReference: "https://www.discoverdominica.com/" },
    { name: "Waitukubuli National Trail Segment Roseau", pointType: "Tourist Attraction", city: "Roseau", submarket: "Roseau", latitude: 15.3156, longitude: -61.3678, sourceReference: "https://www.discoverdominica.com/" },
    { name: "Layou River Valley", pointType: "Tourist Attraction", city: "Layou", submarket: "Other", latitude: 15.4012, longitude: -61.4012, sourceReference: "https://www.discoverdominica.com/" },
    { name: "Mero Beach", pointType: "Beach / Waterfront", city: "Mero", submarket: "Other", latitude: 15.4234, longitude: -61.4234, sourceReference: "https://www.discoverdominica.com/" },
    { name: "Dominica Export Import Agency Precinct", pointType: "Government / Civic Center", city: "Roseau", submarket: "Roseau", latitude: 15.3023, longitude: -61.3856, sourceReference: "https://www.investdominica.dm/" },
    { name: "Dominica Industrial Estate", pointType: "Industrial / Logistics Zone", city: "Fond Cole", submarket: "Roseau", latitude: 15.2912, longitude: -61.4012, sourceReference: "https://www.dominica.gov.dm/" },
    { name: "Rosalie Bay Resort Turtle Sanctuary", pointType: "Tourist Attraction", city: "Rosalie", submarket: "East Coast", latitude: 15.3678, longitude: -61.2623, sourceReference: "https://www.discoverdominica.com/" },
    { name: "Hampstead Beach", pointType: "Beach / Waterfront", city: "Hampstead", submarket: "East Coast", latitude: 15.5789, longitude: -61.3234, sourceReference: "https://www.discoverdominica.com/" },
    { name: "Castle Bruce Village", pointType: "Tourist Attraction", city: "Castle Bruce", submarket: "East Coast", latitude: 15.4456, longitude: -61.2567, sourceReference: "https://www.discoverdominica.com/" },
    { name: "Dominica Convention Bureau District", pointType: "Convention Center", city: "Roseau", submarket: "Roseau", latitude: 15.3001, longitude: -61.3878, sourceReference: "https://www.discoverdominica.com/" },
    { name: "Portsmouth North Gateway Growth Node", pointType: "Future Growth Node", city: "Portsmouth", submarket: "Portsmouth", latitude: 15.5812, longitude: -61.4589, sourceReference: "https://www.investdominica.dm/" },
    { name: "Roseau Valley Resort Growth Corridor", pointType: "Future Growth Node", city: "Roseau", submarket: "Roseau", latitude: 15.3189, longitude: -61.3712, sourceReference: "https://www.investdominica.dm/" },
  ],
  tiRecords: [
    { name: "Douglas-Charles Airport Access", pointType: "Highway Access", pointSubtype: "Airport Access", city: "Marigot", submarket: "Portsmouth", latitude: 15.5470, longitude: -61.3000, sourceReference: "https://www.dominica.gov.dm/", notes: "Primary international airport in north-east." },
    { name: "Canefield Airport Access", pointType: "Highway Access", pointSubtype: "Airport Access", city: "Canefield", submarket: "Roseau", latitude: 15.3367, longitude: -61.3922, sourceReference: "https://www.dominica.gov.dm/", notes: "Regional airport near Roseau capital." },
    { name: "Roseau Cruise Berth Access", pointType: "Port / Maritime", pointSubtype: "Cruise Terminal", city: "Roseau", submarket: "Roseau", latitude: 15.2978, longitude: -61.3871, sourceReference: "https://www.discoverdominica.com/", notes: "Capital cruise berth access.", useCaseTags: ["Cruise / Port", "Resort / Leisure"] },
    { name: "Portsmouth Bay Marina Access", pointType: "Port / Maritime", pointSubtype: "Marina", city: "Portsmouth", submarket: "Portsmouth", latitude: 15.5789, longitude: -61.4567, sourceReference: "https://www.discoverdominica.com/", notes: "North coast marina and yacht access." },
    { name: "Cabrits National Park Access", pointType: "Highway Access", pointSubtype: "Scenic Corridor", city: "Portsmouth", submarket: "Portsmouth", latitude: 15.5845, longitude: -61.4678, sourceReference: "https://www.discoverdominica.com/", notes: "Historic fort and north gateway scenic access." },
    { name: "Scotts Head Marine Reserve Access", pointType: "Highway Access", pointSubtype: "Coastal Corridor", city: "Scotts Head", submarket: "South Coast", latitude: 15.2123, longitude: -61.3789, sourceReference: "https://www.discoverdominica.com/", notes: "South-west coastal dive and snorkel access." },
    { name: "Calibishie East Coast Access", pointType: "Highway Access", pointSubtype: "Coastal Corridor", city: "Calibishie", submarket: "East Coast", latitude: 15.5923, longitude: -61.3456, sourceReference: "https://www.discoverdominica.com/", notes: "Atlantic coast village and beach access." },
    { name: "Dominica Industrial Estate Access", pointType: "Highway Access", pointSubtype: "Industrial Corridor", city: "Fond Cole", submarket: "Roseau", latitude: 15.2912, longitude: -61.4012, sourceReference: "https://www.dominica.gov.dm/", notes: "Industrial zone connector near capital.", useCaseTags: ["Industrial / Logistics", "Airport / Transit"] },
  ],
  googleCorrections: {},
};
