/** @type {import("./island-build-types.js").IslandBuildSpec} */
export const SAINT_VINCENT_AND_THE_GRENADINES_BUILD = {
  slug: "saint-vincent-and-the-grenadines",
  country: "Saint Vincent and the Grenadines",
  sequence: 20,
  market: "Saint Vincent and the Grenadines Countrywide",
  submarkets: ["Kingstown", "Grenadines", "North Coast", "Other"],
  notes: "Kingstown cruise/civic; Grenadines yacht/leisure islands; Argyle airport south gateway.",
  tourismUrl: "https://www.discoversvg.com/",
  microPass: {
    names: [],
    rules: [{ base: ["https://www.discoversvg.com/", "https://www.discoversvg.com"], template: "https://www.discoversvg.com/places/{key}" }],
  },
  audit: {
    keywords: ["saint vincent", "st vincent", "svg", "kingstown", "grenadines", "bequia", "mustique", "union island", "argyle", "svb", "cruise"],
    expectedPatterns: [
      { label: "Argyle International Airport / SVD", patterns: [/argyle.*international/i, /\bSVD\b/i] },
      { label: "Kingstown cruise berth", patterns: [/kingstown.*cruise/i, /cruise.*kingstown/i] },
      { label: "Bequia tourism gateway", patterns: [/bequia/i] },
      { label: "Mustique resort island", patterns: [/mustique/i] },
      { label: "Union Island gateway", patterns: [/union island/i] },
    ],
  },
  candidates: [
    { name: "Argyle International Airport Corridor", pointType: "Future Growth Node", city: "Argyle", submarket: "Other", latitude: 13.1567, longitude: -61.1512, sourceReference: "https://www.svgairport.com/", manuallyVerified: true },
    { name: "Kingstown Cruise Ship Berth", pointType: "Mixed-Use Development", city: "Kingstown", submarket: "Kingstown", latitude: 13.1567, longitude: -61.2234, sourceReference: "https://www.discoversvg.com/", manuallyVerified: true },
    { name: "Kingstown Central Business District", pointType: "Business District", city: "Kingstown", submarket: "Kingstown", latitude: 13.1589, longitude: -61.2267, sourceReference: "https://www.discoversvg.com/" },
    { name: "Botanic Gardens St. Vincent", pointType: "Tourist Attraction", city: "Kingstown", submarket: "Kingstown", latitude: 13.1612, longitude: -61.2289, sourceReference: "https://www.discoversvg.com/" },
    { name: "Fort Charlotte Historic Site", pointType: "Tourist Attraction", city: "Kingstown", submarket: "Kingstown", latitude: 13.1623, longitude: -61.2312, sourceReference: "https://www.discoversvg.com/" },
    { name: "Milton Cato Memorial Hospital", pointType: "Medical Campus", city: "Kingstown", submarket: "Kingstown", latitude: 13.1545, longitude: -61.2189, sourceReference: "https://www.gov.vc/" },
    { name: "St. Vincent and the Grenadines Community College", pointType: "University / College", city: "Kingstown", submarket: "Kingstown", latitude: 13.1523, longitude: -61.2212, sourceReference: "https://www.gov.vc/" },
    { name: "Arnos Vale Sports Complex", pointType: "Sports Venue", city: "Kingstown", submarket: "Kingstown", latitude: 13.1489, longitude: -61.2156, sourceReference: "https://www.discoversvg.com/" },
    { name: "Villa Beach Resort Strip", pointType: "Beach / Waterfront", city: "Villa", submarket: "Kingstown", latitude: 13.1456, longitude: -61.2012, sourceReference: "https://www.discoversvg.com/" },
    { name: "Indian Bay Beach", pointType: "Beach / Waterfront", city: "Kingstown", submarket: "Kingstown", latitude: 13.1423, longitude: -61.1989, sourceReference: "https://www.discoversvg.com/" },
    { name: "Young Island Resort", pointType: "Mixed-Use Development", city: "Kingstown", submarket: "Kingstown", latitude: 13.1389, longitude: -61.2123, sourceReference: "https://www.discoversvg.com/" },
    { name: "La Soufrière Volcano National Park", pointType: "Tourist Attraction", city: "Richmond", submarket: "North Coast", latitude: 13.3345, longitude: -61.1789, sourceReference: "https://www.discoversvg.com/", manuallyVerified: true },
    { name: "Owia Salt Pond", pointType: "Tourist Attraction", city: "Owia", submarket: "North Coast", latitude: 13.3678, longitude: -61.1234, sourceReference: "https://www.discoversvg.com/" },
    { name: "Dark View Falls", pointType: "Tourist Attraction", city: "Richmond", submarket: "North Coast", latitude: 13.3123, longitude: -61.1567, sourceReference: "https://www.discoversvg.com/" },
    { name: "Falls of Baleine", pointType: "Tourist Attraction", city: "Richmond", submarket: "North Coast", latitude: 13.3789, longitude: -61.1456, sourceReference: "https://www.discoversvg.com/" },
    { name: "Bequia Tourism Gateway", pointType: "Future Growth Node", city: "Port Elizabeth", submarket: "Grenadines", latitude: 13.0123, longitude: -61.2456, sourceReference: "https://www.discoversvg.com/", manuallyVerified: true },
    { name: "Bequia Admiralty Bay Marina", pointType: "Beach / Waterfront", city: "Port Elizabeth", submarket: "Grenadines", latitude: 13.0089, longitude: -61.2412, sourceReference: "https://www.discoversvg.com/" },
    { name: "Princess Margaret Beach Bequia", pointType: "Beach / Waterfront", city: "Port Elizabeth", submarket: "Grenadines", latitude: 13.0067, longitude: -61.2389, sourceReference: "https://www.discoversvg.com/" },
    { name: "Mustique Island Resort Zone", pointType: "Mixed-Use Development", city: "Mustique", submarket: "Grenadines", latitude: 12.8789, longitude: -61.1789, sourceReference: "https://www.discoversvg.com/", manuallyVerified: true },
    { name: "Canouan Island Resort Marina", pointType: "Beach / Waterfront", city: "Canouan", submarket: "Grenadines", latitude: 12.7012, longitude: -61.3234, sourceReference: "https://www.discoversvg.com/" },
    { name: "Union Island Clifton Harbour", pointType: "Beach / Waterfront", city: "Clifton", submarket: "Grenadines", latitude: 12.5989, longitude: -61.4234, sourceReference: "https://www.discoversvg.com/" },
    { name: "Palm Island Resort", pointType: "Mixed-Use Development", city: "Palm Island", submarket: "Grenadines", latitude: 12.5789, longitude: -61.3912, sourceReference: "https://www.discoversvg.com/" },
    { name: "Mayreau Salt Whistle Bay", pointType: "Beach / Waterfront", city: "Mayreau", submarket: "Grenadines", latitude: 12.6456, longitude: -61.3912, sourceReference: "https://www.discoversvg.com/" },
    { name: "Tobago Cays Marine Park", pointType: "Tourist Attraction", city: "Tobago Cays", submarket: "Grenadines", latitude: 12.6234, longitude: -61.3567, sourceReference: "https://www.discoversvg.com/", manuallyVerified: true },
    { name: "Petit St. Vincent Private Island Resort", pointType: "Mixed-Use Development", city: "Petit St. Vincent", submarket: "Grenadines", latitude: 12.5234, longitude: -61.3789, sourceReference: "https://www.discoversvg.com/" },
    { name: "Chateaubelair Fishing Village", pointType: "Tourist Attraction", city: "Chateaubelair", submarket: "North Coast", latitude: 13.2912, longitude: -61.2456, sourceReference: "https://www.discoversvg.com/" },
    { name: "Barrouallie Fishing Village", pointType: "Beach / Waterfront", city: "Barrouallie", submarket: "Other", latitude: 13.2234, longitude: -61.2678, sourceReference: "https://www.discoversvg.com/" },
    { name: "Layou Petroglyph Park", pointType: "Tourist Attraction", city: "Layou", submarket: "Other", latitude: 13.2123, longitude: -61.2567, sourceReference: "https://www.discoversvg.com/" },
    { name: "Buccament Bay Resort Corridor", pointType: "Beach / Waterfront", city: "Buccament", submarket: "Other", latitude: 13.1789, longitude: -61.2678, sourceReference: "https://www.discoversvg.com/" },
    { name: "Georgetown Market District", pointType: "Entertainment District", city: "Georgetown", submarket: "Other", latitude: 13.2789, longitude: -61.1234, sourceReference: "https://www.discoversvg.com/" },
    { name: "Mesopotamia Valley Agriculture Tourism", pointType: "Tourist Attraction", city: "Mesopotamia", submarket: "Other", latitude: 13.2012, longitude: -61.2123, sourceReference: "https://www.discoversvg.com/" },
    { name: "Invest SVG Business Precinct", pointType: "Government / Civic Center", city: "Kingstown", submarket: "Kingstown", latitude: 13.1578, longitude: -61.2245, sourceReference: "https://www.investsvg.com/" },
    { name: "Kingstown Market Vendors District", pointType: "Entertainment District", city: "Kingstown", submarket: "Kingstown", latitude: 13.1598, longitude: -61.2278, sourceReference: "https://www.discoversvg.com/" },
    { name: "Blue Lagoon Marina St. Vincent", pointType: "Beach / Waterfront", city: "Kingstown", submarket: "Kingstown", latitude: 13.1345, longitude: -61.1934, sourceReference: "https://www.discoversvg.com/" },
    { name: "Grenadines Yacht Charter Hub", pointType: "Future Growth Node", city: "Port Elizabeth", submarket: "Grenadines", latitude: 13.0112, longitude: -61.2434, sourceReference: "https://www.discoversvg.com/" },
    { name: "St. Vincent Conference Centre", pointType: "Convention Center", city: "Kingstown", submarket: "Kingstown", latitude: 13.1556, longitude: -61.2201, sourceReference: "https://www.discoversvg.com/" },
    { name: "Calliaqua Industrial Zone", pointType: "Industrial / Logistics Zone", city: "Calliaqua", submarket: "Kingstown", latitude: 13.1289, longitude: -61.1912, sourceReference: "https://www.gov.vc/" },
    { name: "Wallilabou Bay Pirates of the Caribbean Site", pointType: "Tourist Attraction", city: "Wallilabou", submarket: "North Coast", latitude: 13.2567, longitude: -61.2567, sourceReference: "https://www.discoversvg.com/" },
    { name: "Argyle South Coast Growth Node", pointType: "Future Growth Node", city: "Argyle", submarket: "Other", latitude: 13.1512, longitude: -61.1489, sourceReference: "https://www.investsvg.com/" },
  ],
  tiRecords: [
    { name: "Argyle International Airport Access", pointType: "Highway Access", pointSubtype: "Airport Access", city: "Argyle", submarket: "Other", latitude: 13.1567, longitude: -61.1512, sourceReference: "https://www.svgairport.com/", notes: "Primary international gateway since 2017." },
    { name: "Kingstown Cruise Berth Access", pointType: "Port / Maritime", pointSubtype: "Cruise Terminal", city: "Kingstown", submarket: "Kingstown", latitude: 13.1567, longitude: -61.2234, sourceReference: "https://www.discoversvg.com/", notes: "Capital cruise berth access.", useCaseTags: ["Cruise / Port", "Resort / Leisure"] },
    { name: "Bequia Ferry and Marina Access", pointType: "Ferry Terminal", pointSubtype: "Inter-Island Ferry", city: "Port Elizabeth", submarket: "Grenadines", latitude: 13.0123, longitude: -61.2456, sourceReference: "https://www.discoversvg.com/", notes: "Main Grenadines ferry and yacht gateway." },
    { name: "Admiralty Bay Marina Access", pointType: "Port / Maritime", pointSubtype: "Marina", city: "Port Elizabeth", submarket: "Grenadines", latitude: 13.0089, longitude: -61.2412, sourceReference: "https://www.discoversvg.com/", notes: "Bequia marina supporting sailing tourism.", useCaseTags: ["Cruise / Port", "Resort / Leisure"] },
    { name: "Canouan Airport and Marina Connector", pointType: "Highway Access", pointSubtype: "Airport-Resort Corridor", city: "Canouan", submarket: "Grenadines", latitude: 12.7012, longitude: -61.3234, sourceReference: "https://www.discoversvg.com/", notes: "Grenadines resort island air and marina access." },
    { name: "Union Island Clifton Harbour Access", pointType: "Ferry Terminal", pointSubtype: "Harbour Access", city: "Clifton", submarket: "Grenadines", latitude: 12.5989, longitude: -61.4234, sourceReference: "https://www.discoversvg.com/", notes: "Southern Grenadines harbour and inter-island ferry node." },
    { name: "Kingstown Waterfront Access", pointType: "Highway Access", pointSubtype: "Waterfront Corridor", city: "Kingstown", submarket: "Kingstown", latitude: 13.1589, longitude: -61.2267, sourceReference: "https://www.discoversvg.com/", notes: "Capital waterfront and market district access." },
    { name: "Calliaqua Industrial Zone Access", pointType: "Highway Access", pointSubtype: "Industrial Corridor", city: "Calliaqua", submarket: "Kingstown", latitude: 13.1289, longitude: -61.1912, sourceReference: "https://www.gov.vc/", notes: "South coast industrial connector.", useCaseTags: ["Industrial / Logistics", "Airport / Transit"] },
  ],
  googleCorrections: {},
};
