/** @type {import("./island-build-types.js").IslandBuildSpec} */
export const SAINT_KITTS_AND_NEVIS_BUILD = {
  slug: "saint-kitts-and-nevis",
  country: "Saint Kitts and Nevis",
  sequence: 22,
  market: "Saint Kitts and Nevis Countrywide",
  submarkets: ["Basseterre", "Frigate Bay", "Nevis", "Other"],
  notes: "Basseterre cruise/civic; Frigate Bay resort strip; Nevis heritage/luxury secondary island.",
  tourismUrl: "https://www.stkittstourism.kn/",
  microPass: {
    names: [],
    rules: [{ base: ["https://www.stkittstourism.kn/", "https://www.stkittstourism.kn"], template: "https://www.stkittstourism.kn/places/{key}" }],
  },
  audit: {
    keywords: ["saint kitts", "st kitts", "nevis", "basseterre", "frigate bay", "robert bradshaw", "skb", "cruise", "brimstone hill", "charlestown"],
    expectedPatterns: [
      { label: "Robert L. Bradshaw Airport / SKB", patterns: [/robert.*bradshaw/i, /\bSKB\b/i] },
      { label: "Basseterre cruise port", patterns: [/basseterre.*cruise/i, /port zante/i] },
      { label: "Frigate Bay resort corridor", patterns: [/frigate bay/i] },
      { label: "Brimstone Hill Fortress", patterns: [/brimstone hill/i] },
      { label: "Nevis Vance Amory Airport", patterns: [/vance amory/i, /\bNEV\b/i] },
    ],
  },
  candidates: [
    { name: "Robert L. Bradshaw International Airport Corridor", pointType: "Future Growth Node", city: "Basseterre", submarket: "Basseterre", latitude: 17.3112, longitude: -62.7189, sourceReference: "https://www.stkittstourism.kn/", manuallyVerified: true },
    { name: "Port Zante Cruise Terminal", pointType: "Mixed-Use Development", city: "Basseterre", submarket: "Basseterre", latitude: 17.2967, longitude: -62.7234, sourceReference: "https://www.stkittstourism.kn/", manuallyVerified: true },
    { name: "Basseterre Central Business District", pointType: "Business District", city: "Basseterre", submarket: "Basseterre", latitude: 17.2956, longitude: -62.7267, sourceReference: "https://www.stkittstourism.kn/" },
    { name: "Independence Square Basseterre", pointType: "Government / Civic Center", city: "Basseterre", submarket: "Basseterre", latitude: 17.2945, longitude: -62.7289, sourceReference: "https://www.stkittstourism.kn/" },
    { name: "St. Kitts National Museum", pointType: "Tourist Attraction", city: "Basseterre", submarket: "Basseterre", latitude: 17.2934, longitude: -62.7278, sourceReference: "https://www.stkittstourism.kn/" },
    { name: "Joseph N. France General Hospital", pointType: "Medical Campus", city: "Basseterre", submarket: "Basseterre", latitude: 17.2912, longitude: -62.7312, sourceReference: "https://www.gov.kn/" },
    { name: "Clarence Fitzroy Bryant College", pointType: "University / College", city: "Basseterre", submarket: "Basseterre", latitude: 17.2889, longitude: -62.7234, sourceReference: "https://www.gov.kn/" },
    { name: "Warner Park Cricket Stadium", pointType: "Sports Venue", city: "Basseterre", submarket: "Basseterre", latitude: 17.3012, longitude: -62.7189, sourceReference: "https://www.stkittstourism.kn/" },
    { name: "Brimstone Hill Fortress UNESCO", pointType: "Tourist Attraction", city: "Sandy Point", submarket: "Other", latitude: 17.3478, longitude: -62.8345, sourceReference: "https://www.stkittstourism.kn/", manuallyVerified: true },
    { name: "Frigate Bay Resort Beach Strip", pointType: "Beach / Waterfront", city: "Frigate Bay", submarket: "Frigate Bay", latitude: 17.2789, longitude: -62.6789, sourceReference: "https://www.stkittstourism.kn/", manuallyVerified: true },
    { name: "South Frigate Bay Beach", pointType: "Beach / Waterfront", city: "Frigate Bay", submarket: "Frigate Bay", latitude: 17.2767, longitude: -62.6767, sourceReference: "https://www.stkittstourism.kn/" },
    { name: "North Frigate Bay Beach", pointType: "Beach / Waterfront", city: "Frigate Bay", submarket: "Frigate Bay", latitude: 17.2812, longitude: -62.6812, sourceReference: "https://www.stkittstourism.kn/" },
    { name: "St. Kitts Marriott Resort Zone", pointType: "Mixed-Use Development", city: "Frigate Bay", submarket: "Frigate Bay", latitude: 17.2801, longitude: -62.6798, sourceReference: "https://www.stkittstourism.kn/" },
    { name: "Christophe Harbour Marina", pointType: "Beach / Waterfront", city: "Basseterre", submarket: "Frigate Bay", latitude: 17.2567, longitude: -62.6234, sourceReference: "https://www.stkittstourism.kn/" },
    { name: "Sandy Point National Marine Park", pointType: "Tourist Attraction", city: "Sandy Point", submarket: "Other", latitude: 17.3567, longitude: -62.8512, sourceReference: "https://www.stkittstourism.kn/" },
    { name: "Black Rocks Formation", pointType: "Tourist Attraction", city: "Saddlers", submarket: "Other", latitude: 17.3678, longitude: -62.7789, sourceReference: "https://www.stkittstourism.kn/" },
    { name: "Romney Manor and Caribelle Batik", pointType: "Tourist Attraction", city: "Old Road", submarket: "Other", latitude: 17.3234, longitude: -62.8012, sourceReference: "https://www.stkittstourism.kn/" },
    { name: "St. Kitts Scenic Railway", pointType: "Tourist Attraction", city: "Basseterre", submarket: "Basseterre", latitude: 17.2989, longitude: -62.7212, sourceReference: "https://www.stkittstourism.kn/" },
    { name: "Fairview Great House and Botanical Garden", pointType: "Tourist Attraction", city: "Basseterre", submarket: "Other", latitude: 17.3123, longitude: -62.7456, sourceReference: "https://www.stkittstourism.kn/" },
    { name: "Nevis Tourism Gateway Charlestown", pointType: "Future Growth Node", city: "Charlestown", submarket: "Nevis", latitude: 17.1456, longitude: -62.6234, sourceReference: "https://www.stkittstourism.kn/", manuallyVerified: true },
    { name: "Vance W. Amory International Airport Nevis", pointType: "Future Growth Node", city: "Newcastle", submarket: "Nevis", latitude: 17.2012, longitude: -62.5934, sourceReference: "https://www.stkittstourism.kn/", manuallyVerified: true },
    { name: "Pinney's Beach Nevis", pointType: "Beach / Waterfront", city: "Charlestown", submarket: "Nevis", latitude: 17.1512, longitude: -62.6189, sourceReference: "https://www.stkittstourism.kn/" },
    { name: "Four Seasons Resort Nevis", pointType: "Mixed-Use Development", city: "Charlestown", submarket: "Nevis", latitude: 17.1678, longitude: -62.6012, sourceReference: "https://www.stkittstourism.kn/" },
    { name: "Nevis Peak Trailhead", pointType: "Tourist Attraction", city: "Gingerland", submarket: "Nevis", latitude: 17.1567, longitude: -62.5789, sourceReference: "https://www.stkittstourism.kn/" },
    { name: "Bath Spring Historic Site Nevis", pointType: "Tourist Attraction", city: "Charlestown", submarket: "Nevis", latitude: 17.1423, longitude: -62.6267, sourceReference: "https://www.stkittstourism.kn/" },
    { name: "Alexander Hamilton Museum Nevis", pointType: "Tourist Attraction", city: "Charlestown", submarket: "Nevis", latitude: 17.1434, longitude: -62.6256, sourceReference: "https://www.stkittstourism.kn/" },
    { name: "Nevis Botanical Gardens", pointType: "Tourist Attraction", city: "Charlestown", submarket: "Nevis", latitude: 17.1612, longitude: -62.6123, sourceReference: "https://www.stkittstourism.kn/" },
    { name: "Oualie Beach Resort Nevis", pointType: "Beach / Waterfront", city: "Oualie", submarket: "Nevis", latitude: 17.1789, longitude: -62.5934, sourceReference: "https://www.stkittstourism.kn/" },
    { name: "St. Kitts Ferry Terminal", pointType: "Future Growth Node", city: "Basseterre", submarket: "Basseterre", latitude: 17.2978, longitude: -62.7245, sourceReference: "https://www.stkittstourism.kn/" },
    { name: "Carambola Beach Club", pointType: "Beach / Waterfront", city: "St. Paul's", submarket: "Other", latitude: 17.3456, longitude: -62.8123, sourceReference: "https://www.stkittstourism.kn/" },
    { name: "Turtle Beach St. Kitts", pointType: "Beach / Waterfront", city: "Southeast Peninsula", submarket: "Frigate Bay", latitude: 17.2512, longitude: -62.6567, sourceReference: "https://www.stkittstourism.kn/" },
    { name: "South East Peninsula Growth Corridor", pointType: "Future Growth Node", city: "Southeast Peninsula", submarket: "Frigate Bay", latitude: 17.2456, longitude: -62.6489, sourceReference: "https://www.investstkitts.kn/" },
    { name: "St. Kitts Economic Citizenship Investment Zone", pointType: "Government / Civic Center", city: "Basseterre", submarket: "Basseterre", latitude: 17.2923, longitude: -62.7256, sourceReference: "https://www.investstkitts.kn/" },
    { name: "Kennedy Avenue Entertainment District", pointType: "Entertainment District", city: "Basseterre", submarket: "Basseterre", latitude: 17.2941, longitude: -62.7298, sourceReference: "https://www.stkittstourism.kn/" },
    { name: "Dieppe Bay Fishing Village", pointType: "Tourist Attraction", city: "Dieppe Bay", submarket: "Other", latitude: 17.4123, longitude: -62.8234, sourceReference: "https://www.stkittstourism.kn/" },
    { name: "St. Kitts Industrial Site", pointType: "Industrial / Logistics Zone", city: "Basseterre", submarket: "Basseterre", latitude: 17.2867, longitude: -62.7345, sourceReference: "https://www.gov.kn/" },
    { name: "St. Kitts Convention Centre", pointType: "Convention Center", city: "Frigate Bay", submarket: "Frigate Bay", latitude: 17.2798, longitude: -62.6778, sourceReference: "https://www.stkittstourism.kn/" },
    { name: "Mount Liamuiga Volcano Trail", pointType: "Tourist Attraction", city: "St. Paul's", submarket: "Other", latitude: 17.3789, longitude: -62.8012, sourceReference: "https://www.stkittstourism.kn/" },
    { name: "Nevis Heritage Trail Charlestown", pointType: "Tourist Attraction", city: "Charlestown", submarket: "Nevis", latitude: 17.1445, longitude: -62.6245, sourceReference: "https://www.stkittstourism.kn/" },
  ],
  tiRecords: [
    { name: "Robert L. Bradshaw International Airport Access", pointType: "Highway Access", pointSubtype: "Airport Access", city: "Basseterre", submarket: "Basseterre", latitude: 17.3112, longitude: -62.7189, sourceReference: "https://www.stkittstourism.kn/", notes: "Primary international gateway for St. Kitts." },
    { name: "Port Zante Cruise Terminal Access", pointType: "Port / Maritime", pointSubtype: "Cruise Terminal", city: "Basseterre", submarket: "Basseterre", latitude: 17.2967, longitude: -62.7234, sourceReference: "https://www.stkittstourism.kn/", notes: "Main cruise terminal in Basseterre harbour.", useCaseTags: ["Cruise / Port", "Resort / Leisure"] },
    { name: "Frigate Bay Resort Corridor Access", pointType: "Highway Access", pointSubtype: "Resort Corridor", city: "Frigate Bay", submarket: "Frigate Bay", latitude: 17.2789, longitude: -62.6789, sourceReference: "https://www.stkittstourism.kn/", notes: "Primary resort beach strip road access." },
    { name: "Christophe Harbour Marina Access", pointType: "Port / Maritime", pointSubtype: "Marina", city: "Basseterre", submarket: "Frigate Bay", latitude: 17.2567, longitude: -62.6234, sourceReference: "https://www.stkittstourism.kn/", notes: "Luxury marina on south-east peninsula.", useCaseTags: ["Cruise / Port", "Resort / Leisure"] },
    { name: "St. Kitts Nevis Ferry Terminal Access", pointType: "Ferry Terminal", pointSubtype: "Inter-Island Ferry", city: "Basseterre", submarket: "Basseterre", latitude: 17.2978, longitude: -62.7245, sourceReference: "https://www.stkittstourism.kn/", notes: "Ferry link between St. Kitts and Nevis." },
    { name: "Vance W. Amory Airport Nevis Access", pointType: "Highway Access", pointSubtype: "Airport Access", city: "Newcastle", submarket: "Nevis", latitude: 17.2012, longitude: -62.5934, sourceReference: "https://www.stkittstourism.kn/", notes: "Nevis island air gateway." },
    { name: "Charlestown Nevis Waterfront Access", pointType: "Highway Access", pointSubtype: "Waterfront Corridor", city: "Charlestown", submarket: "Nevis", latitude: 17.1456, longitude: -62.6234, sourceReference: "https://www.stkittstourism.kn/", notes: "Nevis capital waterfront and heritage access." },
    { name: "Basseterre Deep Water Port Access", pointType: "Port / Maritime", pointSubtype: "Commercial Port", city: "Basseterre", submarket: "Basseterre", latitude: 17.2912, longitude: -62.7312, sourceReference: "https://www.gov.kn/", notes: "Cargo port supporting business travel.", useCaseTags: ["Industrial / Logistics", "Airport / Transit"] },
  ],
  googleCorrections: {},
};
