/** @typedef {import("./island-build-types.js").IslandBuildSpec} IslandBuildSpec */

/** @type {IslandBuildSpec} */
export const SAINT_LUCIA_BUILD = {
  slug: "saint-lucia",
  country: "Saint Lucia",
  sequence: 17,
  market: "Saint Lucia Countrywide",
  submarkets: ["Castries", "Rodney Bay / Gros Islet", "Soufrière", "Vieux Fort", "Other"],
  notes: "Castries cruise/civic anchor; Rodney Bay resort corridor; Pitons/Soufrière leisure; Vieux Fort airport south.",
  tourismUrl: "https://www.stlucia.org/",
  microPass: {
    names: [],
    rules: [{ base: ["https://www.stlucia.org/", "https://www.stlucia.org"], template: "https://www.stlucia.org/places/{key}" }],
  },
  audit: {
    keywords: ["saint lucia", "stlucia", "castries", "rodney bay", "gros islet", "soufriere", "vieux fort", "hewanorra", "uvf", "pitons", "marigot", "cruise", "reduit"],
    expectedPatterns: [
      { label: "Hewanorra International Airport / UVF", patterns: [/hewanorra/i, /\bUVF\b/i] },
      { label: "George F. L. Charles Airport / SLU", patterns: [/george f\.? l\.? charles/i, /\bSLU\b/i] },
      { label: "Castries cruise port", patterns: [/castries.*cruise/i, /port.*castries/i] },
      { label: "Rodney Bay resort corridor", patterns: [/rodney bay/i, /reduit beach/i] },
      { label: "Soufrière Pitons corridor", patterns: [/pitons/i, /soufri[eè]re/i] },
      { label: "Marigot Bay access", patterns: [/marigot bay/i] },
      { label: "Vieux Fort south gateway", patterns: [/vieux fort/i] },
    ],
  },
  candidates: [
    { name: "Hewanorra International Airport Corridor", pointType: "Future Growth Node", city: "Vieux Fort", submarket: "Vieux Fort", latitude: 13.7332, longitude: -60.9526, sourceReference: "https://www.slulimited.com/", manuallyVerified: true },
    { name: "George F. L. Charles Airport", pointType: "Future Growth Node", city: "Castries", submarket: "Castries", latitude: 14.0202, longitude: -60.9929, sourceReference: "https://www.slulimited.com/", manuallyVerified: true },
    { name: "Port of Castries Cruise Terminal", pointType: "Mixed-Use Development", city: "Castries", submarket: "Castries", latitude: 14.0107, longitude: -60.9915, sourceReference: "https://www.stlucia.org/", manuallyVerified: true },
    { name: "Castries Central Business District", pointType: "Business District", city: "Castries", submarket: "Castries", latitude: 14.0101, longitude: -60.9895, sourceReference: "https://www.stlucia.org/" },
    { name: "Duty Free Pointe Seraphine", pointType: "Entertainment District", city: "Castries", submarket: "Castries", latitude: 14.0139, longitude: -60.9878, sourceReference: "https://www.stlucia.org/" },
    { name: "OECS Commission Headquarters Precinct", pointType: "Government / Civic Center", city: "Castries", submarket: "Castries", latitude: 14.0078, longitude: -60.9934, sourceReference: "https://www.oecs.org/" },
    { name: "Owen King EU Hospital", pointType: "Medical Campus", city: "Castries", submarket: "Castries", latitude: 14.0056, longitude: -60.9789, sourceReference: "https://www.stlucia.gov.lc/" },
    { name: "Sir Arthur Lewis Community College", pointType: "University / College", city: "Castries", submarket: "Castries", latitude: 14.0189, longitude: -60.9812, sourceReference: "https://www.salcc.edu.lc/" },
    { name: "Daren Sammy Cricket Ground", pointType: "Sports Venue", city: "Gros Islet", submarket: "Rodney Bay / Gros Islet", latitude: 14.0689, longitude: -60.9534, sourceReference: "https://www.stlucia.org/" },
    { name: "Rodney Bay Marina", pointType: "Beach / Waterfront", city: "Rodney Bay", submarket: "Rodney Bay / Gros Islet", latitude: 14.0742, longitude: -60.9512, sourceReference: "https://www.stlucia.org/", manuallyVerified: true },
    { name: "Reduit Beach Resort Corridor", pointType: "Beach / Waterfront", city: "Rodney Bay", submarket: "Rodney Bay / Gros Islet", latitude: 14.0789, longitude: -60.9498, sourceReference: "https://www.stlucia.org/", manuallyVerified: true },
    { name: "Pigeon Island National Landmark", pointType: "Tourist Attraction", city: "Gros Islet", submarket: "Rodney Bay / Gros Islet", latitude: 14.0923, longitude: -60.9612, sourceReference: "https://www.stlucia.org/" },
    { name: "Gros Islet Friday Night Street Party", pointType: "Entertainment District", city: "Gros Islet", submarket: "Rodney Bay / Gros Islet", latitude: 14.0798, longitude: -60.9456, sourceReference: "https://www.stlucia.org/" },
    { name: "Cap Estate Golf and Resort Zone", pointType: "Mixed-Use Development", city: "Cap Estate", submarket: "Rodney Bay / Gros Islet", latitude: 14.1012, longitude: -60.9478, sourceReference: "https://www.stlucia.org/" },
    { name: "Atlantic Rally for Cruisers Finish", pointType: "Future Growth Node", city: "Rodney Bay", submarket: "Rodney Bay / Gros Islet", latitude: 14.0756, longitude: -60.9523, sourceReference: "https://www.stlucia.org/" },
    { name: "Marigot Bay Heritage Harbour", pointType: "Tourist Attraction", city: "Marigot Bay", submarket: "Other", latitude: 13.9478, longitude: -61.0267, sourceReference: "https://www.stlucia.org/", manuallyVerified: true },
    { name: "Pitons Management Area UNESCO", pointType: "Tourist Attraction", city: "Soufrière", submarket: "Soufrière", latitude: 13.8089, longitude: -61.0678, sourceReference: "https://www.stlucia.org/", manuallyVerified: true },
    { name: "Soufrière Town Waterfront", pointType: "Beach / Waterfront", city: "Soufrière", submarket: "Soufrière", latitude: 13.8567, longitude: -61.0567, sourceReference: "https://www.stlucia.org/" },
    { name: "Sulphur Springs Drive-In Volcano", pointType: "Tourist Attraction", city: "Soufrière", submarket: "Soufrière", latitude: 13.8412, longitude: -61.0456, sourceReference: "https://www.stlucia.org/" },
    { name: "Diamond Falls Botanical Gardens", pointType: "Tourist Attraction", city: "Soufrière", submarket: "Soufrière", latitude: 13.8534, longitude: -61.0512, sourceReference: "https://www.stlucia.org/" },
    { name: "Anse Chastanet Resort Beach", pointType: "Beach / Waterfront", city: "Soufrière", submarket: "Soufrière", latitude: 13.8623, longitude: -61.0789, sourceReference: "https://www.stlucia.org/" },
    { name: "Sugar Beach Pitons View Corridor", pointType: "Beach / Waterfront", city: "Soufrière", submarket: "Soufrière", latitude: 13.8645, longitude: -61.0756, sourceReference: "https://www.stlucia.org/" },
    { name: "Fond Doux Plantation Resort", pointType: "Tourist Attraction", city: "Soufrière", submarket: "Soufrière", latitude: 13.8489, longitude: -61.0389, sourceReference: "https://www.stlucia.org/" },
    { name: "Vieux Fort Industrial Free Zone", pointType: "Industrial / Logistics Zone", city: "Vieux Fort", submarket: "Vieux Fort", latitude: 13.7289, longitude: -60.9612, sourceReference: "https://www.stlucia.gov.lc/" },
    { name: "Micoud Bay Fishing Village", pointType: "Beach / Waterfront", city: "Micoud", submarket: "Other", latitude: 13.8123, longitude: -60.9012, sourceReference: "https://www.stlucia.org/" },
    { name: "Dennery Fishing Village East Coast", pointType: "Beach / Waterfront", city: "Dennery", submarket: "Other", latitude: 13.9012, longitude: -60.8934, sourceReference: "https://www.stlucia.org/" },
    { name: "Choiseul Heritage Coast", pointType: "Tourist Attraction", city: "Choiseul", submarket: "Other", latitude: 13.7723, longitude: -61.0456, sourceReference: "https://www.stlucia.org/" },
    { name: "Laborie Bay South Coast", pointType: "Beach / Waterfront", city: "Laborie", submarket: "Other", latitude: 13.7512, longitude: -60.9934, sourceReference: "https://www.stlucia.org/" },
    { name: "Canaries Fishing Village", pointType: "Tourist Attraction", city: "Canaries", submarket: "Other", latitude: 13.9012, longitude: -61.0623, sourceReference: "https://www.stlucia.org/" },
    { name: "Saint Lucia Conference Centre", pointType: "Convention Center", city: "Rodney Bay", submarket: "Rodney Bay / Gros Islet", latitude: 14.0723, longitude: -60.9534, sourceReference: "https://www.stlucia.org/" },
    { name: "Baywalk Shopping Plaza Rodney Bay", pointType: "Entertainment District", city: "Rodney Bay", submarket: "Rodney Bay / Gros Islet", latitude: 14.0767, longitude: -60.9501, sourceReference: "https://www.stlucia.org/" },
    { name: "Windward Islands Research and Education Foundation", pointType: "University / College", city: "Soufrière", submarket: "Soufrière", latitude: 13.8578, longitude: -61.0545, sourceReference: "https://www.stlucia.org/" },
    { name: "Saint Lucia South Coast Growth Node", pointType: "Future Growth Node", city: "Vieux Fort", submarket: "Vieux Fort", latitude: 13.7267, longitude: -60.9489, sourceReference: "https://www.investstlucia.com/", manuallyVerified: true },
    { name: "Rodney Bay Resort Expansion Corridor", pointType: "Future Growth Node", city: "Rodney Bay", submarket: "Rodney Bay / Gros Islet", latitude: 14.0812, longitude: -60.9478, sourceReference: "https://www.investstlucia.com/" },
    { name: "Castries Waterfront Redevelopment", pointType: "Mixed-Use Development", city: "Castries", submarket: "Castries", latitude: 14.0098, longitude: -60.9889, sourceReference: "https://www.investstlucia.com/" },
    { name: "Anse La Raye Fish Fry", pointType: "Entertainment District", city: "Anse La Raye", submarket: "Other", latitude: 13.9456, longitude: -61.0389, sourceReference: "https://www.stlucia.org/" },
    { name: "Babonneau Community Tourism Corridor", pointType: "Tourist Attraction", city: "Babonneau", submarket: "Other", latitude: 14.0123, longitude: -60.9234, sourceReference: "https://www.stlucia.org/" },
    { name: "Ti Rocher Rainforest Adventure Zone", pointType: "Tourist Attraction", city: "Castries", submarket: "Other", latitude: 13.9789, longitude: -60.9678, sourceReference: "https://www.stlucia.org/" },
    { name: "Saint Lucia National Stadium Precinct", pointType: "Sports Venue", city: "Bisee", submarket: "Castries", latitude: 14.0234, longitude: -60.9712, sourceReference: "https://www.stlucia.gov.lc/" },
  ],
  tiRecords: [
    { name: "Hewanorra International Airport Access", pointType: "Highway Access", pointSubtype: "Airport Access", city: "Vieux Fort", submarket: "Vieux Fort", latitude: 13.7332, longitude: -60.9526, sourceReference: "https://www.slulimited.com/", notes: "Primary long-haul stayover gateway for south Saint Lucia resort demand." },
    { name: "George F. L. Charles Airport Access", pointType: "Highway Access", pointSubtype: "Airport Access", city: "Castries", submarket: "Castries", latitude: 14.0202, longitude: -60.9929, sourceReference: "https://www.slulimited.com/", notes: "Regional airport serving Castries and north resort corridors." },
    { name: "Castries Cruise Port Access", pointType: "Port / Maritime", pointSubtype: "Cruise Terminal", city: "Castries", submarket: "Castries", latitude: 14.0107, longitude: -60.9915, sourceReference: "https://www.stlucia.org/", notes: "Main cruise terminal supporting day-call and pre/post-stay lodging.", useCaseTags: ["Cruise / Port", "Resort / Leisure"] },
    { name: "Rodney Bay Marina Access", pointType: "Port / Maritime", pointSubtype: "Marina", city: "Rodney Bay", submarket: "Rodney Bay / Gros Islet", latitude: 14.0742, longitude: -60.9512, sourceReference: "https://www.stlucia.org/", notes: "Marina access for yacht and north-coast leisure demand.", useCaseTags: ["Cruise / Port", "Resort / Leisure"] },
    { name: "Rodney Bay Resort Corridor Access", pointType: "Highway Access", pointSubtype: "Resort Corridor", city: "Rodney Bay", submarket: "Rodney Bay / Gros Islet", latitude: 14.0789, longitude: -60.9498, sourceReference: "https://www.stlucia.org/", notes: "Primary road access serving Reduit Beach resort inventory." },
    { name: "Soufrière Pitons Scenic Corridor Access", pointType: "Highway Access", pointSubtype: "Scenic Corridor", city: "Soufrière", submarket: "Soufrière", latitude: 13.8567, longitude: -61.0567, sourceReference: "https://www.stlucia.org/", notes: "West coast scenic access linking Pitons resort and heritage demand." },
    { name: "Marigot Bay Ferry and Harbour Access", pointType: "Ferry Terminal", pointSubtype: "Harbour Access", city: "Marigot Bay", submarket: "Other", latitude: 13.9478, longitude: -61.0267, sourceReference: "https://www.stlucia.org/", notes: "Harbour and water-taxi access for Marigot Bay boutique resort demand." },
    { name: "Vieux Fort Industrial Free Zone Access", pointType: "Highway Access", pointSubtype: "Industrial Corridor", city: "Vieux Fort", submarket: "Vieux Fort", latitude: 13.7289, longitude: -60.9612, sourceReference: "https://www.stlucia.gov.lc/", notes: "South gateway industrial connector supporting business travel.", useCaseTags: ["Industrial / Logistics", "Airport / Transit"] },
  ],
  googleCorrections: {},
};
