/**
 * International Controller Outreach Pilot V1 — enums only.
 * Does not change Ready/Watch gates. Does not send email.
 */

export const ICO_VERSION = "gdi_international_controller_outreach_v1";

export const CONTACT_AUTHORITY = Object.freeze({
  HIGH_AUTHORITY: "HIGH_AUTHORITY",
  FUNCTIONALLY_RELEVANT: "FUNCTIONALLY_RELEVANT",
  PLAUSIBLE: "PLAUSIBLE",
  WEAK: "WEAK",
  UNCONFIRMED: "UNCONFIRMED",
});

export const CONTACT_CHANNEL = Object.freeze({
  NAMED_EMAIL: "NAMED_EMAIL",
  FUNCTIONAL_EMAIL: "FUNCTIONAL_EMAIL",
  PCO_EMAIL: "PCO_EMAIL",
  SECRETARIAT_EMAIL: "SECRETARIAT_EMAIL",
  OFFICIAL_CONTACT_FORM: "OFFICIAL_CONTACT_FORM",
  PHONE: "PHONE",
  OTHER: "OTHER",
});

export const OUTREACH_OBJECTIVE = Object.freeze({
  HOTEL_LIST_STATUS: "HOTEL_LIST_STATUS",
  HOTEL_ELIGIBILITY: "HOTEL_ELIGIBILITY",
  RATE_SUBMISSION: "RATE_SUBMISSION",
  ROOM_BLOCK_PROCESS: "ROOM_BLOCK_PROCESS",
  PREFERRED_HOTEL_PROGRAM: "PREFERRED_HOTEL_PROGRAM",
  SELECTION_TIMING: "SELECTION_TIMING",
  HOUSING_CONTROLLER: "HOUSING_CONTROLLER",
});

export const OUTREACH_READINESS = Object.freeze({
  READY_TO_SEND: "READY_TO_SEND",
  NEEDS_CONTACT_RESEARCH: "NEEDS_CONTACT_RESEARCH",
  WAIT_FOR_PUBLICATION: "WAIT_FOR_PUBLICATION",
  DO_NOT_PURSUE: "DO_NOT_PURSUE",
});

/** Controller-outreach response classification (maps into selection/lodging facts). */
export const CONTROLLER_RESPONSE_STATUS = Object.freeze({
  NO_RESPONSE: "NO_RESPONSE",
  NEEDS_FOLLOW_UP: "NEEDS_FOLLOW_UP",
  CONTROLLER_REDIRECT: "CONTROLLER_REDIRECT",
  HOTEL_LIST_OPEN: "HOTEL_LIST_OPEN",
  HOTEL_LIST_NOT_YET_OPEN: "HOTEL_LIST_NOT_YET_OPEN",
  HOTEL_LIST_FINALIZED: "HOTEL_LIST_FINALIZED",
  TARGET_HOTEL_CAN_APPLY: "TARGET_HOTEL_CAN_APPLY",
  TARGET_HOTEL_ADDED: "TARGET_HOTEL_ADDED",
  TARGET_HOTEL_REJECTED: "TARGET_HOTEL_REJECTED",
  RATE_REQUESTED: "RATE_REQUESTED",
  PROPOSAL_REQUESTED: "PROPOSAL_REQUESTED",
  PCO_REDIRECT: "PCO_REDIRECT",
  SELF_BOOKING_ONLY: "SELF_BOOKING_ONLY",
  NO_HOTEL_PROGRAM: "NO_HOTEL_PROGRAM",
  OTHER: "OTHER",
});

export const RESPONSE_AUTHORITY = Object.freeze({
  AUTHORITATIVE: "AUTHORITATIVE",
  STRONG: "STRONG",
  PLAUSIBLE: "PLAUSIBLE",
  WEAK: "WEAK",
});
