/**
 * Leak Audit Airtable schema mapping (Phase 2A).
 * Physical base may lag — filesystem repository mirrors these table contracts.
 *
 * Env (Leak Audit base only — never production ADP table IDs for writes):
 *   AIRTABLE_LEAK_AUDIT_BASE_ID
 *   AIRTABLE_LEAK_AUDIT_API_KEY (falls back to AIRTABLE_API_KEY / AIRTABLE_PAT)
 *   AIRTABLE_LEAK_AUDIT_TABLE_PREFIX (optional)
 */

export const LEAK_AUDIT_AIRTABLE_SCHEMA_VERSION = "adp_leak_audit_airtable_schema_v1";

export const LEAK_AUDIT_TABLE_NAMES = Object.freeze({
  AdpLeakAuditRequests: "AdpLeakAuditRequests",
  AdpLeakAuditHotels: "AdpLeakAuditHotels",
  AdpLeakAuditRuns: "AdpLeakAuditRuns",
  AdpLeakAuditMetrics: "AdpLeakAuditMetrics",
  AdpLeakAuditCompetitors: "AdpLeakAuditCompetitors",
  AdpLeakAuditEvidence: "AdpLeakAuditEvidence",
  AdpLeakAuditActions: "AdpLeakAuditActions",
  AdpLeakAuditReports: "AdpLeakAuditReports",
  AdpLeakAuditPortfolios: "AdpLeakAuditPortfolios",
  AdpLeakAuditPortfolioHotels: "AdpLeakAuditPortfolioHotels",
  AdpLeakAuditPortfolioRuns: "AdpLeakAuditPortfolioRuns",
  AdpLeakAuditPortfolioReports: "AdpLeakAuditPortfolioReports",
  AdpLeakAuditPromotions: "AdpLeakAuditPromotions",
});

/** Collection folder names under filesystem live root. */
export const LEAK_AUDIT_COLLECTIONS = Object.freeze({
  AdpLeakAuditRequests: "requests",
  AdpLeakAuditHotels: "hotels",
  AdpLeakAuditRuns: "runs",
  AdpLeakAuditMetrics: "metrics",
  AdpLeakAuditCompetitors: "competitors",
  AdpLeakAuditEvidence: "evidence",
  AdpLeakAuditActions: "actions",
  AdpLeakAuditReports: "reports",
  AdpLeakAuditPortfolios: "portfolios",
  AdpLeakAuditPortfolioHotels: "portfolio-hotels",
  AdpLeakAuditPortfolioRuns: "portfolio-runs",
  AdpLeakAuditPortfolioReports: "portfolio-reports",
  AdpLeakAuditPromotions: "promotions",
});

/**
 * Field contracts per table. `clientForbidden` must never appear in client payloads.
 */
export const LEAK_AUDIT_TABLE_FIELDS = Object.freeze({
  AdpLeakAuditRequests: {
    required: [
      "id",
      "requestType",
      "hotelName",
      "status",
      "prioritySource",
      "researchMode",
      "createdAt",
      "updatedAt",
    ],
    fields: [
      "id",
      "requestType",
      "hotelName",
      "hotelWebsite",
      "city",
      "market",
      "country",
      "portfolioName",
      "companyName",
      "contactName",
      "contactEmail",
      "role",
      "audienceType",
      "source",
      "sourceCampaign",
      "sourceUrl",
      "prioritySource",
      "optionalDemandPriority",
      "optionalCommercialPriority",
      "researchMode",
      "notes",
      "status",
      "createdAt",
      "updatedAt",
    ],
    defaults: {
      prioritySource: "inferred_from_results",
      researchMode: "leak_audit_lite",
      status: "requested",
      requestType: "single_property",
    },
  },
  AdpLeakAuditHotels: {
    required: ["id", "hotelName", "productionMatchReadOnly", "createdAt"],
    fields: [
      "id",
      "requestId",
      "portfolioId",
      "hotelName",
      "hotelWebsite",
      "city",
      "market",
      "country",
      "locationLabel",
      "shortHotelName",
      "matchedProductionHotelId",
      "matchConfidence",
      "matchBasis",
      "productionMatchReadOnly",
      "createdAt",
      "updatedAt",
    ],
    clientForbidden: ["matchedProductionHotelId"],
    defaults: { productionMatchReadOnly: true, matchConfidence: "none", matchBasis: "none" },
  },
  AdpLeakAuditRuns: {
    required: [
      "id",
      "requestId",
      "runDate",
      "status",
      "researchMode",
      "maxScenarios",
      "maxProviders",
      "maxObservations",
      "createdAt",
    ],
    fields: [
      "id",
      "requestId",
      "hotelAuditId",
      "portfolioRunId",
      "runDate",
      "providerSetVersion",
      "promptSetVersion",
      "providersUsed",
      "scenarioCount",
      "providerCount",
      "scenariosMonitoredLabel",
      "observationsLabel",
      "demandTerritoriesTested",
      "totalPromptsRun",
      "totalObservations",
      "subjectMentionCount",
      "subjectAbsentCount",
      "competitorMentionCount",
      "competitorAbsentAppearanceCount",
      "primaryAreaToReview",
      "confidenceFlag",
      "completenessFlag",
      "researchMode",
      "maxScenarios",
      "maxProviders",
      "maxObservations",
      "actualScenariosRun",
      "actualProvidersRun",
      "actualObservations",
      "estimatedProviderCost",
      "providerCostCurrency",
      "costControlNotes",
      "liveProviderCalls",
      "status",
      "errorLog",
      "createdAt",
      "updatedAt",
    ],
    defaults: {
      researchMode: "leak_audit_lite",
      maxScenarios: 15,
      maxProviders: 4,
      maxObservations: 60,
      promptSetVersion: "leak_audit_lite_v1",
      providerSetVersion: "leak_audit_provider_set_v1",
      scenariosMonitoredLabel: "15 × 4",
      observationsLabel: "60 observations",
      liveProviderCalls: 0,
    },
  },
  AdpLeakAuditMetrics: {
    required: ["id", "runId", "metricKey", "metricValue", "clientSafe"],
    requiredMetricKeys: [
      "ai_consideration",
      "scenario_presence",
      "reality_coverage",
      "leisure_advantage",
      "primary_area_to_review",
    ],
    fields: [
      "id",
      "runId",
      "hotelAuditId",
      "metricKey",
      "metricLabel",
      "metricValue",
      "metricUnit",
      "plainEnglishDefinition",
      "infoTooltipText",
      "displayOrder",
      "clientSafe",
    ],
    defaults: { clientSafe: true },
  },
  AdpLeakAuditCompetitors: {
    required: [
      "id",
      "runId",
      "competitorName",
      "appearedWhenSubjectAbsentCount",
      "clientSafe",
    ],
    fields: [
      "id",
      "runId",
      "hotelAuditId",
      "competitorName",
      "appearedWhenSubjectAbsentCount",
      "demandArea",
      "whatThisMayMean",
      "rank",
      "clientSafe",
      "createdAt",
    ],
    defaults: { clientSafe: true },
  },
  AdpLeakAuditEvidence: {
    required: ["id", "runId", "label", "clientSafe"],
    fields: [
      "id",
      "runId",
      "hotelAuditId",
      "evidenceType",
      "label",
      "headline",
      "description",
      "provider",
      "demandArea",
      "responseExcerpt",
      "sourceLinks",
      "whyItMatters",
      "managementReview",
      "displayOrder",
      "clientSafe",
      "createdAt",
    ],
    forbid: ["fullPromptText", "promptText", "promptId"],
    defaults: { clientSafe: true },
  },
  AdpLeakAuditActions: {
    required: ["id", "runId", "actionTitle", "clientSafe"],
    fields: [
      "id",
      "runId",
      "hotelAuditId",
      "actionNumber",
      "actionTitle",
      "whyItMatters",
      "dealalityCanHelpPrepare",
      "hotelConfirms",
      "sourcesNextCheck",
      "displayOrder",
      "clientSafe",
      "createdAt",
    ],
    defaults: { clientSafe: true },
  },
  AdpLeakAuditReports: {
    required: ["id", "runId", "reportStatus", "shareToken", "createdAt"],
    fields: [
      "id",
      "requestId",
      "hotelAuditId",
      "runId",
      "reportType",
      "reportStatus",
      "reportTitle",
      "hotelDisplayName",
      "locationLabel",
      "coverKicker",
      "coverReportType",
      "coverDescriptorLine",
      "coverMetaLine",
      "coverGeneratedLine",
      "coverDisclaimer",
      "executiveSummary",
      "primaryAreaToReview",
      "diagnosticScopeLabel",
      "scopeDisclaimer",
      "scenarioSummaryLabel",
      "researchMode",
      "reportUrl",
      "pdfUrl",
      "shareToken",
      "shareUrl",
      "approvedAt",
      "sentAt",
      "createdAt",
      "updatedAt",
    ],
    defaults: {
      reportType: "single_property",
      reportStatus: "draft",
      researchMode: "leak_audit_lite",
      coverMetaLine: "PROVIDERS 4 · SCENARIOS 15 · OBSERVATIONS 60 · ACTION ITEMS 3",
    },
  },
  AdpLeakAuditPortfolios: {
    required: ["id", "portfolioName", "status", "createdAt"],
    fields: [
      "id",
      "requestId",
      "portfolioName",
      "companyName",
      "contactName",
      "contactEmail",
      "audienceType",
      "source",
      "status",
      "createdAt",
      "updatedAt",
    ],
  },
  AdpLeakAuditPortfolioHotels: {
    required: ["id", "portfolioId", "hotelName", "inclusionStatus"],
    fields: [
      "id",
      "portfolioId",
      "hotelAuditId",
      "hotelName",
      "hotelWebsite",
      "city",
      "country",
      "inclusionStatus",
      "createdAt",
      "updatedAt",
    ],
  },
  AdpLeakAuditPortfolioRuns: {
    required: ["id", "portfolioId", "runDate", "status"],
    fields: [
      "id",
      "portfolioId",
      "requestId",
      "runDate",
      "hotelCount",
      "completedHotelRuns",
      "failedHotelRuns",
      "providersUsed",
      "promptSetVersion",
      "providerSetVersion",
      "researchMode",
      "mostCommonAreaToReview",
      "mostFrequentCompetitor",
      "hotelsWithPriorityAreasToReview",
      "status",
      "errorLog",
      "createdAt",
      "updatedAt",
    ],
  },
  AdpLeakAuditPortfolioReports: {
    required: ["id", "portfolioId", "portfolioRunId", "shareToken"],
    fields: [
      "id",
      "portfolioId",
      "portfolioRunId",
      "reportStatus",
      "reportUrl",
      "pdfUrl",
      "shareToken",
      "shareUrl",
      "portfolioSummary",
      "executiveSignal",
      "hotelsNeedingAttention",
      "areasToReviewMostOften",
      "competitorsShowingUpInstead",
      "portfolioPattern",
      "firstPortfolioAction",
      "secondPortfolioAction",
      "thirdPortfolioAction",
      "nextStepCta",
      "createdAt",
      "updatedAt",
      "sentAt",
    ],
  },
  AdpLeakAuditPromotions: {
    required: ["id", "requestId", "status", "createdAt"],
    fields: [
      "id",
      "requestId",
      "hotelAuditId",
      "portfolioId",
      "reportId",
      "promotionType",
      "status",
      "createdBy",
      "createdAt",
      "notes",
      "productionAdpSetupId",
      "productionAdpRecordCreated",
      "confirmed",
    ],
    defaults: {
      status: "stub",
      productionAdpRecordCreated: false,
      confirmed: false,
    },
  },
});

/** Backward-compatible contract shape used by existing tests. */
export const AIRTABLE_TABLE_CONTRACTS = Object.freeze(
  Object.fromEntries(
    Object.entries(LEAK_AUDIT_TABLE_FIELDS).map(([table, def]) => [
      table,
      {
        collection: LEAK_AUDIT_COLLECTIONS[table],
        requiredFields: def.required,
        defaults: def.defaults || {},
        clientForbiddenFields: def.clientForbidden || [],
        forbid: def.forbid || [],
        requiredMetricKeys: def.requiredMetricKeys,
        optionalFields: (def.fields || []).filter((f) => !(def.required || []).includes(f)),
      },
    ])
  )
);

export function resolveLeakAuditTableName(logicalName, prefix = process.env.AIRTABLE_LEAK_AUDIT_TABLE_PREFIX || "") {
  const base = LEAK_AUDIT_TABLE_NAMES[logicalName] || logicalName;
  return prefix ? `${prefix}${base}` : base;
}

export function listRequiredLeakAuditTables() {
  return Object.keys(LEAK_AUDIT_TABLE_NAMES);
}
