/**
 * GDI 10 Bases of Demand — HOW opportunity was found/generated.
 * Distinct from demand-engine taxonomy (WHAT type of demand).
 */

export const GDI_BASE_OF_DEMAND = Object.freeze({
  PUBLISHED_EVENT_DECOMPOSITION: "PUBLISHED_EVENT_DECOMPOSITION",
  INTERNATIONAL_ORG_RECURRING_GROUPS: "INTERNATIONAL_ORG_RECURRING_GROUPS",
  PARTICIPANT_EXHIBITOR_SPONSOR_MINING: "PARTICIPANT_EXHIBITOR_SPONSOR_MINING",
  HISTORIC_ROTATION_PREDICTION: "HISTORIC_ROTATION_PREDICTION",
  RECURRING_CORPORATE_MEETINGS: "RECURRING_CORPORATE_MEETINGS",
  CORPORATE_TRIGGER_DEMAND: "CORPORATE_TRIGGER_DEMAND",
  PHARMA_MEDICAL_ECOSYSTEM: "PHARMA_MEDICAL_ECOSYSTEM",
  PROJECT_WORKFORCE_DEMAND: "PROJECT_WORKFORCE_DEMAND",
  SPORTS_ENTERTAINMENT_PRODUCTION: "SPORTS_ENTERTAINMENT_PRODUCTION",
  HOTEL_HISTORY_LOOKALIKE: "HOTEL_HISTORY_LOOKALIKE",
});

export const BASE_OF_DEMAND_LIST = Object.freeze(Object.values(GDI_BASE_OF_DEMAND));

export const COVERAGE_STATE = Object.freeze({
  NOT_RESEARCHED: "NOT_RESEARCHED",
  LIGHT: "LIGHT",
  ADEQUATE: "ADEQUATE",
  DEEP: "DEEP",
  SATURATED: "SATURATED",
  NOT_APPLICABLE: "NOT_APPLICABLE",
});

/** Opportunity maturity — predicted is never confirmed business. */
export const OPPORTUNITY_MATURITY = Object.freeze({
  CONFIRMED_OPPORTUNITY: "CONFIRMED_OPPORTUNITY",
  PREDICTED_OPPORTUNITY: "PREDICTED_OPPORTUNITY",
  VALID_FUTURE_WATCH: "VALID_FUTURE_WATCH",
  RESEARCH_LEAD: "RESEARCH_LEAD",
  GENERATOR_INTELLIGENCE: "GENERATOR_INTELLIGENCE",
  REJECTED: "REJECTED",
});

export const BASE_LABELS = Object.freeze({
  [GDI_BASE_OF_DEMAND.PUBLISHED_EVENT_DECOMPOSITION]: "1. Published Event Decomposition",
  [GDI_BASE_OF_DEMAND.INTERNATIONAL_ORG_RECURRING_GROUPS]: "2. International Org / Recurring Groups",
  [GDI_BASE_OF_DEMAND.PARTICIPANT_EXHIBITOR_SPONSOR_MINING]: "3. Participant / Exhibitor / Sponsor Mining",
  [GDI_BASE_OF_DEMAND.HISTORIC_ROTATION_PREDICTION]: "4. Historic Rotation Prediction",
  [GDI_BASE_OF_DEMAND.RECURRING_CORPORATE_MEETINGS]: "5. Recurring Corporate Meetings",
  [GDI_BASE_OF_DEMAND.CORPORATE_TRIGGER_DEMAND]: "6. Corporate Trigger Demand",
  [GDI_BASE_OF_DEMAND.PHARMA_MEDICAL_ECOSYSTEM]: "7. Pharma / Medical Ecosystem",
  [GDI_BASE_OF_DEMAND.PROJECT_WORKFORCE_DEMAND]: "8. Project / Workforce Demand",
  [GDI_BASE_OF_DEMAND.SPORTS_ENTERTAINMENT_PRODUCTION]: "9. Sports / Entertainment / Production",
  [GDI_BASE_OF_DEMAND.HOTEL_HISTORY_LOOKALIKE]: "10. Hotel History + Lookalike",
});
