/**
 * International Opportunity Completion V2 — minimal disposition/list enums.
 * Does not replace Ready/Watch gates or add discovery spines.
 */

export const IOC_VERSION = "gdi_international_opportunity_completion_v2";

export const FINAL_MISSING_PILLAR = Object.freeze({
  NAMED_TRAVELING_ENTITY: "NAMED_TRAVELING_ENTITY",
  CURRENT_CYCLE_PARTICIPATION: "CURRENT_CYCLE_PARTICIPATION",
  GROUP_MOTION: "GROUP_MOTION",
  HOTEL_LIST_INCLUSION: "HOTEL_LIST_INCLUSION",
  HOTEL_SELECTION_OPEN: "HOTEL_SELECTION_OPEN",
  ROOM_BLOCK_PATH: "ROOM_BLOCK_PATH",
  BUYER_CONTACT: "BUYER_CONTACT",
  FUTURE_DECISION: "FUTURE_DECISION",
  TARGET_HOTEL_FIT: "TARGET_HOTEL_FIT",
  OTHER: "OTHER",
});

export const PARTICIPATION_CLASS = Object.freeze({
  CURRENT_CONFIRMED: "CURRENT_CONFIRMED",
  CURRENT_STRONG: "CURRENT_STRONG",
  CURRENT_PLAUSIBLE: "CURRENT_PLAUSIBLE",
  PRIOR_CYCLE_ONLY: "PRIOR_CYCLE_ONLY",
  UNCONFIRMED: "UNCONFIRMED",
  REJECT: "REJECT",
});

export const TRAVEL_MOTION = Object.freeze({
  PROVEN: "PROVEN",
  STRONG_INFERENCE: "STRONG_INFERENCE",
  UNRESOLVED: "UNRESOLVED",
  NONE: "NONE",
});

export const HOTEL_LIST_STATE = Object.freeze({
  NOT_YET_SELECTED: "NOT_YET_SELECTED",
  SUBMISSIONS_OPEN: "SUBMISSIONS_OPEN",
  UNDER_REVIEW: "UNDER_REVIEW",
  TARGET_HOTEL_LISTED: "TARGET_HOTEL_LISTED",
  OTHER_HOTELS_LISTED_TARGET_ABSENT: "OTHER_HOTELS_LISTED_TARGET_ABSENT",
  OFFICIAL_HOTEL_LOCKED: "OFFICIAL_HOTEL_LOCKED",
  MULTI_HOTEL_OPEN: "MULTI_HOTEL_OPEN",
  SELF_BOOKING: "SELF_BOOKING",
  CLOSED: "CLOSED",
  UNKNOWN: "UNKNOWN",
  NO_HOTEL_PROGRAM: "NO_HOTEL_PROGRAM",
});

export const CONTACT_PATH_CLASS = Object.freeze({
  NAMED_BUYER_PERSON: "NAMED_BUYER_PERSON",
  PCO_CONTACT: "PCO_CONTACT",
  HOUSING_CONTACT: "HOUSING_CONTACT",
  SECRETARIAT_CONTACT: "SECRETARIAT_CONTACT",
  EVENT_TEAM_CONTACT: "EVENT_TEAM_CONTACT",
  PROCUREMENT_CONTACT: "PROCUREMENT_CONTACT",
  FUNCTIONAL_EMAIL: "FUNCTIONAL_EMAIL",
  GENERIC_FORM: "GENERIC_FORM",
  NONE: "NONE",
});
